package wireless

import (
	"fmt"
	"strings"

	"github.com/rforced/ostiole/internal/model"
)

// Header marks the generated files as outputs.
const Header = "# Generated by ostiole. Do not edit; changes are overwritten on apply.\n"

// Render writes one radio's hostapd configuration. The first network is
// hostapd's own interface and the rest are bss blocks on it. A nil phy
// leaves out the capability lines, so a router without the card still
// renders a plan and the preflight is what refuses it.
func Render(country string, r model.Radio, nets []model.Interface, phy *Phy, master map[string]string,
	level model.LogLevel) string {
	if len(nets) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString(Header)
	put := func(k string, v any) { fmt.Fprintf(&b, "%s=%v\n", k, v) }

	var info BandInfo
	if phy != nil {
		info = phy.Bands[r.Band]
	}
	hw := "a"
	if r.Band == model.Band2G {
		hw = "g"
	}
	put("interface", nets[0].Name)
	put("driver", "nl80211")
	put("ctrl_interface", "/run/hostapd/"+r.Name)
	// The module log goes to syslog with a priority the level cap can
	// read, and not to stdout as well, so no association is written twice.
	// hostapd's own messages still go to stdout: no distribution builds
	// the -s that would send them to syslog, so at the journal's default
	// priority the cap drops them along with the client addresses they
	// carry. A radio that will not start explains itself at info.
	put("logger_syslog", -1)
	put("logger_syslog_level", syslogLevel(level))
	put("logger_stdout", 0)
	put("country_code", country)
	put("ieee80211d", 1)
	put("hw_mode", hw)
	put("channel", r.Channel)
	if r.Channel == 0 {
		put("acs_exclude_dfs", 1)
	}
	if r.Band == model.Band6G {
		put("op_class", opClass(r.Width))
	}

	modern := r.Standard == model.StandardN || r.Standard == model.StandardAC || r.Standard == model.StandardAX
	if modern && r.Band != model.Band6G {
		put("ieee80211n", 1)
		capab := append([]string{}, info.HTCapab...)
		if phy != nil && r.Width >= 40 {
			capab = append([]string{secondary(r.Band, r.Channel)}, capab...)
		}
		if len(capab) > 0 {
			put("ht_capab", strings.Join(capab, ""))
		}
	}
	if r.Band == model.Band5G && (r.Standard == model.StandardAC || r.Standard == model.StandardAX) {
		put("ieee80211ac", 1)
		if len(info.VHTCapab) > 0 {
			put("vht_capab", strings.Join(info.VHTCapab, ""))
		}
		put("vht_oper_chwidth", chwidth(r.Width))
		if idx, ok := centre(r.Band, r.Channel, r.Width); ok {
			put("vht_oper_centr_freq_seg0_idx", idx)
		}
	}
	if r.Standard == model.StandardAX {
		put("ieee80211ax", 1)
		put("he_oper_chwidth", chwidth(r.Width))
		if idx, ok := centre(r.Band, r.Channel, r.Width); ok {
			put("he_oper_centr_freq_seg0_idx", idx)
		}
	}
	put("wmm_enabled", 1)

	for i, in := range nets {
		if i > 0 {
			put("bss", in.Name)
		}
		n := in.Wireless
		put("ssid", n.SSID)
		if m := master[in.Name]; m != "" {
			put("bridge", m)
		}
		put("ignore_broadcast_ssid", boolInt(n.Hidden))
		put("ap_isolate", boolInt(n.Isolate))
		if n.MaxClients > 0 {
			put("max_num_sta", n.MaxClients)
		}
		if n.Security == model.SecurityOpen {
			continue
		}
		put("wpa", 2)
		put("wpa_key_mgmt", keyMgmt(n.Security))
		put("rsn_pairwise", "CCMP")
		if n.Security.NeedsPassphrase() {
			put("wpa_passphrase", n.Passphrase)
		}
		put("ieee80211w", pmf(n.Security))
		// Signed beacons, so nobody can forge this network's beacons to
		// move or deauthenticate its clients. It needs protected
		// management frames and a card that can sign on the AP side.
		if pmf(n.Security) > 0 && phy != nil && phy.BeaconProtection() {
			put("beacon_prot", 1)
		}
		if n.Security == model.SecurityMixed {
			put("sae_require_mfp", 1)
		}
		if n.Security == model.SecurityWPA3 || n.Security == model.SecurityMixed {
			put("sae_pwe", saePWE(r.Band))
		}
	}
	return b.String()
}

// syslogLevel maps the router's log level onto hostapd's scale, where 0
// is every frame and 4 is nothing below an error. Info is 2, which is
// where each association and each disassociation is written.
func syslogLevel(l model.LogLevel) int {
	switch l {
	case model.LogInfo:
		return 2
	case model.LogDebug:
		return 1
	default:
		return 4
	}
}

// Env is the unit's environment: which device to set the power on and
// which interface to create for hostapd. The rest is what the radio was
// asked for, so an apply can check it against the card without reading
// the configuration back.
func Env(country string, r model.Radio, phy *Phy, nets []model.Interface) string {
	name := "phy0"
	if phy != nil && phy.Name != "" {
		name = phy.Name
	}
	power := "auto"
	if r.Power > 0 {
		power = fmt.Sprintf("limit %d", r.Power*100)
	}
	first := ""
	if len(nets) > 0 {
		first = nets[0].Name
	}
	return fmt.Sprintf("PHY=%s\nAP=%s\nTXPOWER=%s\nCOUNTRY=%s\nBAND=%s\nCHANNEL=%d\nWIDTH=%d\nSTANDARD=%s\nNETWORKS=%d\n",
		name, first, power, country, r.Band, r.Channel, r.Width, r.Standard, len(nets))
}

// EnvPlan is what Env recorded about a radio.
type EnvPlan struct {
	PHY      string
	AP       string
	Country  string
	Band     model.Band
	Channel  int
	Width    int
	Standard model.Standard
	Networks int
}

// ParseEnv reads back what Env wrote.
func ParseEnv(text string) EnvPlan {
	var p EnvPlan
	for _, line := range strings.Split(text, "\n") {
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		switch key {
		case "PHY":
			p.PHY = value
		case "AP":
			p.AP = value
		case "COUNTRY":
			p.Country = value
		case "BAND":
			p.Band = model.Band(value)
		case "CHANNEL":
			p.Channel = int(number(value))
		case "WIDTH":
			p.Width = int(number(value))
		case "STANDARD":
			p.Standard = model.Standard(value)
		case "NETWORKS":
			p.Networks = int(number(value))
		}
	}
	return p
}

func keyMgmt(s model.Security) string {
	switch s {
	case model.SecurityWPA3:
		return "SAE"
	case model.SecurityMixed:
		return "WPA-PSK SAE"
	case model.SecurityOWE:
		return "OWE"
	}
	return "WPA-PSK"
}

// pmf is protected management frames: required where the standard says
// so, optional where an older client still has to get on.
func pmf(s model.Security) int {
	if s == model.SecurityWPA3 || s == model.SecurityOWE {
		return 2
	}
	return 1
}

// saePWE picks how a passphrase becomes a key. 6 GHz takes hash-to-element
// only; elsewhere the older way has to stay available.
func saePWE(b model.Band) int {
	if b == model.Band6G {
		return 1
	}
	return 2
}

func opClass(width int) int {
	switch width {
	case 40:
		return 132
	case 80:
		return 133
	case 160:
		return 134
	}
	return 131
}

func chwidth(width int) int {
	switch width {
	case 80:
		return 1
	case 160:
		return 2
	}
	return 0
}

// secondary is where the second 20 MHz of a 40 MHz channel sits.
func secondary(b model.Band, channel int) string {
	if ht40Plus(b, channel) {
		return "[HT40+]"
	}
	return "[HT40-]"
}

func ht40Plus(b model.Band, channel int) bool {
	if channel == 0 {
		// A card picking its own channel moves the pair with it.
		return true
	}
	switch b {
	case model.Band2G:
		return channel <= 7
	case model.Band6G:
		return (channel-1)%8 == 0
	}
	// The 5 GHz pairs start at 36 and again at 149, where the band was
	// extended on a boundary of its own.
	return (channel-36)%8 == 0 || (channel-149)%8 == 0
}

// centres80 and centres160 map the first channel of a wide block to the
// middle of it. 6 GHz is regular enough to compute.
var (
	centres80  = map[int]int{36: 42, 52: 58, 100: 106, 116: 122, 132: 138, 149: 155, 165: 171}
	centres160 = map[int]int{36: 50, 100: 114, 149: 163}
)

// centre is the index hostapd puts at the middle of a wide channel. A
// 20 or 40 MHz channel has none: hostapd works it out from the secondary,
// and so does a card picking its own channel.
func centre(b model.Band, channel, width int) (int, bool) {
	if channel == 0 || width < 80 {
		return 0, false
	}
	if b == model.Band6G {
		if width == 160 {
			return channel - (channel-1)%32 + 14, true
		}
		return channel - (channel-1)%16 + 6, true
	}
	if b != model.Band5G {
		return 0, false
	}
	span, table := 12, centres80
	if width == 160 {
		span, table = 28, centres160
	}
	for start, c := range table {
		if channel >= start && channel <= start+span {
			return c, true
		}
	}
	return 0, false
}

func boolInt(b bool) int {
	if b {
		return 1
	}
	return 0
}
