/**
 * The countries a GeoIP alias can name, with a region to group them by.
 *
 * Codes and names come from the tz database's iso3166.tab, and the region
 * from the continent half of each country's time zone in zone.tab. Both are
 * public domain and change about as often as countries do.
 *
 * A country alias holds these codes; the addresses behind them are fetched
 * from the GeoIP source set under System.
 */

/** @typedef {{code: string, name: string, region: string}} Country */

/** @type {Country[]} */
export const COUNTRIES = [
  { code: 'af', name: 'Afghanistan', region: 'Asia' },
  { code: 'al', name: 'Albania', region: 'Europe' },
  { code: 'dz', name: 'Algeria', region: 'Africa' },
  { code: 'ad', name: 'Andorra', region: 'Europe' },
  { code: 'ao', name: 'Angola', region: 'Africa' },
  { code: 'ai', name: 'Anguilla', region: 'The Americas' },
  { code: 'aq', name: 'Antarctica', region: 'Antarctica' },
  { code: 'ag', name: 'Antigua & Barbuda', region: 'The Americas' },
  { code: 'ar', name: 'Argentina', region: 'The Americas' },
  { code: 'am', name: 'Armenia', region: 'Asia' },
  { code: 'aw', name: 'Aruba', region: 'The Americas' },
  { code: 'au', name: 'Australia', region: 'Oceania' },
  { code: 'at', name: 'Austria', region: 'Europe' },
  { code: 'az', name: 'Azerbaijan', region: 'Asia' },
  { code: 'bs', name: 'Bahamas', region: 'The Americas' },
  { code: 'bh', name: 'Bahrain', region: 'Asia' },
  { code: 'bd', name: 'Bangladesh', region: 'Asia' },
  { code: 'bb', name: 'Barbados', region: 'The Americas' },
  { code: 'by', name: 'Belarus', region: 'Europe' },
  { code: 'be', name: 'Belgium', region: 'Europe' },
  { code: 'bz', name: 'Belize', region: 'The Americas' },
  { code: 'bj', name: 'Benin', region: 'Africa' },
  { code: 'bm', name: 'Bermuda', region: 'Atlantic' },
  { code: 'bt', name: 'Bhutan', region: 'Asia' },
  { code: 'bo', name: 'Bolivia', region: 'The Americas' },
  { code: 'ba', name: 'Bosnia & Herzegovina', region: 'Europe' },
  { code: 'bw', name: 'Botswana', region: 'Africa' },
  { code: 'bv', name: 'Bouvet Island', region: 'Atlantic' },
  { code: 'br', name: 'Brazil', region: 'The Americas' },
  { code: 'gb', name: 'Britain (UK)', region: 'Europe' },
  { code: 'io', name: 'British Indian Ocean Territory', region: 'Indian Ocean' },
  { code: 'bn', name: 'Brunei', region: 'Asia' },
  { code: 'bg', name: 'Bulgaria', region: 'Europe' },
  { code: 'bf', name: 'Burkina Faso', region: 'Africa' },
  { code: 'bi', name: 'Burundi', region: 'Africa' },
  { code: 'kh', name: 'Cambodia', region: 'Asia' },
  { code: 'cm', name: 'Cameroon', region: 'Africa' },
  { code: 'ca', name: 'Canada', region: 'The Americas' },
  { code: 'cv', name: 'Cape Verde', region: 'Atlantic' },
  { code: 'bq', name: 'Caribbean NL', region: 'The Americas' },
  { code: 'ky', name: 'Cayman Islands', region: 'The Americas' },
  { code: 'cf', name: 'Central African Rep.', region: 'Africa' },
  { code: 'td', name: 'Chad', region: 'Africa' },
  { code: 'cl', name: 'Chile', region: 'The Americas' },
  { code: 'cn', name: 'China', region: 'Asia' },
  { code: 'cx', name: 'Christmas Island', region: 'Indian Ocean' },
  { code: 'cc', name: 'Cocos (Keeling) Islands', region: 'Indian Ocean' },
  { code: 'co', name: 'Colombia', region: 'The Americas' },
  { code: 'km', name: 'Comoros', region: 'Indian Ocean' },
  { code: 'cd', name: 'Congo (Dem. Rep.)', region: 'Africa' },
  { code: 'cg', name: 'Congo (Rep.)', region: 'Africa' },
  { code: 'ck', name: 'Cook Islands', region: 'Oceania' },
  { code: 'cr', name: 'Costa Rica', region: 'The Americas' },
  { code: 'hr', name: 'Croatia', region: 'Europe' },
  { code: 'cu', name: 'Cuba', region: 'The Americas' },
  { code: 'cw', name: 'Curaçao', region: 'The Americas' },
  { code: 'cy', name: 'Cyprus', region: 'Asia' },
  { code: 'cz', name: 'Czech Republic', region: 'Europe' },
  { code: 'ci', name: 'Côte d’Ivoire', region: 'Africa' },
  { code: 'dk', name: 'Denmark', region: 'Europe' },
  { code: 'dj', name: 'Djibouti', region: 'Africa' },
  { code: 'dm', name: 'Dominica', region: 'The Americas' },
  { code: 'do', name: 'Dominican Republic', region: 'The Americas' },
  { code: 'tl', name: 'East Timor', region: 'Asia' },
  { code: 'ec', name: 'Ecuador', region: 'The Americas' },
  { code: 'eg', name: 'Egypt', region: 'Africa' },
  { code: 'sv', name: 'El Salvador', region: 'The Americas' },
  { code: 'gq', name: 'Equatorial Guinea', region: 'Africa' },
  { code: 'er', name: 'Eritrea', region: 'Africa' },
  { code: 'ee', name: 'Estonia', region: 'Europe' },
  { code: 'sz', name: 'Eswatini (Swaziland)', region: 'Africa' },
  { code: 'et', name: 'Ethiopia', region: 'Africa' },
  { code: 'fk', name: 'Falkland Islands', region: 'Atlantic' },
  { code: 'fo', name: 'Faroe Islands', region: 'Atlantic' },
  { code: 'fj', name: 'Fiji', region: 'Oceania' },
  { code: 'fi', name: 'Finland', region: 'Europe' },
  { code: 'fr', name: 'France', region: 'Europe' },
  { code: 'gf', name: 'French Guiana', region: 'The Americas' },
  { code: 'pf', name: 'French Polynesia', region: 'Oceania' },
  { code: 'tf', name: 'French S. Terr.', region: 'Indian Ocean' },
  { code: 'ga', name: 'Gabon', region: 'Africa' },
  { code: 'gm', name: 'Gambia', region: 'Africa' },
  { code: 'ge', name: 'Georgia', region: 'Asia' },
  { code: 'de', name: 'Germany', region: 'Europe' },
  { code: 'gh', name: 'Ghana', region: 'Africa' },
  { code: 'gi', name: 'Gibraltar', region: 'Europe' },
  { code: 'gr', name: 'Greece', region: 'Europe' },
  { code: 'gl', name: 'Greenland', region: 'The Americas' },
  { code: 'gd', name: 'Grenada', region: 'The Americas' },
  { code: 'gp', name: 'Guadeloupe', region: 'The Americas' },
  { code: 'gu', name: 'Guam', region: 'Oceania' },
  { code: 'gt', name: 'Guatemala', region: 'The Americas' },
  { code: 'gg', name: 'Guernsey', region: 'Europe' },
  { code: 'gn', name: 'Guinea', region: 'Africa' },
  { code: 'gw', name: 'Guinea-Bissau', region: 'Africa' },
  { code: 'gy', name: 'Guyana', region: 'The Americas' },
  { code: 'ht', name: 'Haiti', region: 'The Americas' },
  { code: 'hm', name: 'Heard & McDonald Islands', region: 'Indian Ocean' },
  { code: 'hn', name: 'Honduras', region: 'The Americas' },
  { code: 'hk', name: 'Hong Kong', region: 'Asia' },
  { code: 'hu', name: 'Hungary', region: 'Europe' },
  { code: 'is', name: 'Iceland', region: 'Atlantic' },
  { code: 'in', name: 'India', region: 'Asia' },
  { code: 'id', name: 'Indonesia', region: 'Asia' },
  { code: 'ir', name: 'Iran', region: 'Asia' },
  { code: 'iq', name: 'Iraq', region: 'Asia' },
  { code: 'ie', name: 'Ireland', region: 'Europe' },
  { code: 'im', name: 'Isle of Man', region: 'Europe' },
  { code: 'il', name: 'Israel', region: 'Asia' },
  { code: 'it', name: 'Italy', region: 'Europe' },
  { code: 'jm', name: 'Jamaica', region: 'The Americas' },
  { code: 'jp', name: 'Japan', region: 'Asia' },
  { code: 'je', name: 'Jersey', region: 'Europe' },
  { code: 'jo', name: 'Jordan', region: 'Asia' },
  { code: 'kz', name: 'Kazakhstan', region: 'Asia' },
  { code: 'ke', name: 'Kenya', region: 'Africa' },
  { code: 'ki', name: 'Kiribati', region: 'Oceania' },
  { code: 'kp', name: 'Korea (North)', region: 'Asia' },
  { code: 'kr', name: 'Korea (South)', region: 'Asia' },
  { code: 'kw', name: 'Kuwait', region: 'Asia' },
  { code: 'kg', name: 'Kyrgyzstan', region: 'Asia' },
  { code: 'la', name: 'Laos', region: 'Asia' },
  { code: 'lv', name: 'Latvia', region: 'Europe' },
  { code: 'lb', name: 'Lebanon', region: 'Asia' },
  { code: 'ls', name: 'Lesotho', region: 'Africa' },
  { code: 'lr', name: 'Liberia', region: 'Africa' },
  { code: 'ly', name: 'Libya', region: 'Africa' },
  { code: 'li', name: 'Liechtenstein', region: 'Europe' },
  { code: 'lt', name: 'Lithuania', region: 'Europe' },
  { code: 'lu', name: 'Luxembourg', region: 'Europe' },
  { code: 'mo', name: 'Macau', region: 'Asia' },
  { code: 'mg', name: 'Madagascar', region: 'Indian Ocean' },
  { code: 'mw', name: 'Malawi', region: 'Africa' },
  { code: 'my', name: 'Malaysia', region: 'Asia' },
  { code: 'mv', name: 'Maldives', region: 'Indian Ocean' },
  { code: 'ml', name: 'Mali', region: 'Africa' },
  { code: 'mt', name: 'Malta', region: 'Europe' },
  { code: 'mh', name: 'Marshall Islands', region: 'Oceania' },
  { code: 'mq', name: 'Martinique', region: 'The Americas' },
  { code: 'mr', name: 'Mauritania', region: 'Africa' },
  { code: 'mu', name: 'Mauritius', region: 'Indian Ocean' },
  { code: 'yt', name: 'Mayotte', region: 'Indian Ocean' },
  { code: 'mx', name: 'Mexico', region: 'The Americas' },
  { code: 'fm', name: 'Micronesia', region: 'Oceania' },
  { code: 'md', name: 'Moldova', region: 'Europe' },
  { code: 'mc', name: 'Monaco', region: 'Europe' },
  { code: 'mn', name: 'Mongolia', region: 'Asia' },
  { code: 'me', name: 'Montenegro', region: 'Europe' },
  { code: 'ms', name: 'Montserrat', region: 'The Americas' },
  { code: 'ma', name: 'Morocco', region: 'Africa' },
  { code: 'mz', name: 'Mozambique', region: 'Africa' },
  { code: 'mm', name: 'Myanmar (Burma)', region: 'Asia' },
  { code: 'na', name: 'Namibia', region: 'Africa' },
  { code: 'nr', name: 'Nauru', region: 'Oceania' },
  { code: 'np', name: 'Nepal', region: 'Asia' },
  { code: 'nl', name: 'Netherlands', region: 'Europe' },
  { code: 'nc', name: 'New Caledonia', region: 'Oceania' },
  { code: 'nz', name: 'New Zealand', region: 'Oceania' },
  { code: 'ni', name: 'Nicaragua', region: 'The Americas' },
  { code: 'ne', name: 'Niger', region: 'Africa' },
  { code: 'ng', name: 'Nigeria', region: 'Africa' },
  { code: 'nu', name: 'Niue', region: 'Oceania' },
  { code: 'nf', name: 'Norfolk Island', region: 'Oceania' },
  { code: 'mk', name: 'North Macedonia', region: 'Europe' },
  { code: 'mp', name: 'Northern Mariana Islands', region: 'Oceania' },
  { code: 'no', name: 'Norway', region: 'Europe' },
  { code: 'om', name: 'Oman', region: 'Asia' },
  { code: 'pk', name: 'Pakistan', region: 'Asia' },
  { code: 'pw', name: 'Palau', region: 'Oceania' },
  { code: 'ps', name: 'Palestine', region: 'Asia' },
  { code: 'pa', name: 'Panama', region: 'The Americas' },
  { code: 'pg', name: 'Papua New Guinea', region: 'Oceania' },
  { code: 'py', name: 'Paraguay', region: 'The Americas' },
  { code: 'pe', name: 'Peru', region: 'The Americas' },
  { code: 'ph', name: 'Philippines', region: 'Asia' },
  { code: 'pn', name: 'Pitcairn', region: 'Oceania' },
  { code: 'pl', name: 'Poland', region: 'Europe' },
  { code: 'pt', name: 'Portugal', region: 'Europe' },
  { code: 'pr', name: 'Puerto Rico', region: 'The Americas' },
  { code: 'qa', name: 'Qatar', region: 'Asia' },
  { code: 'ro', name: 'Romania', region: 'Europe' },
  { code: 'ru', name: 'Russia', region: 'Europe' },
  { code: 'rw', name: 'Rwanda', region: 'Africa' },
  { code: 're', name: 'Réunion', region: 'Indian Ocean' },
  { code: 'as', name: 'Samoa (American)', region: 'Oceania' },
  { code: 'ws', name: 'Samoa (western)', region: 'Oceania' },
  { code: 'sm', name: 'San Marino', region: 'Europe' },
  { code: 'st', name: 'Sao Tome & Principe', region: 'Africa' },
  { code: 'sa', name: 'Saudi Arabia', region: 'Asia' },
  { code: 'sn', name: 'Senegal', region: 'Africa' },
  { code: 'rs', name: 'Serbia', region: 'Europe' },
  { code: 'sc', name: 'Seychelles', region: 'Indian Ocean' },
  { code: 'sl', name: 'Sierra Leone', region: 'Africa' },
  { code: 'sg', name: 'Singapore', region: 'Asia' },
  { code: 'sk', name: 'Slovakia', region: 'Europe' },
  { code: 'si', name: 'Slovenia', region: 'Europe' },
  { code: 'sb', name: 'Solomon Islands', region: 'Oceania' },
  { code: 'so', name: 'Somalia', region: 'Africa' },
  { code: 'za', name: 'South Africa', region: 'Africa' },
  { code: 'gs', name: 'South Georgia & the South Sandwich Islands', region: 'Atlantic' },
  { code: 'ss', name: 'South Sudan', region: 'Africa' },
  { code: 'es', name: 'Spain', region: 'Europe' },
  { code: 'lk', name: 'Sri Lanka', region: 'Asia' },
  { code: 'bl', name: 'St Barthelemy', region: 'The Americas' },
  { code: 'sh', name: 'St Helena', region: 'Atlantic' },
  { code: 'kn', name: 'St Kitts & Nevis', region: 'The Americas' },
  { code: 'lc', name: 'St Lucia', region: 'The Americas' },
  { code: 'sx', name: 'St Maarten (Dutch)', region: 'The Americas' },
  { code: 'mf', name: 'St Martin (French)', region: 'The Americas' },
  { code: 'pm', name: 'St Pierre & Miquelon', region: 'The Americas' },
  { code: 'vc', name: 'St Vincent', region: 'The Americas' },
  { code: 'sd', name: 'Sudan', region: 'Africa' },
  { code: 'sr', name: 'Suriname', region: 'The Americas' },
  { code: 'sj', name: 'Svalbard & Jan Mayen', region: 'Europe' },
  { code: 'se', name: 'Sweden', region: 'Europe' },
  { code: 'ch', name: 'Switzerland', region: 'Europe' },
  { code: 'sy', name: 'Syria', region: 'Asia' },
  { code: 'tw', name: 'Taiwan', region: 'Asia' },
  { code: 'tj', name: 'Tajikistan', region: 'Asia' },
  { code: 'tz', name: 'Tanzania', region: 'Africa' },
  { code: 'th', name: 'Thailand', region: 'Asia' },
  { code: 'tg', name: 'Togo', region: 'Africa' },
  { code: 'tk', name: 'Tokelau', region: 'Oceania' },
  { code: 'to', name: 'Tonga', region: 'Oceania' },
  { code: 'tt', name: 'Trinidad & Tobago', region: 'The Americas' },
  { code: 'tn', name: 'Tunisia', region: 'Africa' },
  { code: 'tr', name: 'Turkey', region: 'Europe' },
  { code: 'tm', name: 'Turkmenistan', region: 'Asia' },
  { code: 'tc', name: 'Turks & Caicos Is', region: 'The Americas' },
  { code: 'tv', name: 'Tuvalu', region: 'Oceania' },
  { code: 'um', name: 'US minor outlying islands', region: 'Oceania' },
  { code: 'ug', name: 'Uganda', region: 'Africa' },
  { code: 'ua', name: 'Ukraine', region: 'Europe' },
  { code: 'ae', name: 'United Arab Emirates', region: 'Asia' },
  { code: 'us', name: 'United States', region: 'The Americas' },
  { code: 'uy', name: 'Uruguay', region: 'The Americas' },
  { code: 'uz', name: 'Uzbekistan', region: 'Asia' },
  { code: 'vu', name: 'Vanuatu', region: 'Oceania' },
  { code: 'va', name: 'Vatican City', region: 'Europe' },
  { code: 've', name: 'Venezuela', region: 'The Americas' },
  { code: 'vn', name: 'Vietnam', region: 'Asia' },
  { code: 'vg', name: 'Virgin Islands (UK)', region: 'The Americas' },
  { code: 'vi', name: 'Virgin Islands (US)', region: 'The Americas' },
  { code: 'wf', name: 'Wallis & Futuna', region: 'Oceania' },
  { code: 'eh', name: 'Western Sahara', region: 'Africa' },
  { code: 'ye', name: 'Yemen', region: 'Asia' },
  { code: 'zm', name: 'Zambia', region: 'Africa' },
  { code: 'zw', name: 'Zimbabwe', region: 'Africa' },
  { code: 'ax', name: 'Åland Islands', region: 'Europe' },
]

/** Regions in the order the picker lists them. */
export const REGIONS = [
  'Africa',
  'Asia',
  'Europe',
  'The Americas',
  'Oceania',
  'Atlantic',
  'Indian Ocean',
  'Antarctica',
]

/**
 * Groups that are worth one click. The European Union is not a region, but
 * it is the selection people most often want, so it is offered as one.
 */
export const PRESETS = [
  {
    name: 'European Union',
    codes: [
      'at',
      'be',
      'bg',
      'hr',
      'cy',
      'cz',
      'dk',
      'ee',
      'fi',
      'fr',
      'de',
      'gr',
      'hu',
      'ie',
      'it',
      'lv',
      'lt',
      'lu',
      'mt',
      'nl',
      'pl',
      'pt',
      'ro',
      'sk',
      'si',
      'es',
      'se',
    ],
  },
]
