package shaping

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rforced/ostiole/internal/model"
	"github.com/rforced/ostiole/internal/network"
)

// FileHeader marks the rendered batches as outputs. Batch strips it, and
// every other comment, before handing the script to tc, which has no
// notion of one.
const FileHeader = "# Generated by ostiole. Do not edit; changes are overwritten on apply.\n"

// File name suffixes. One interface gets up to two: the queue that hangs
// off the device itself, and the one that hangs off its helper.
const (
	EgressSuffix  = ".egress.tc"
	IngressSuffix = ".ingress.tc"
)

// EgressFile names the batch for the direction that leaves an interface.
func EgressFile(iface string) string { return iface + EgressSuffix }

// IngressFile names the batch for the direction that arrives on it.
func IngressFile(iface string) string { return iface + IngressSuffix }

// Render turns the configuration into the tc batches that install it. The
// files are the snapshot a revert restores, so what is on disk is always
// what the kernel was last told.
func Render(cfg *model.Config) (network.Files, error) {
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	files := network.Files{}
	for _, p := range Plans(cfg) {
		if p.Egress != nil {
			files[EgressFile(p.Interface)] = renderEgress(p)
		}
		if p.Ingress != nil {
			files[IngressFile(p.Interface)] = renderIngress(p)
		}
	}
	return files, nil
}

// renderEgress hangs the queue off the device's own root, replacing
// whatever the kernel put there (mq, fq_codel) for as long as Ostiole is
// shaping this interface.
func renderEgress(p Plan) string {
	return FileHeader + fmt.Sprintf("qdisc replace dev %s root handle %x: %s\n",
		p.Interface, Handle, cake(*p.Egress))
}

// renderIngress sends what arrives on the interface through a helper
// device, because the kernel only queues on the way out of somewhere.
//
// The filter restores the tier from the connection first: on the way in
// nftables has not run yet, so the only thing that knows which tier a
// packet belongs to is conntrack, and act_ctinfo is what asks it.
//
// Replacing the filter in place is not idempotent — a second run either
// stacks a duplicate or refuses outright — so the whole parent is cleared
// and one filter added back at a fixed preference and handle.
func renderIngress(p Plan) string {
	var b strings.Builder
	b.WriteString(FileHeader)
	fmt.Fprintf(&b, "qdisc replace dev %s handle ffff: ingress\n", p.Interface)
	fmt.Fprintf(&b, "filter del dev %s parent ffff:\n", p.Interface)
	fmt.Fprintf(&b, "filter add dev %s parent ffff: pref %d handle %d matchall"+
		" action ctinfo cpmark 0x%08x action mirred egress redirect dev %s\n",
		p.Interface, FilterPref, FilterHandle, model.ShapeMarkMask, p.IFB)
	fmt.Fprintf(&b, "qdisc replace dev %s root handle %x: %s\n", p.IFB, Handle, cake(*p.Ingress))
	return b.String()
}

// cake is the qdisc specification: the rate, how the line is framed, and
// where to read the tier from.
func cake(q Queue) string {
	parts := append([]string{"cake", "bandwidth", fmt.Sprintf("%dbit", q.Rate)}, q.Options...)
	parts = append(parts, "fwmark", fmt.Sprintf("0x%08x", model.ShapeMarkMask))
	return strings.Join(parts, " ")
}

// BatchFor is the script that installs everything one interface needs, in
// the order tc takes it: the queue on the device, then the redirection
// that gives the other direction one too.
func BatchFor(files network.Files, iface string) string {
	return files[EgressFile(iface)] + files[IngressFile(iface)]
}

// Devices names the interfaces a set of files covers, sorted so a
// reconcile is deterministic.
func Devices(files network.Files) []string {
	seen := map[string]bool{}
	for name := range files {
		switch {
		case strings.HasSuffix(name, EgressSuffix):
			seen[strings.TrimSuffix(name, EgressSuffix)] = true
		case strings.HasSuffix(name, IngressSuffix):
			seen[strings.TrimSuffix(name, IngressSuffix)] = true
		}
	}
	out := make([]string, 0, len(seen))
	for name := range seen {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// wanted reports which halves of an interface a set of files asks for.
func wanted(files network.Files, iface string) (egress, ingress bool) {
	_, egress = files[EgressFile(iface)]
	_, ingress = files[IngressFile(iface)]
	return egress, ingress
}
