package model

import (
	"fmt"
	"hash/fnv"
	"net/netip"
	"regexp"
	"slices"
	"strings"
)

// certIDRe is what a certificate may be called. It is a directory name
// and a URL segment, so it is narrower than an ordinary id.
var certIDRe = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,31}$`)

// ValidCertificateID reports whether id could name a certificate. The
// store and the API refuse anything else before it reaches a path.
func ValidCertificateID(id string) bool { return certIDRe.MatchString(id) }

// ACME is how this router gets certificates: the accounts it holds at a
// CA and the DNS providers a dns-01 challenge writes to.
type ACME struct {
	Accounts  []ACMEAccount `json:"accounts,omitempty"`
	Providers []DNSProvider `json:"providers,omitempty"`
}

// ACMEAccount is one account at one CA. The key is generated by the
// API when the account is created and never leaves the configuration.
type ACMEAccount struct {
	ID          string `json:"id"`
	Description string `json:"description,omitempty"`
	// Directory is the CA's directory URL.
	Directory string `json:"directory"`
	// Email is where the CA writes about expiry; empty registers none.
	Email string `json:"email,omitempty"`
	// EABKeyID and EABHMAC bind the account to one a CA issued elsewhere.
	EABKeyID string `json:"eabKeyId,omitempty"`
	EABHMAC  string `json:"eabHmac,omitempty"`
	// PrivateKey is the account's key, PEM.
	PrivateKey string `json:"privateKey"`
	// CACert is a PEM certificate to trust for the directory, for a CA
	// browsers do not know.
	CACert string `json:"caCert,omitempty"`
}

// DNSProvider holds what a dns-01 challenge needs to write a record.
type DNSProvider struct {
	ID          string `json:"id"`
	Description string `json:"description,omitempty"`
	// Kind is one of ProviderKinds.
	Kind string `json:"kind"`
	// Settings are the kind's fields, by name.
	Settings map[string]string `json:"settings,omitempty"`
	// PropagationSeconds is how long to wait before the CA looks; 0 is
	// the kind's own default.
	PropagationSeconds int `json:"propagationSeconds,omitempty"`
}

// CertSource says where a certificate came from.
type CertSource string

// Certificate sources.
const (
	SourceACME     CertSource = "acme"
	SourceUploaded CertSource = "uploaded"
)

// CertSources lists them in the order the UI offers them.
var CertSources = []CertSource{SourceACME, SourceUploaded}

// Challenge is how a CA checks that this router holds a name.
type Challenge string

// Challenges.
const (
	ChallengeDNS  Challenge = "dns-01"
	ChallengeHTTP Challenge = "http-01"
)

// Challenges lists them in the order the UI offers them.
var Challenges = []Challenge{ChallengeDNS, ChallengeHTTP}

// Certificate is one certificate this router holds. Its files are under
// certs/<id> in the configuration directory whatever the source, so a
// service reads them by ID and nothing else.
type Certificate struct {
	ID          string     `json:"id"`
	Description string     `json:"description,omitempty"`
	Enabled     bool       `json:"enabled"`
	Source      CertSource `json:"source"`
	// Names are DNS names, wildcards, or IP addresses.
	Names []string `json:"names,omitempty"`
	// InterfaceAddresses adds the public addresses these interfaces have
	// when the certificate is issued; a change re-issues it.
	InterfaceAddresses []string  `json:"interfaceAddresses,omitempty"`
	Account            string    `json:"account,omitempty"`
	Challenge          Challenge `json:"challenge,omitempty"`
	// Provider is the DNS provider a dns-01 challenge uses.
	Provider string `json:"provider,omitempty"`
	// KeyType is ec256, ec384, rsa2048 or rsa4096; empty is ec256.
	KeyType string `json:"keyType,omitempty"`
	// Profile is what the CA offers; empty is its default. IP addresses
	// need shortlived, which is set for them.
	Profile string `json:"profile,omitempty"`
	// CertPEM and KeyPEM are an uploaded certificate, its chain under it.
	CertPEM string `json:"certPem,omitempty"`
	KeyPEM  string `json:"keyPem,omitempty"`
}

// KeyTypes are the keys a certificate can be issued for.
var KeyTypes = []string{"ec256", "ec384", "rsa2048", "rsa4096"}

// ProfileShortlived is the six-day profile. An IP address is only issued
// under it.
const ProfileShortlived = "shortlived"

// Profiles are the certificate profiles a CA may offer. Empty is the CA's
// own default.
var Profiles = []string{"", "classic", "tlsserver", ProfileShortlived}

// Directory URLs the account dialog offers by name.
const (
	ACMEDirectoryLetsEncrypt        = "https://acme-v02.api.letsencrypt.org/directory"
	ACMEDirectoryLetsEncryptStaging = "https://acme-staging-v02.api.letsencrypt.org/directory"
)

// CronIDCertificates is the derived cron that renews what is due.
const CronIDCertificates = "system:certificates"

// Certificate returns the certificate with the given id.
func (c *Config) Certificate(id string) (*Certificate, bool) {
	for i := range c.Certificates {
		if c.Certificates[i].ID == id {
			return &c.Certificates[i], true
		}
	}
	return nil, false
}

// ACMEAccount returns the account with the given id.
func (c *Config) ACMEAccount(id string) (*ACMEAccount, bool) {
	for i := range c.ACME.Accounts {
		if c.ACME.Accounts[i].ID == id {
			return &c.ACME.Accounts[i], true
		}
	}
	return nil, false
}

// DNSProvider returns the provider with the given id.
func (c *Config) DNSProvider(id string) (*DNSProvider, bool) {
	for i := range c.ACME.Providers {
		if c.ACME.Providers[i].ID == id {
			return &c.ACME.Providers[i], true
		}
	}
	return nil, false
}

// HasIP reports whether this certificate covers an address rather than a
// name, either written out or through an interface.
func (c Certificate) HasIP() bool {
	if len(c.InterfaceAddresses) > 0 {
		return true
	}
	for _, n := range c.Names {
		if _, err := netip.ParseAddr(strings.TrimSpace(n)); err == nil {
			return true
		}
	}
	return false
}

// EffectiveProfile is the profile to ask the CA for. An address is only
// issued under the short-lived profile, so it is not a choice.
func (c Certificate) EffectiveProfile() string {
	if c.HasIP() {
		return ProfileShortlived
	}
	return c.Profile
}

// HTTP01Certificates reports whether anything on this router answers an
// http-01 challenge, which is what opens port 80.
func (c *Config) HTTP01Certificates() bool {
	for _, cert := range c.Certificates {
		if cert.Enabled && cert.Source == SourceACME && cert.Challenge == ChallengeHTTP {
			return true
		}
	}
	return false
}

// IssuesCertificates reports whether anything is waiting on the CA.
func (c *Config) IssuesCertificates() bool {
	return slices.ContainsFunc(c.Certificates, func(cert Certificate) bool {
		return cert.Enabled && cert.Source == SourceACME
	})
}

// CertificateSchedule is when the renewal cron runs: every hour, at a
// minute this router keeps to itself, so two routers at one CA do not
// knock at the same moment.
func (c *Config) CertificateSchedule() string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(c.System.Hostname))
	return fmt.Sprintf("%d * * * *", h.Sum32()%60)
}
