package network

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"net/netip"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/vishvananda/netlink"

	"github.com/rforced/ostiole/internal/model"
)

// Networkd renders systemd-networkd units. Ostiole owns every file in Dir
// whose name starts with Prefix; everything else is left alone. The prefix
// sorts before anything cloud-init or a distro drops in (10-…), because
// networkd applies the first .network file whose [Match] fits a link.
type Networkd struct {
	// Dir is where units live; default /etc/systemd/network.
	Dir string
	// Prefix marks Ostiole-owned files; default "00-ostiole-".
	Prefix string
	// Cmd runs networkctl; default execs it.
	Cmd Commander
	// DelLink removes a virtual device Ostiole created; default uses
	// netlink. Deleting a link that is already gone is not an error.
	DelLink func(name string) error
	// LinkExists reports whether the kernel has a device by this name;
	// default uses netlink.
	LinkExists func(name string) bool
}

// Defaults for Networkd.
const (
	NetworkdDir    = "/etc/systemd/network"
	NetworkdPrefix = "00-ostiole-"
)

const fileHeader = "# Generated by ostiole. Do not edit; changes are overwritten on apply.\n"

// NewNetworkd returns a backend with production defaults.
func NewNetworkd() *Networkd {
	return &Networkd{Dir: NetworkdDir, Prefix: NetworkdPrefix, Cmd: execCommander{}}
}

func (n *Networkd) dir() string {
	if n.Dir == "" {
		return NetworkdDir
	}
	return n.Dir
}

func (n *Networkd) prefix() string {
	if n.Prefix == "" {
		return NetworkdPrefix
	}
	return n.Prefix
}

func (n *Networkd) cmd() Commander {
	if n.Cmd == nil {
		return execCommander{}
	}
	return n.Cmd
}

// Name implements Backend.
func (n *Networkd) Name() string { return "systemd-networkd" }

func (n *Networkd) networkFile(iface string) string { return n.prefix() + iface + ".network" }
func (n *Networkd) netdevFile(iface string) string  { return n.prefix() + iface + ".netdev" }

// keyFile is where a WireGuard secret lives. Keys stay out of the .netdev
// so the unit itself can remain world-readable like the others.
func (n *Networkd) keyFile(iface, name string) string {
	return n.prefix() + iface + "-" + name + ".key"
}

// Render implements Backend.
func (n *Networkd) Render(cfg *model.Config) (Files, error) {
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	files := Files{}

	vlansByParent := map[string][]string{}
	for _, in := range cfg.Interfaces {
		switch in.Kind() {
		case model.KindVLAN:
			vlansByParent[in.VLAN.Parent] = append(vlansByParent[in.VLAN.Parent], in.Name)
			files[n.netdevFile(in.Name)] = renderNetdev(in)
		case model.KindWireGuard:
			files[n.netdevFile(in.Name)] = n.renderWireGuardNetdev(in, files)
		case model.KindBridge:
			files[n.netdevFile(in.Name)] = renderBridgeNetdev(in)
		case model.KindBond:
			files[n.netdevFile(in.Name)] = renderBondNetdev(in)
		}
	}

	routes, err := routesByInterface(cfg)
	if err != nil {
		return nil, err
	}
	masters := cfg.MasterOf()
	dialled := cfg.PPPoEParents()

	for _, in := range cfg.Interfaces {
		switch in.Kind() {
		case model.KindPPPoE, model.KindTailscale:
			// pppd and tailscaled create the interface and put the address
			// on it, so networkd is told to keep its hands off rather than
			// given a unit that would strip what the daemon just configured.
			continue
		}
		// A link that carries a bridge, a bond, or a dialled session is a
		// port: it comes up, and nothing else.
		attach := enslavement(cfg, masters[in.Name])
		port := attach != "" || dialled[in.Name] != ""
		files[n.networkFile(in.Name)] = renderNetwork(in, vlansByParent[in.Name], routes[in.Name],
			gatewaysFor(cfg, in.Name), port, attach)
	}
	// A VLAN parent that is not itself configured still needs a unit so
	// networkd brings the trunk up and attaches the VLANs.
	for parent, vlans := range vlansByParent {
		if _, ok := cfg.Interface(parent); !ok {
			files[n.networkFile(parent)] = renderTrunk(parent, vlans)
		}
	}
	// Same for a bridge or bond member that is not configured in its own
	// right, which is the usual case: it is a port, not an interface.
	for member, master := range masters {
		if _, ok := cfg.Interface(member); ok {
			continue
		}
		files[n.networkFile(member)] = renderPort(member, "Port on "+master, enslavement(cfg, master))
	}
	// The link under a dialled session needs a unit only so networkd
	// brings it up; pppd does the rest over it.
	for parent, session := range dialled {
		if _, ok := cfg.Interface(parent); ok {
			continue
		}
		files[n.networkFile(parent)] = renderPort(parent, "Carries the PPPoE session "+session, "")
	}
	// A radio's own interface carries nothing. It stays up because a card
	// that forgets its country when the firmware restarts only learns it
	// again by scanning on a live interface (ADR-0015).
	for _, r := range cfg.ActiveRadios() {
		files[n.networkFile(r.Name)] = renderPort(r.Name, "Radio; its networks are interfaces of their own", "")
	}
	return files, nil
}

// enslavement is the [Network] line that attaches a port to its master,
// empty when the interface stands alone.
func enslavement(cfg *model.Config, master string) string {
	if master == "" {
		return ""
	}
	in, ok := cfg.Interface(master)
	if !ok {
		return ""
	}
	switch in.Kind() {
	case model.KindBridge:
		return "Bridge=" + master
	case model.KindBond:
		return "Bond=" + master
	}
	return ""
}

func renderBridgeNetdev(in model.Interface) string {
	var b strings.Builder
	b.WriteString(fileHeader)
	fmt.Fprintf(&b, "[NetDev]\nName=%s\nKind=bridge\n", in.Name)
	if in.Description != "" {
		fmt.Fprintf(&b, "Description=%s\n", sanitizeValue(in.Description))
	}
	if in.MTU != 0 {
		fmt.Fprintf(&b, "MTUBytes=%d\n", in.MTU)
	}
	b.WriteString("\n[Bridge]\n")
	fmt.Fprintf(&b, "STP=%s\n", yesNo(in.Bridge.STP))
	fmt.Fprintf(&b, "VLANFiltering=%s\n", yesNo(in.Bridge.VLANFiltering))
	return b.String()
}

func renderBondNetdev(in model.Interface) string {
	bond := in.Bond
	var b strings.Builder
	b.WriteString(fileHeader)
	fmt.Fprintf(&b, "[NetDev]\nName=%s\nKind=bond\n", in.Name)
	if in.Description != "" {
		fmt.Fprintf(&b, "Description=%s\n", sanitizeValue(in.Description))
	}
	if in.MTU != 0 {
		fmt.Fprintf(&b, "MTUBytes=%d\n", in.MTU)
	}
	fmt.Fprintf(&b, "\n[Bond]\nMode=%s\n", bond.Mode)
	if bond.TransmitHashPolicy != "" {
		fmt.Fprintf(&b, "TransmitHashPolicy=%s\n", bond.TransmitHashPolicy)
	}
	if bond.MIIMonitorMS > 0 {
		fmt.Fprintf(&b, "MIIMonitorSec=%dms\n", bond.MIIMonitorMS)
	}
	if bond.Primary != "" && bond.Mode == model.BondActiveBackup {
		// networkd sets the primary on the member, not the bond; naming it
		// here as a comment keeps the unit self-explanatory.
		fmt.Fprintf(&b, "# primary member: %s\n", bond.Primary)
	}
	if bond.LACPRate != "" && bond.Mode == model.BondLACP {
		fmt.Fprintf(&b, "LACPTransmitRate=%s\n", bond.LACPRate)
	}
	return b.String()
}

// renderPort is the unit for a link that carries someone else's traffic:
// a bridge or bond port, or the Ethernet under a dialled session. It gets
// no addressing of its own, only whatever attaches it to its owner.
func renderPort(name, description, attach string) string {
	var b strings.Builder
	b.WriteString(fileHeader)
	fmt.Fprintf(&b, "[Match]\nName=%s\n\n[Network]\nDescription=%s (managed by ostiole)\n",
		name, sanitizeValue(description))
	b.WriteString("LinkLocalAddressing=no\n")
	if attach != "" {
		b.WriteString(attach + "\n")
	}
	return b.String()
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func renderNetdev(in model.Interface) string {
	var b strings.Builder
	b.WriteString(fileHeader)
	fmt.Fprintf(&b, "[NetDev]\nName=%s\nKind=vlan\n", in.Name)
	if in.MTU != 0 {
		fmt.Fprintf(&b, "MTUBytes=%d\n", in.MTU)
	}
	fmt.Fprintf(&b, "\n[VLAN]\nId=%d\n", in.VLAN.ID)
	return b.String()
}

// renderWireGuardNetdev writes the tunnel unit and, as a side effect, the
// key files it points at.
func (n *Networkd) renderWireGuardNetdev(in model.Interface, files Files) string {
	w := in.WireGuard
	var b strings.Builder
	b.WriteString(fileHeader)
	fmt.Fprintf(&b, "[NetDev]\nName=%s\nKind=wireguard\n", in.Name)
	if in.Description != "" {
		fmt.Fprintf(&b, "Description=%s\n", sanitizeValue(in.Description))
	}
	if in.MTU != 0 {
		fmt.Fprintf(&b, "MTUBytes=%d\n", in.MTU)
	}
	privName := n.keyFile(in.Name, "private")
	files[privName] = w.PrivateKey + "\n"
	fmt.Fprintf(&b, "\n[WireGuard]\nPrivateKeyFile=%s\n", filepath.Join(n.dir(), privName))
	if w.ListenPort != 0 {
		fmt.Fprintf(&b, "ListenPort=%d\n", w.ListenPort)
	}
	for _, p := range w.Peers {
		if !p.Enabled {
			continue
		}
		fmt.Fprintf(&b, "\n[WireGuardPeer]\n# %s\n", sanitizeValue(p.Name))
		fmt.Fprintf(&b, "PublicKey=%s\n", p.PublicKey)
		if p.PresharedKey != "" {
			psk := n.keyFile(in.Name, "peer-"+sanitizeValue(p.Name)+"-psk")
			files[psk] = p.PresharedKey + "\n"
			fmt.Fprintf(&b, "PresharedKeyFile=%s\n", filepath.Join(n.dir(), psk))
		}
		if len(p.AllowedIPs) > 0 {
			fmt.Fprintf(&b, "AllowedIPs=%s\n", strings.Join(p.AllowedIPs, " "))
		}
		if p.Endpoint != "" {
			fmt.Fprintf(&b, "Endpoint=%s\n", sanitizeValue(p.Endpoint))
		}
		if p.Keepalive > 0 {
			fmt.Fprintf(&b, "PersistentKeepalive=%d\n", p.Keepalive)
		}
	}
	return b.String()
}

func renderTrunk(name string, vlans []string) string {
	var b strings.Builder
	b.WriteString(fileHeader)
	fmt.Fprintf(&b, "[Match]\nName=%s\n\n[Network]\nDescription=VLAN trunk (managed by ostiole)\nLinkLocalAddressing=no\n", name)
	sort.Strings(vlans)
	for _, v := range vlans {
		fmt.Fprintf(&b, "VLAN=%s\n", v)
	}
	return b.String()
}

// gatewaysFor lists the enabled gateways that live on an interface.
func gatewaysFor(cfg *model.Config, iface string) []model.Gateway {
	var out []model.Gateway
	for _, g := range cfg.Gateways {
		if g.Enabled && g.Interface == iface {
			out = append(out, g)
		}
	}
	return out
}

func renderNetwork(in model.Interface, vlans []string, routes []model.StaticRoute, gateways []model.Gateway, port bool, attach string) string {
	var b strings.Builder
	b.WriteString(fileHeader)
	fmt.Fprintf(&b, "[Match]\nName=%s\n", in.Name)

	link := []string{}
	if !in.Enabled {
		link = append(link, "ActivationPolicy=down")
	}
	// The .netdev of a virtual interface sets its MTU at creation; setting
	// it here too is what makes a later change take effect, because
	// networkd reconfigures a link without recreating the device.
	if in.MTU != 0 {
		link = append(link, fmt.Sprintf("MTUBytes=%d", in.MTU))
	}
	// Only a physical interface reaches this with an address set, which
	// validation is what enforces.
	if in.MACAddress != "" {
		link = append(link, "MACAddress="+in.MACAddress)
	}
	if len(link) > 0 {
		b.WriteString("\n[Link]\n" + strings.Join(link, "\n") + "\n")
	}

	b.WriteString("\n[Network]\n")
	if in.Description != "" {
		fmt.Fprintf(&b, "Description=%s\n", sanitizeValue(in.Description))
	}
	if !in.Enabled {
		b.WriteString("LinkLocalAddressing=no\n")
		return b.String()
	}
	if port {
		// A port carries nothing of its own; whatever sits on top does.
		b.WriteString("LinkLocalAddressing=no\n")
		if attach != "" {
			b.WriteString(attach + "\n")
		}
		return b.String()
	}
	if in.Kind() == model.KindBridge || in.Kind() == model.KindBond {
		// A bridge with every port unplugged, or a bond waiting for its
		// switch, should still come up with its address.
		b.WriteString("ConfigureWithoutCarrier=yes\n")
	}

	dhcp4 := in.IPv4.Mode == model.AddrDHCP
	dhcp6 := in.IPv6.Mode == model.AddrDHCP
	switch {
	case dhcp4 && dhcp6:
		b.WriteString("DHCP=yes\n")
	case dhcp4:
		b.WriteString("DHCP=ipv4\n")
	case dhcp6:
		b.WriteString("DHCP=ipv6\n")
	default:
		b.WriteString("DHCP=no\n")
	}
	// A router announces nothing about itself on any segment. These are
	// name and topology protocols; the router's names come from its own
	// DNS service and its topology is not the neighbours' business.
	b.WriteString("LLMNR=no\nMulticastDNS=no\nLLDP=no\nEmitLLDP=no\n")
	if in.IPv6.Mode == model.AddrSLAAC || in.IPv6.Mode == model.AddrDHCP {
		b.WriteString("IPv6AcceptRA=yes\n")
		if in.IPv6.TemporaryAddresses {
			// RFC 4941: a second, short-lived address that outgoing
			// traffic prefers, so the stable one is not what the far end
			// sees every day.
			b.WriteString("IPv6PrivacyExtensions=yes\n")
		}
	} else {
		// An interface handing out addresses is the router on its segment,
		// so it listens to nobody else's advertisements.
		b.WriteString("IPv6AcceptRA=no\n")
	}
	if in.IPv6.Mode == model.AddrNone {
		// None means none. Left to itself, networkd keeps the kernel's
		// link-local address, and the interface stays on IPv6 in a way
		// nothing in the configuration admits to.
		b.WriteString("LinkLocalAddressing=no\n")
	}
	if in.IPv6.Mode == model.AddrDelegated {
		b.WriteString("DHCPPrefixDelegation=yes\n")
	}
	if in.DynamicAddressing() {
		// A stop drops leased addresses, and a revert over SSH on a DHCP
		// WAN lost its own session. Static addresses survive a stop
		// anyway. The routes left behind are swept in install.NetworkRevert.
		//
		// dhcp-on-stop: systemd 257 renamed it dynamic-on-stop and still
		// takes the old name; systemd 252 (RHEL 9) warns on the new one
		// and ignores it. On 252 only the DHCPv4 lease is kept. `yes`
		// would also ignore lease expiry.
		b.WriteString("KeepConfiguration=dhcp-on-stop\n")
	}
	if in.IPv4.Mode == model.AddrStatic {
		fmt.Fprintf(&b, "Address=%s\n", in.IPv4.Address)
	}
	if in.IPv6.Mode == model.AddrStatic {
		fmt.Fprintf(&b, "Address=%s\n", in.IPv6.Address)
	}
	// A gateway entry owns the default route and gives it a metric, so
	// failover has something to compare. Without one, the interface's own
	// gateway is used, and the kernel's default metric is fine.
	if !hasGateway(gateways, 4) && in.IPv4.Gateway != "" {
		fmt.Fprintf(&b, "Gateway=%s\n", in.IPv4.Gateway)
	}
	if !hasGateway(gateways, 6) && in.IPv6.Gateway != "" {
		fmt.Fprintf(&b, "Gateway=%s\n", in.IPv6.Gateway)
	}
	// Every plain key belongs to [Network], so the VLANs have to be written
	// before the first sub-section opens.
	sort.Strings(vlans)
	for _, v := range vlans {
		fmt.Fprintf(&b, "VLAN=%s\n", v)
	}
	b.WriteString(delegationSections(in, gateways))
	for _, g := range gateways {
		if g.Address == "" {
			continue
		}
		dst := "0.0.0.0/0"
		if a, err := model.ParseIP(g.Address); err == nil && !a.Is4() {
			dst = "::/0"
		}
		fmt.Fprintf(&b, "\n[Route]\nDestination=%s\nGateway=%s\nMetric=%d\n", dst, g.Address, g.GatewayMetric())
	}
	for _, dst := range wireGuardRoutes(in) {
		// On-link through the tunnel: WireGuard picks the peer by its
		// allowed addresses, so no gateway is involved.
		fmt.Fprintf(&b, "\n[Route]\nDestination=%s\nScope=link\n", dst)
	}
	for _, r := range routes {
		fmt.Fprintf(&b, "\n[Route]\nDestination=%s\nGateway=%s\n", r.Destination, r.Gateway)
	}
	return b.String()
}

// delegationSections writes the DHCP and router-advertisement blocks: the
// route metrics a gateway needs, the prefix an upstream should ask for,
// which piece of it an inside interface takes, and what the router tells
// the provider about itself, which is as little as the protocols allow.
func delegationSections(in model.Interface, gateways []model.Gateway) string {
	var dhcp4, dhcp6, ra []string
	if in.IPv4.Mode == model.AddrDHCP {
		// A DHCP request carries a name only when it is asked for, and
		// the client identifies by its hardware address rather than by a
		// DUID that outlives it. UseHostname=no keeps the provider from
		// renaming the router.
		dhcp4 = append(dhcp4,
			"SendHostname="+yesNo(in.IPv4.SendHostname),
			"ClientIdentifier=mac",
			"UseHostname=no")
	}
	if (in.IPv6.Mode == model.AddrDHCP || in.IPv6.Mode == model.AddrSLAAC) && hasHardwareAddress(in) {
		// A link-layer DUID is derived from the hardware address, so
		// overriding that address changes every identifier the provider
		// sees. SLAAC is included because networkd starts a DHCPv6 client
		// whenever the router advertisement asks for one, and that client
		// sends a DUID too. PPPoE has no hardware address of its own, so
		// networkd's default stands there.
		dhcp6 = append(dhcp6, "DUIDType=link-layer")
	}
	if in.IPv6.Mode == model.AddrSLAAC || in.IPv6.Mode == model.AddrDHCP {
		// RFC 7217: the host part is derived from the prefix and a secret
		// rather than from the hardware address, so the card's serial
		// number is no longer inside the router's global address.
		ra = append(ra, "Token=prefixstable")
	}
	for _, g := range gateways {
		if g.Address != "" {
			continue
		}
		// The address comes from the network, so the metric has to be set
		// where that route is created.
		metric := fmt.Sprintf("RouteMetric=%d", g.GatewayMetric())
		if in.IPv4.Mode == model.AddrDHCP {
			dhcp4 = append(dhcp4, metric)
		}
		if in.IPv6.Mode == model.AddrDHCP {
			dhcp6 = append(dhcp6, metric)
		}
		if in.IPv6.Mode == model.AddrSLAAC {
			ra = append(ra, metric)
		}
	}
	if in.IPv6.PrefixHint != "" {
		dhcp6 = append(dhcp6,
			"PrefixDelegationHint="+in.IPv6.PrefixHint,
			// Plenty of ISPs never set the managed flag in their router
			// advertisements but still delegate on request, so ask anyway.
			"WithoutRA=solicit",
			"UseDelegatedPrefix=yes")
	}

	var b strings.Builder
	section := func(name string, lines []string) {
		if len(lines) == 0 {
			return
		}
		fmt.Fprintf(&b, "\n[%s]\n%s\n", name, strings.Join(lines, "\n"))
	}
	section("DHCPv4", dhcp4)
	section("DHCPv6", dhcp6)
	section("IPv6AcceptRA", ra)
	if in.IPv6.Mode == model.AddrDelegated {
		// Ostiole advertises the prefix through dnsmasq, which follows
		// whatever address ends up on the interface, so networkd must not
		// also send router advertisements for it.
		fmt.Fprintf(&b, "\n[DHCPPrefixDelegation]\nUplinkInterface=%s\nSubnetId=0x%x\nAnnounce=no\n",
			in.IPv6.DelegatedFrom, in.IPv6.SubnetID)
	}
	return b.String()
}

// hasHardwareAddress reports whether this kind of interface has a MAC a
// DUID can be derived from.
func hasHardwareAddress(in model.Interface) bool {
	switch in.Kind() {
	case model.KindPhysical, model.KindVLAN, model.KindBridge, model.KindBond, model.KindWireless:
		return true
	}
	return false
}

// wireGuardRoutes lists the peer networks that the interface's own
// addresses do not already cover. Default routes are left out: sending
// everything down a tunnel is a deliberate act, not a side effect of
// adding a peer.
func wireGuardRoutes(in model.Interface) []string {
	if in.WireGuard == nil {
		return nil
	}
	var own []netip.Prefix
	for _, addr := range []string{in.IPv4.Address, in.IPv6.Address} {
		if p, err := netip.ParsePrefix(addr); err == nil {
			own = append(own, p.Masked())
		}
	}
	var out []string
	seen := map[string]bool{}
	for _, p := range in.WireGuard.Peers {
		if !p.Enabled {
			continue
		}
		for _, a := range p.AllowedIPs {
			pre, err := netip.ParsePrefix(a)
			if err != nil {
				if addr, aerr := netip.ParseAddr(a); aerr == nil {
					pre = netip.PrefixFrom(addr, addr.BitLen())
				} else {
					continue
				}
			}
			pre = pre.Masked()
			if pre.Bits() == 0 || seen[pre.String()] {
				continue
			}
			covered := false
			for _, o := range own {
				if o.Overlaps(pre) && o.Bits() <= pre.Bits() {
					covered = true
					break
				}
			}
			if covered {
				continue
			}
			seen[pre.String()] = true
			out = append(out, pre.String())
		}
	}
	sort.Strings(out)
	return out
}

// routesByInterface assigns each enabled static route to an interface:
// the one named on the route, else the one whose static address covers
// the gateway.
// hasGateway reports whether a gateway of the given family is configured
// on the interface. A gateway without an address follows whatever the
// network hands out, which covers both families.
func hasGateway(gateways []model.Gateway, family int) bool {
	for _, g := range gateways {
		if g.Address == "" {
			return true
		}
		if a, err := model.ParseIP(g.Address); err == nil && (a.Is4() == (family == 4)) {
			return true
		}
	}
	return false
}

// dynamicAddressing reports whether the interface has a leased, advertised
// or delegated address: the ones networkd drops when it stops.
func routesByInterface(cfg *model.Config) (map[string][]model.StaticRoute, error) {
	out := map[string][]model.StaticRoute{}
	for _, r := range cfg.Routes {
		if !r.Enabled {
			continue
		}
		iface := r.Interface
		if iface == "" {
			gw, _ := model.ParseIP(r.Gateway)
			iface = interfaceForGateway(cfg, gw)
			if iface == "" {
				return nil, fmt.Errorf("route %s: gateway %s is not on any static interface network; set interface explicitly", r.ID, r.Gateway)
			}
		}
		out[iface] = append(out[iface], r)
	}
	return out, nil
}

func interfaceForGateway(cfg *model.Config, gw netip.Addr) string {
	for _, in := range cfg.Interfaces {
		if !in.Enabled {
			continue
		}
		for _, a := range []string{in.IPv4.Address, in.IPv6.Address} {
			if a == "" {
				continue
			}
			p, err := netip.ParsePrefix(a)
			if err == nil && p.Masked().Contains(gw) {
				return in.Name
			}
		}
	}
	return ""
}

func sanitizeValue(s string) string {
	return strings.NewReplacer("\n", " ", "\r", " ").Replace(s)
}

// Snapshot implements Backend.
func (n *Networkd) Snapshot() (Files, error) {
	files := Files{}
	entries, err := os.ReadDir(n.dir())
	if errors.Is(err, os.ErrNotExist) {
		return files, nil
	}
	if err != nil {
		return nil, err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasPrefix(e.Name(), n.prefix()) {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(n.dir(), e.Name()))
		if err != nil {
			return nil, err
		}
		files[e.Name()] = string(raw)
	}
	return files, nil
}

// Apply implements Backend: write the files, delete stale owned files,
// then reload networkd, reconfigure the affected links, and take down the
// devices that are no longer configured.
func (n *Networkd) Apply(ctx context.Context, files Files) error {
	gone, err := n.staleDevices(files)
	if err != nil {
		return err
	}
	changed, err := n.Write(files)
	if err != nil {
		return err
	}
	if !changed {
		return nil
	}
	// A .network for a device that is not there yet is left to networkd,
	// which configures a link the moment it appears: hostapd and pppd
	// create theirs after this, and networkctl refuses to reconfigure a
	// name it cannot resolve.
	var links []string
	for _, name := range n.linkNames(files) {
		if n.linkExists(name) {
			links = append(links, name)
		}
	}
	if err := n.Reload(ctx, links); err != nil {
		return err
	}
	// networkd creates the device a .netdev describes but never removes it
	// again: delete the unit and the tunnel or VLAN keeps running, keeps its
	// addresses, and comes back after a reboot as an interface nobody
	// configured. Only devices Ostiole made are touched here, which is
	// exactly what a vanished ostiole-owned .netdev proves — a physical NIC
	// never has one.
	for _, name := range gone {
		if err := n.delLink(name); err != nil {
			return fmt.Errorf("delete link %s: %w", name, err)
		}
	}
	return nil
}

// staleDevices names the virtual devices whose .netdev is about to go away.
func (n *Networkd) staleDevices(files Files) ([]string, error) {
	current, err := n.Snapshot()
	if err != nil {
		return nil, err
	}
	var gone []string
	for name := range current {
		if _, keep := files[name]; keep || !strings.HasSuffix(name, ".netdev") {
			continue
		}
		gone = append(gone, strings.TrimSuffix(strings.TrimPrefix(name, n.prefix()), ".netdev"))
	}
	sort.Strings(gone)
	return gone, nil
}

func (n *Networkd) linkExists(name string) bool {
	if n.LinkExists != nil {
		return n.LinkExists(name)
	}
	_, err := netlink.LinkByName(name)
	return err == nil
}

func (n *Networkd) delLink(name string) error {
	if n.DelLink != nil {
		return n.DelLink(name)
	}
	link, err := netlink.LinkByName(name)
	if err != nil {
		var missing netlink.LinkNotFoundError
		if errors.As(err, &missing) {
			return nil
		}
		return err
	}
	return netlink.LinkDel(link)
}

// Write installs exactly the given files, removing stale owned ones, and
// reports whether anything changed. It does not talk to networkd, so it
// is safe before networkd runs (the takeover uses it).
func (n *Networkd) Write(files Files) (bool, error) {
	// networkd runs as its own unprivileged user and must read these units.
	if err := os.MkdirAll(n.dir(), 0o755); err != nil { //nolint:gosec // see above
		return false, err
	}
	current, err := n.Snapshot()
	if err != nil {
		return false, err
	}
	changed := false
	for name, content := range files {
		if !strings.HasPrefix(name, n.prefix()) || strings.ContainsAny(name, "/\\") {
			return false, fmt.Errorf("refusing to write %q: not an ostiole-owned unit name", name)
		}
		if current[name] == content {
			continue
		}
		if err := writeFile(filepath.Join(n.dir(), name), content); err != nil {
			return false, err
		}
		changed = true
	}
	for name := range current {
		if _, keep := files[name]; keep {
			continue
		}
		if err := os.Remove(filepath.Join(n.dir(), name)); err != nil && !errors.Is(err, os.ErrNotExist) {
			return false, err
		}
		changed = true
	}
	return changed, nil
}

// Reload tells networkd to re-read units and reconfigure links.
func (n *Networkd) Reload(ctx context.Context, links []string) error {
	if out, err := n.cmd().Run(ctx, "networkctl", "reload"); err != nil {
		return fmt.Errorf("networkctl reload: %w: %s", err, bytes.TrimSpace(out))
	}
	if len(links) == 0 {
		return nil
	}
	if out, err := n.cmd().Run(ctx, "networkctl", append([]string{"reconfigure"}, links...)...); err != nil {
		return fmt.Errorf("networkctl reconfigure: %w: %s", err, bytes.TrimSpace(out))
	}
	return nil
}

// Renew implements Renewer. A renew asks the server to extend the lease
// the link holds; a release reconfigures the link, which drops the lease
// and starts over from discovery.
func (n *Networkd) Renew(ctx context.Context, link string, release bool) error {
	verb := "renew"
	if release {
		verb = "reconfigure"
	}
	if out, err := n.cmd().Run(ctx, "networkctl", verb, link); err != nil {
		return fmt.Errorf("networkctl %s %s: %w: %s", verb, link, err, bytes.TrimSpace(out))
	}
	return nil
}

// LinkNames lists interfaces that have a .network unit in files.
func (n *Networkd) LinkNames(files Files) []string { return n.linkNames(files) }

// linkNames lists interfaces that have a .network unit in files.
func (n *Networkd) linkNames(files Files) []string {
	var names []string
	for name := range files {
		if strings.HasSuffix(name, ".network") {
			names = append(names, strings.TrimSuffix(strings.TrimPrefix(name, n.prefix()), ".network"))
		}
	}
	sort.Strings(names)
	return names
}

// networkdUser is who systemd-networkd drops to; key files are readable
// by that group and nobody else.
const networkdUser = "systemd-network"

func writeFile(path, content string) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".*.tmp")
	if err != nil {
		return err
	}
	name := tmp.Name()
	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()
		_ = os.Remove(name)
		return err
	}
	mode := os.FileMode(0o644)
	if strings.HasSuffix(path, ".key") {
		mode = 0o640
		if gid, err := networkdGID(); err == nil {
			// Ignore failures: without the group the file stays root-only,
			// which networkd reports clearly if it cannot read it.
			_ = tmp.Chown(0, gid)
		}
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		_ = os.Remove(name)
		return err
	}
	// A crash soon after an apply must not boot networkd on an empty unit.
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		_ = os.Remove(name)
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(name)
		return err
	}
	if err := os.Rename(name, path); err != nil {
		_ = os.Remove(name)
		return err
	}
	syncDir(filepath.Dir(path))
	return nil
}

// syncDir makes the renames in dir durable. Best effort, as in the store.
func syncDir(dir string) {
	if d, err := os.Open(dir); err == nil {
		_ = d.Sync()
		_ = d.Close()
	}
}

func networkdGID() (int, error) {
	g, err := user.LookupGroup(networkdUser)
	if err != nil {
		return 0, err
	}
	return strconv.Atoi(g.Gid)
}

type execCommander struct{}

func (execCommander) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	return exec.CommandContext(ctx, name, args...).CombinedOutput()
}
