// Package services runs LAN services (DHCP and DNS) through dnsmasq: it
// renders the configuration, manages the ostiole-dnsmasq unit, and reads
// leases.
package services

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"syscall"

	"github.com/rforced/ostiole/internal/model"
	"github.com/rforced/ostiole/internal/network"
	"github.com/rforced/ostiole/internal/nft"
)

// Paths and names.
const (
	Unit = "ostiole-dnsmasq.service"
	// DefaultDir and LeaseFile are the places the distro's SELinux policy
	// lets dnsmasq read and write (dnsmasq_etc_t, dnsmasq_lease_t), and
	// they are world-readable because dnsmasq drops privileges before it
	// reads the hosts file. /etc/ostiole is private and unlabeled for it.
	DefaultDir   = "/etc/dnsmasq.d"
	LeaseFile    = "/var/lib/dnsmasq/ostiole.leases"
	ResolvConf   = "/etc/resolv.conf"
	confName     = "ostiole.conf"
	hostsName    = "ostiole.hosts"
	enabledName  = "ostiole.enabled"
	resolvName   = "resolv.conf"
	fileHeader   = "# Generated by ostiole. Do not edit; changes are overwritten on apply.\n"
	distroUnit   = "dnsmasq.service"
	resolvedUnit = "systemd-resolved.service"
)

// Dnsmasq is the services backend. It implements network.Backend so the
// engine can snapshot, apply, and revert it like the network units.
type Dnsmasq struct {
	// Dir holds the generated files; default DefaultDir.
	Dir string
	// Leases is the lease file dnsmasq writes; default LeaseFile.
	Leases string
	// Resolv is the resolver file written when DNS is on; default
	// /etc/resolv.conf. Empty string in tests disables it.
	Resolv string
	// Cmd runs systemctl; default execs it.
	Cmd network.Commander
}

// New returns a backend with production defaults.
func New() *Dnsmasq {
	return &Dnsmasq{Dir: DefaultDir, Leases: LeaseFile, Resolv: ResolvConf, Cmd: execCommander{}}
}

func (d *Dnsmasq) dir() string {
	if d.Dir == "" {
		return DefaultDir
	}
	return d.Dir
}

func (d *Dnsmasq) leases() string {
	if d.Leases == "" {
		return LeaseFile
	}
	return d.Leases
}

func (d *Dnsmasq) cmd() network.Commander {
	if d.Cmd == nil {
		return execCommander{}
	}
	return d.Cmd
}

// Name implements network.Backend.
func (d *Dnsmasq) Name() string { return "dnsmasq" }

// Enabled reports whether either service is on.
func Enabled(cfg *model.Config) bool {
	return cfg.Services.DHCP.Enabled || cfg.Services.DNS.Enabled
}

// Render implements network.Backend. When both services are off it returns
// no files, which Apply turns into "unit stopped".
func (d *Dnsmasq) Render(cfg *model.Config) (network.Files, error) {
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	files := network.Files{}
	if !Enabled(cfg) {
		if d.Resolv != "" && len(cfg.System.DNSServers) > 0 {
			files[resolvName] = renderResolv(cfg.System.DNSServers, "")
		}
		return files, nil
	}
	conf, hosts, err := d.render(cfg)
	if err != nil {
		return nil, err
	}
	files[confName] = conf
	files[hostsName] = hosts
	files[enabledName] = "1\n"
	if d.Resolv != "" {
		if cfg.Services.DNS.Enabled {
			files[resolvName] = renderResolv([]string{"127.0.0.1"}, cfg.Services.DNS.Domain)
		} else if len(cfg.System.DNSServers) > 0 {
			files[resolvName] = renderResolv(cfg.System.DNSServers, "")
		}
	}
	return files, nil
}

func renderResolv(servers []string, domain string) string {
	var b strings.Builder
	b.WriteString("# Generated by ostiole.\n")
	for _, s := range servers {
		fmt.Fprintf(&b, "nameserver %s\n", s)
	}
	if domain != "" {
		fmt.Fprintf(&b, "search %s\n", domain)
	}
	return b.String()
}

func (d *Dnsmasq) render(cfg *model.Config) (conf, hosts string, err error) {
	svc := cfg.Services
	var b strings.Builder
	b.WriteString(fileHeader)
	b.WriteString("no-resolv\nno-hosts\nno-poll\nbind-dynamic\n")
	fmt.Fprintf(&b, "addn-hosts=%s\n", filepath.Join(d.dir(), hostsName))
	fmt.Fprintf(&b, "dhcp-leasefile=%s\n", d.leases())

	// bind-dynamic serves only the listed interfaces, so every interface
	// that needs DNS, DHCP, or router advertisements has to appear here.
	for _, name := range listenInterfaces(cfg) {
		fmt.Fprintf(&b, "interface=%s\n", name)
	}

	// ---- DNS ----
	if svc.DNS.Enabled {
		b.WriteString("domain-needed\nbogus-priv\nlocalise-queries\n")
		b.WriteString("listen-address=127.0.0.1\n")
		if ResolverEnabled(cfg) {
			// unbound does the resolving and the DNSSEC validation;
			// proxy-dnssec passes its verdict on to clients.
			fmt.Fprintf(&b, "server=%s#%d\n", UnboundAddress, UnboundPort)
			b.WriteString("proxy-dnssec\n")
		} else {
			upstreams := svc.DNS.Upstreams
			if len(upstreams) == 0 {
				upstreams = cfg.System.DNSServers
			}
			for _, u := range upstreams {
				fmt.Fprintf(&b, "server=%s\n", u)
			}
		}
		// Domain overrides beat the servers above whatever the order,
		// because dnsmasq answers from the longest matching domain. That
		// holds with unbound behind us as well: a delegated domain goes
		// straight to its own resolver instead of through a recursor that
		// would never find it, which is the whole point of the override.
		delegated := append([]model.DomainOverride(nil), svc.DNS.DomainOverrides...)
		sort.Slice(delegated, func(i, j int) bool { return delegated[i].Domain < delegated[j].Domain })
		for _, d := range delegated {
			for _, s := range d.Servers {
				fmt.Fprintf(&b, "server=/%s/%s\n", model.NormalizeDomain(d.Domain), strings.TrimSpace(s))
			}
		}
		if svc.DNS.Domain != "" {
			fmt.Fprintf(&b, "domain=%s\nlocal=/%s/\nexpand-hosts\n", svc.DNS.Domain, svc.DNS.Domain)
		}
		// The blocklist lives in its own file, written from the cache
		// rather than from the model. The include is named whenever DNS is
		// answering, empty or not, so turning blocking on and off does not
		// rewrite this file and cost a second restart.
		fmt.Fprintf(&b, "conf-file=%s\n", filepath.Join(d.dir(), BlockConfName))
	} else {
		b.WriteString("port=0\n")
	}

	// ---- DHCP ----
	if svc.DHCP.Enabled {
		b.WriteString("dhcp-authoritative\n")
		for _, sc := range svc.DHCP.Scopes {
			if !sc.Enabled {
				continue
			}
			in, _ := cfg.Interface(sc.Interface)
			prefix, perr := netip.ParsePrefix(in.IPv4.Address)
			if perr != nil {
				return "", "", fmt.Errorf("scope %s: %w", sc.Interface, perr)
			}
			maskStr := net.IP(net.CIDRMask(prefix.Bits(), 32)).String()
			lease := sc.LeaseTime
			if lease == "" {
				lease = "12h"
			}
			tag := "s_" + sanitizeTag(sc.Interface)
			fmt.Fprintf(&b, "dhcp-range=set:%s,%s,%s,%s,%s\n", tag, sc.RangeStart, sc.RangeEnd, maskStr, lease)
			gw := sc.Gateway
			if gw == "" {
				gw = prefix.Addr().String()
			}
			fmt.Fprintf(&b, "dhcp-option=tag:%s,option:router,%s\n", tag, gw)
			dns := sc.DNS
			if len(dns) == 0 {
				switch {
				case svc.DNS.Enabled:
					dns = []string{prefix.Addr().String()}
				case len(cfg.System.DNSServers) > 0:
					dns = cfg.System.DNSServers
				default:
					dns = svc.DNS.Upstreams
				}
			}
			if len(dns) > 0 {
				fmt.Fprintf(&b, "dhcp-option=tag:%s,option:dns-server,%s\n", tag, strings.Join(dns, ","))
			}
			domain := sc.Domain
			if domain == "" {
				domain = svc.DNS.Domain
			}
			if domain != "" {
				fmt.Fprintf(&b, "dhcp-option=tag:%s,option:domain-name,%s\n", tag, domain)
			}
		}
		renderV6(&b, cfg)
		for _, l := range svc.DHCP.StaticLeases {
			parts := []string{strings.ToLower(l.MAC)}
			if l.IP != "" {
				parts = append(parts, l.IP)
			}
			if l.IPv6 != "" {
				parts = append(parts, "["+l.IPv6+"]")
			}
			if l.Hostname != "" {
				parts = append(parts, l.Hostname)
			}
			fmt.Fprintf(&b, "dhcp-host=%s\n", strings.Join(parts, ","))
		}
	}

	// ---- hosts ----
	var h strings.Builder
	h.WriteString(fileHeader)
	overrides := append([]model.HostOverride(nil), svc.DNS.HostOverrides...)
	sort.Slice(overrides, func(i, j int) bool { return overrides[i].Hostname < overrides[j].Hostname })
	for _, o := range overrides {
		fmt.Fprintf(&h, "%s %s\n", o.IP, o.Hostname)
	}
	// Static leases with hostnames resolve locally too. An IPv6 host part
	// like ::20 is only meaningful next to a prefix, so it is left out.
	for _, l := range svc.DHCP.StaticLeases {
		if l.Hostname == "" {
			continue
		}
		if l.IP != "" {
			fmt.Fprintf(&h, "%s %s\n", l.IP, l.Hostname)
		}
		if ip, err := netip.ParseAddr(l.IPv6); err == nil && !hostPartOnly(ip) {
			fmt.Fprintf(&h, "%s %s\n", ip, l.Hostname)
		}
	}
	return b.String(), h.String(), nil
}

// hostPartOnly reports an address written as a bare host part, like ::20,
// which dnsmasq combines with the interface's prefix.
func hostPartOnly(ip netip.Addr) bool {
	if !ip.Is6() || ip.Is4In6() {
		return false
	}
	b := ip.As16()
	for _, x := range b[:8] {
		if x != 0 {
			return false
		}
	}
	return true
}

// listenInterfaces is every interface dnsmasq must bind: the DNS
// interfaces plus any that hand out addresses or advertise IPv6.
func listenInterfaces(cfg *model.Config) []string {
	var out []string
	seen := map[string]bool{}
	add := func(name string) {
		if name != "" && !seen[name] {
			seen[name] = true
			out = append(out, name)
		}
	}
	if cfg.Services.DNS.Enabled {
		for _, name := range nft.DNSInterfaces(cfg) {
			add(name)
		}
	}
	if cfg.Services.DHCP.Enabled {
		for _, sc := range cfg.Services.DHCP.Scopes {
			if sc.Enabled {
				add(sc.Interface)
			}
		}
		for _, sc := range EnabledV6(cfg) {
			add(sc.Interface)
		}
	}
	return out
}

// EnabledV6 lists the IPv6 scopes that are on and whose interface is on.
func EnabledV6(cfg *model.Config) []model.DHCPv6Scope {
	var out []model.DHCPv6Scope
	if !cfg.Services.DHCP.Enabled {
		return nil
	}
	for _, sc := range cfg.Services.DHCP.V6 {
		if in, ok := cfg.Interface(sc.Interface); ok && sc.Enabled && in.Enabled {
			out = append(out, sc)
		}
	}
	return out
}

// renderV6 writes the router advertisement and DHCPv6 configuration. The
// prefix is never written out: constructor: tells dnsmasq to take it from
// the interface, so SLAAC or a delegated prefix keeps working.
func renderV6(b *strings.Builder, cfg *model.Config) {
	scopes := EnabledV6(cfg)
	if len(scopes) == 0 {
		return
	}
	svc := cfg.Services
	b.WriteString("enable-ra\n")
	for _, sc := range scopes {
		tag := "s6_" + sanitizeTag(sc.Interface)
		lease := sc.LeaseTime
		if lease == "" {
			lease = "12h"
		}
		switch sc.Mode {
		case model.RASLAAC:
			fmt.Fprintf(b, "dhcp-range=set:%s,::,constructor:%s,ra-only,64,%s\n", tag, sc.Interface, lease)
		case model.RAStateless:
			fmt.Fprintf(b, "dhcp-range=set:%s,::,constructor:%s,ra-stateless,ra-names,64,%s\n", tag, sc.Interface, lease)
		case model.RAManaged:
			fmt.Fprintf(b, "dhcp-range=set:%s,%s,%s,constructor:%s,ra-names,64,%s\n",
				tag, sc.RangeStart, sc.RangeEnd, sc.Interface, lease)
		}
		dns := sc.DNS
		if len(dns) == 0 && svc.DNS.Enabled {
			// dnsmasq puts a DNS server into the router advertisement only
			// when it is a literal address: its [::] shorthand for "this
			// box" reaches DHCPv6 replies but is dropped from the RDNSS
			// option, which is all a SLAAC-only client ever sees. Use the
			// interface's own address when the configuration names one.
			dns = []string{"::"}
			if in, ok := cfg.Interface(sc.Interface); ok && in.IPv6.Mode == model.AddrStatic {
				if p, err := netip.ParsePrefix(in.IPv6.Address); err == nil {
					dns = []string{p.Addr().String()}
				}
			}
		}
		if len(dns) > 0 {
			addrs := make([]string, 0, len(dns))
			for _, d := range dns {
				addrs = append(addrs, "["+d+"]")
			}
			fmt.Fprintf(b, "dhcp-option=tag:%s,option6:dns-server,%s\n", tag, strings.Join(addrs, ","))
		}
		domain := sc.Domain
		if domain == "" {
			domain = svc.DNS.Domain
		}
		if domain != "" {
			fmt.Fprintf(b, "dhcp-option=tag:%s,option6:domain-search,%s\n", tag, domain)
		}
	}
}

func sanitizeTag(s string) string {
	return strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' {
			return r
		}
		return '_'
	}, s)
}

// Snapshot implements network.Backend.
func (d *Dnsmasq) Snapshot() (network.Files, error) {
	files := network.Files{}
	for _, name := range []string{confName, hostsName, enabledName} {
		raw, err := os.ReadFile(filepath.Join(d.dir(), name))
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, err
		}
		files[name] = string(raw)
	}
	if d.Resolv != "" {
		if raw, err := os.ReadFile(d.Resolv); err == nil && strings.HasPrefix(string(raw), "# Generated by ostiole") {
			files[resolvName] = string(raw)
		}
	}
	return files, nil
}

// Apply implements network.Backend: write the files and start, restart,
// or stop the unit to match.
func (d *Dnsmasq) Apply(ctx context.Context, files network.Files) error {
	if err := os.MkdirAll(d.dir(), 0o755); err != nil { //nolint:gosec // dnsmasq reads these unprivileged
		return err
	}
	current, err := d.Snapshot()
	if err != nil {
		return err
	}
	changed := false
	for _, name := range []string{confName, hostsName, enabledName} {
		content, want := files[name]
		path := filepath.Join(d.dir(), name)
		switch {
		case want && current[name] != content:
			if err := writeFile(path, content); err != nil {
				return err
			}
			changed = true
		case !want && current[name] != "":
			if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
				return err
			}
			changed = true
		}
	}
	if d.Resolv != "" {
		if content, want := files[resolvName]; want && current[resolvName] != content {
			if err := writeFile(d.Resolv, content); err != nil {
				return err
			}
		}
	}
	enabled := files[enabledName] != ""
	if !enabled {
		if current[enabledName] != "" {
			if out, err := d.cmd().Run(ctx, "systemctl", "disable", "--now", Unit); err != nil {
				return fmt.Errorf("stop %s: %w: %s", Unit, err, bytes.TrimSpace(out))
			}
		}
		return nil
	}
	if !changed {
		return nil
	}
	if !d.Installed(ctx) {
		return errors.New("dnsmasq is not set up on this host; run `ostiole services setup`")
	}
	if err := os.MkdirAll(filepath.Dir(d.leases()), 0o755); err != nil { //nolint:gosec // dnsmasq writes here unprivileged
		return err
	}
	if out, err := d.cmd().Run(ctx, "systemctl", "enable", Unit); err != nil {
		return fmt.Errorf("enable %s: %w: %s", Unit, err, bytes.TrimSpace(out))
	}
	if out, err := d.cmd().Run(ctx, "systemctl", "restart", Unit); err != nil {
		return fmt.Errorf("restart %s: %w: %s", Unit, err, bytes.TrimSpace(out))
	}
	return nil
}

// Installed reports whether the ostiole-dnsmasq unit exists.
func (d *Dnsmasq) Installed(ctx context.Context) bool {
	_, err := d.cmd().Run(ctx, "systemctl", "cat", Unit)
	return err == nil
}

// Active reports whether the unit is running.
func (d *Dnsmasq) Active(ctx context.Context) bool {
	out, err := d.cmd().Run(ctx, "systemctl", "is-active", Unit)
	return err == nil && strings.TrimSpace(string(out)) == "active"
}

// writeFile replaces path, atomically where the filesystem allows it.
// Generated service files are world-readable: dnsmasq and unbound read them
// after dropping privileges.
func writeFile(path, content string) error { return writeMode(path, content, 0o644) }

// writeSecretFile does the same for a file nobody but root should read,
// like the provider password in a pppd peer file.
func writeSecretFile(path, content string) error { return writeMode(path, content, 0o600) }

func writeMode(path, content string, mode os.FileMode) error {
	err := writeAtomic(path, content, mode)
	if err == nil || !sealedDir(err) {
		return err
	}
	// The directory takes no new entries. That is how the daemon's own
	// sandbox looks from in here: ProtectSystem=strict leaves /etc
	// read-only and ReadWritePaths=/etc/resolv.conf mounts just that file
	// read-write, so the file can only be rewritten where it lies. Writing
	// through the file also keeps whatever SELinux label it already has,
	// which a fresh file in /etc would not inherit.
	if _, statErr := os.Stat(path); statErr != nil {
		return err
	}
	return writeInPlace(path, content, mode)
}

// writeAtomic writes a temporary file beside path and renames it over the
// top, so a reader sees either the whole old file or the whole new one.
func writeAtomic(path, content string, mode os.FileMode) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".*.tmp")
	if err != nil {
		return err
	}
	name := tmp.Name()
	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()
		_ = os.Remove(name)
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		_ = os.Remove(name)
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(name)
		return err
	}
	if err := os.Rename(name, path); err != nil {
		_ = os.Remove(name)
		return err
	}
	return nil
}

// writeInPlace rewrites an existing file through its own inode: the new
// content goes over the old bytes and the file is then cut to length. A
// resolver that reads the file mid-write sees the new nameservers, at worst
// with a stale line still hanging off the end, and never an empty file.
func writeInPlace(path, content string, mode os.FileMode) error {
	f, err := os.OpenFile(path, os.O_WRONLY, 0)
	if err != nil {
		return err
	}
	if _, err := f.WriteString(content); err != nil {
		_ = f.Close()
		return err
	}
	if err := f.Truncate(int64(len(content))); err != nil {
		_ = f.Close()
		return err
	}
	if info, err := f.Stat(); err == nil && info.Mode().Perm() != mode.Perm() {
		if err := f.Chmod(mode); err != nil {
			_ = f.Close()
			return err
		}
	}
	return f.Close()
}

// sealedDir reports whether the error says the directory holding the file
// refuses the entries an atomic replace needs: read-only or unwritable for
// the temporary file, busy for a rename over a mount point.
func sealedDir(err error) bool {
	return errors.Is(err, syscall.EROFS) || errors.Is(err, syscall.EBUSY) || errors.Is(err, os.ErrPermission)
}

type execCommander struct{}

func (execCommander) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	return exec.CommandContext(ctx, name, args...).CombinedOutput()
}
