// Package services runs LAN services (DHCP and DNS) through dnsmasq: it
// renders the configuration, manages the ostiole-dnsmasq unit, and reads
// leases.
package services

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/rforced/ostiole/internal/model"
	"github.com/rforced/ostiole/internal/network"
	"github.com/rforced/ostiole/internal/nft"
)

// Paths and names.
const (
	Unit = "ostiole-dnsmasq.service"
	// DefaultDir is world-readable on purpose: dnsmasq drops privileges
	// before reading the hosts file, so it cannot live under /etc/ostiole.
	DefaultDir   = "/var/lib/ostiole/dnsmasq"
	LeaseFile    = "/var/lib/ostiole/dnsmasq.leases"
	ResolvConf   = "/etc/resolv.conf"
	confName     = "dnsmasq.conf"
	hostsName    = "hosts"
	enabledName  = "dnsmasq.enabled"
	resolvName   = "resolv.conf"
	fileHeader   = "# Generated by ostiole. Do not edit; changes are overwritten on apply.\n"
	distroUnit   = "dnsmasq.service"
	resolvedUnit = "systemd-resolved.service"
)

// Dnsmasq is the services backend. It implements network.Backend so the
// engine can snapshot, apply, and revert it like the network units.
type Dnsmasq struct {
	// Dir holds the generated files; default DefaultDir.
	Dir string
	// Leases is the lease file dnsmasq writes; default LeaseFile.
	Leases string
	// Resolv is the resolver file written when DNS is on; default
	// /etc/resolv.conf. Empty string in tests disables it.
	Resolv string
	// Cmd runs systemctl; default execs it.
	Cmd network.Commander
}

// New returns a backend with production defaults.
func New() *Dnsmasq {
	return &Dnsmasq{Dir: DefaultDir, Leases: LeaseFile, Resolv: ResolvConf, Cmd: execCommander{}}
}

func (d *Dnsmasq) dir() string {
	if d.Dir == "" {
		return DefaultDir
	}
	return d.Dir
}

func (d *Dnsmasq) leases() string {
	if d.Leases == "" {
		return LeaseFile
	}
	return d.Leases
}

func (d *Dnsmasq) cmd() network.Commander {
	if d.Cmd == nil {
		return execCommander{}
	}
	return d.Cmd
}

// Name implements network.Backend.
func (d *Dnsmasq) Name() string { return "dnsmasq" }

// Enabled reports whether either service is on.
func Enabled(cfg *model.Config) bool {
	return cfg.Services.DHCP.Enabled || cfg.Services.DNS.Enabled
}

// Render implements network.Backend. When both services are off it returns
// no files, which Apply turns into "unit stopped".
func (d *Dnsmasq) Render(cfg *model.Config) (network.Files, error) {
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	files := network.Files{}
	if !Enabled(cfg) {
		if d.Resolv != "" && len(cfg.System.DNSServers) > 0 {
			files[resolvName] = renderResolv(cfg.System.DNSServers, "")
		}
		return files, nil
	}
	conf, hosts, err := d.render(cfg)
	if err != nil {
		return nil, err
	}
	files[confName] = conf
	files[hostsName] = hosts
	files[enabledName] = "1\n"
	if d.Resolv != "" {
		if cfg.Services.DNS.Enabled {
			files[resolvName] = renderResolv([]string{"127.0.0.1"}, cfg.Services.DNS.Domain)
		} else if len(cfg.System.DNSServers) > 0 {
			files[resolvName] = renderResolv(cfg.System.DNSServers, "")
		}
	}
	return files, nil
}

func renderResolv(servers []string, domain string) string {
	var b strings.Builder
	b.WriteString("# Generated by ostiole.\n")
	for _, s := range servers {
		fmt.Fprintf(&b, "nameserver %s\n", s)
	}
	if domain != "" {
		fmt.Fprintf(&b, "search %s\n", domain)
	}
	return b.String()
}

func (d *Dnsmasq) render(cfg *model.Config) (conf, hosts string, err error) {
	svc := cfg.Services
	var b strings.Builder
	b.WriteString(fileHeader)
	b.WriteString("no-resolv\nno-hosts\nno-poll\nbind-dynamic\n")
	fmt.Fprintf(&b, "addn-hosts=%s\n", filepath.Join(d.dir(), hostsName))
	fmt.Fprintf(&b, "dhcp-leasefile=%s\n", d.leases())

	// ---- DNS ----
	if svc.DNS.Enabled {
		b.WriteString("domain-needed\nbogus-priv\nlocalise-queries\n")
		ifs := nft.DNSInterfaces(cfg)
		for _, name := range ifs {
			fmt.Fprintf(&b, "interface=%s\n", name)
		}
		b.WriteString("listen-address=127.0.0.1\n")
		upstreams := svc.DNS.Upstreams
		if len(upstreams) == 0 {
			upstreams = cfg.System.DNSServers
		}
		for _, u := range upstreams {
			fmt.Fprintf(&b, "server=%s\n", u)
		}
		if svc.DNS.Domain != "" {
			fmt.Fprintf(&b, "domain=%s\nlocal=/%s/\nexpand-hosts\n", svc.DNS.Domain, svc.DNS.Domain)
		}
	} else {
		b.WriteString("port=0\n")
		if svc.DHCP.Enabled {
			// dnsmasq only serves DHCP on interfaces it listens on.
			for _, sc := range svc.DHCP.Scopes {
				if sc.Enabled {
					fmt.Fprintf(&b, "interface=%s\n", sc.Interface)
				}
			}
		}
	}

	// ---- DHCP ----
	if svc.DHCP.Enabled {
		b.WriteString("dhcp-authoritative\n")
		for _, sc := range svc.DHCP.Scopes {
			if !sc.Enabled {
				continue
			}
			in, _ := cfg.Interface(sc.Interface)
			prefix, perr := netip.ParsePrefix(in.IPv4.Address)
			if perr != nil {
				return "", "", fmt.Errorf("scope %s: %w", sc.Interface, perr)
			}
			maskStr := net.IP(net.CIDRMask(prefix.Bits(), 32)).String()
			lease := sc.LeaseTime
			if lease == "" {
				lease = "12h"
			}
			tag := "s_" + sanitizeTag(sc.Interface)
			fmt.Fprintf(&b, "dhcp-range=set:%s,%s,%s,%s,%s\n", tag, sc.RangeStart, sc.RangeEnd, maskStr, lease)
			gw := sc.Gateway
			if gw == "" {
				gw = prefix.Addr().String()
			}
			fmt.Fprintf(&b, "dhcp-option=tag:%s,option:router,%s\n", tag, gw)
			dns := sc.DNS
			if len(dns) == 0 {
				switch {
				case svc.DNS.Enabled:
					dns = []string{prefix.Addr().String()}
				case len(cfg.System.DNSServers) > 0:
					dns = cfg.System.DNSServers
				default:
					dns = svc.DNS.Upstreams
				}
			}
			if len(dns) > 0 {
				fmt.Fprintf(&b, "dhcp-option=tag:%s,option:dns-server,%s\n", tag, strings.Join(dns, ","))
			}
			domain := sc.Domain
			if domain == "" {
				domain = svc.DNS.Domain
			}
			if domain != "" {
				fmt.Fprintf(&b, "dhcp-option=tag:%s,option:domain-name,%s\n", tag, domain)
			}
		}
		for _, l := range svc.DHCP.StaticLeases {
			line := "dhcp-host=" + strings.ToLower(l.MAC) + "," + l.IP
			if l.Hostname != "" {
				line += "," + l.Hostname
			}
			b.WriteString(line + "\n")
		}
	}

	// ---- hosts ----
	var h strings.Builder
	h.WriteString(fileHeader)
	overrides := append([]model.HostOverride(nil), svc.DNS.HostOverrides...)
	sort.Slice(overrides, func(i, j int) bool { return overrides[i].Hostname < overrides[j].Hostname })
	for _, o := range overrides {
		fmt.Fprintf(&h, "%s %s\n", o.IP, o.Hostname)
	}
	// Static leases with hostnames resolve locally too.
	for _, l := range svc.DHCP.StaticLeases {
		if l.Hostname != "" {
			fmt.Fprintf(&h, "%s %s\n", l.IP, l.Hostname)
		}
	}
	return b.String(), h.String(), nil
}

func sanitizeTag(s string) string {
	return strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' {
			return r
		}
		return '_'
	}, s)
}

// Snapshot implements network.Backend.
func (d *Dnsmasq) Snapshot() (network.Files, error) {
	files := network.Files{}
	for _, name := range []string{confName, hostsName, enabledName} {
		raw, err := os.ReadFile(filepath.Join(d.dir(), name))
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, err
		}
		files[name] = string(raw)
	}
	if d.Resolv != "" {
		if raw, err := os.ReadFile(d.Resolv); err == nil && strings.HasPrefix(string(raw), "# Generated by ostiole") {
			files[resolvName] = string(raw)
		}
	}
	return files, nil
}

// Apply implements network.Backend: write the files and start, restart,
// or stop the unit to match.
func (d *Dnsmasq) Apply(ctx context.Context, files network.Files) error {
	if err := os.MkdirAll(d.dir(), 0o755); err != nil { //nolint:gosec // dnsmasq reads these unprivileged
		return err
	}
	current, err := d.Snapshot()
	if err != nil {
		return err
	}
	changed := false
	for _, name := range []string{confName, hostsName, enabledName} {
		content, want := files[name]
		path := filepath.Join(d.dir(), name)
		switch {
		case want && current[name] != content:
			if err := writeFile(path, content, 0o644); err != nil {
				return err
			}
			changed = true
		case !want && current[name] != "":
			if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
				return err
			}
			changed = true
		}
	}
	if d.Resolv != "" {
		if content, want := files[resolvName]; want && current[resolvName] != content {
			if err := writeFile(d.Resolv, content, 0o644); err != nil {
				return err
			}
		}
	}
	enabled := files[enabledName] != ""
	if !enabled {
		if current[enabledName] != "" {
			if out, err := d.cmd().Run(ctx, "systemctl", "disable", "--now", Unit); err != nil {
				return fmt.Errorf("stop %s: %w: %s", Unit, err, bytes.TrimSpace(out))
			}
		}
		return nil
	}
	if !changed {
		return nil
	}
	if !d.Installed(ctx) {
		return errors.New("dnsmasq is not set up on this host; run `ostiole services setup`")
	}
	if err := os.MkdirAll(filepath.Dir(d.leases()), 0o755); err != nil { //nolint:gosec // dnsmasq writes here unprivileged
		return err
	}
	if out, err := d.cmd().Run(ctx, "systemctl", "enable", Unit); err != nil {
		return fmt.Errorf("enable %s: %w: %s", Unit, err, bytes.TrimSpace(out))
	}
	if out, err := d.cmd().Run(ctx, "systemctl", "restart", Unit); err != nil {
		return fmt.Errorf("restart %s: %w: %s", Unit, err, bytes.TrimSpace(out))
	}
	return nil
}

// Installed reports whether the ostiole-dnsmasq unit exists.
func (d *Dnsmasq) Installed(ctx context.Context) bool {
	_, err := d.cmd().Run(ctx, "systemctl", "cat", Unit)
	return err == nil
}

// Active reports whether the unit is running.
func (d *Dnsmasq) Active(ctx context.Context) bool {
	out, err := d.cmd().Run(ctx, "systemctl", "is-active", Unit)
	return err == nil && strings.TrimSpace(string(out)) == "active"
}

func writeFile(path, content string, mode os.FileMode) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".*.tmp")
	if err != nil {
		return err
	}
	name := tmp.Name()
	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()
		_ = os.Remove(name)
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		_ = os.Remove(name)
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(name)
		return err
	}
	return os.Rename(name, path)
}

type execCommander struct{}

func (execCommander) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	return exec.CommandContext(ctx, name, args...).CombinedOutput()
}
