package services

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/rforced/ostiole/internal/model"
	"github.com/rforced/ostiole/internal/network"
)

// PPPoE paths and names.
const (
	// PPPoEDir is where pppd looks for the files named by `pppd call`.
	PPPoEDir = "/etc/ppp/peers"
	// PPPoEUnit is a templated unit: one instance per session, named after
	// the interface it brings up.
	PPPoEUnit = "ostiole-pppoe@.service"
	// PPPoEPrefix marks the peer files Ostiole owns.
	PPPoEPrefix = "ostiole-"
	// pppoeDefaultLCP is how pppd notices a line that has gone quiet:
	// an echo every 10 seconds, giving up after five unanswered.
	pppoeDefaultLCPInterval = 10
	pppoeDefaultLCPFailures = 5
)

// PPPoE runs dialled sessions through pppd. Each configured session gets
// a peer file and an instance of the templated unit; the interface pppd
// creates is an ordinary interface everywhere else in Ostiole.
type PPPoE struct {
	// Dir holds the peer files; default PPPoEDir.
	Dir string
	// Cmd runs systemctl; default execs it.
	Cmd network.Commander
}

var _ network.Backend = (*PPPoE)(nil)

// NewPPPoE returns a backend with production defaults.
func NewPPPoE() *PPPoE { return &PPPoE{Dir: PPPoEDir, Cmd: execCommander{}} }

func (p *PPPoE) dir() string {
	if p.Dir == "" {
		return PPPoEDir
	}
	return p.Dir
}

func (p *PPPoE) cmd() network.Commander {
	if p.Cmd == nil {
		return execCommander{}
	}
	return p.Cmd
}

// Name implements network.Backend.
func (p *PPPoE) Name() string { return "pppoe" }

// PeerFile is the name of the peer file for a session.
func PeerFile(iface string) string { return PPPoEPrefix + iface }

// unitFor is the instance of the templated unit that runs one session.
func unitFor(iface string) string {
	return strings.Replace(PPPoEUnit, "@.", "@"+iface+".", 1)
}

// Sessions lists the enabled PPPoE interfaces, in configuration order.
func Sessions(cfg *model.Config) []model.Interface {
	var out []model.Interface
	for _, in := range cfg.Interfaces {
		if in.PPPoE != nil && in.Enabled {
			out = append(out, in)
		}
	}
	return out
}

// Render implements network.Backend.
func (p *PPPoE) Render(cfg *model.Config) (network.Files, error) {
	files := network.Files{}
	for _, in := range Sessions(cfg) {
		files[PeerFile(in.Name)] = renderPeer(in, gatewayMetric(cfg, in.Name))
	}
	return files, nil
}

// gatewayMetric is the route metric a gateway on this interface asks for,
// or zero when none is configured. pppd installs the default route, so it
// is the one that has to know the metric.
func gatewayMetric(cfg *model.Config, iface string) int {
	for _, g := range cfg.Gateways {
		if g.Enabled && g.Interface == iface {
			return g.GatewayMetric()
		}
	}
	return 0
}

// renderPeer writes the options pppd reads for one session. The password
// lives here rather than in the shared pap-secrets and chap-secrets,
// which belong to whatever else the box runs; the file is root-only.
func renderPeer(in model.Interface, metric int) string {
	p := in.PPPoE
	var b strings.Builder
	b.WriteString("# Generated by ostiole. Do not edit; changes are overwritten on apply.\n")
	fmt.Fprintf(&b, "plugin rp-pppoe.so\n")
	fmt.Fprintf(&b, "nic-%s\n", p.Parent)
	// Without this the kernel names the interface ppp0, ppp1, … in the
	// order the sessions happen to come up, and firewall rules name
	// interfaces.
	fmt.Fprintf(&b, "ifname %s\n", in.Name)
	fmt.Fprintf(&b, "user %s\n", quotePPP(p.Username))
	fmt.Fprintf(&b, "password %s\n", quotePPP(p.Password))
	if p.ServiceName != "" {
		fmt.Fprintf(&b, "rp_pppoe_service %s\n", quotePPP(p.ServiceName))
	}
	if p.ACName != "" {
		fmt.Fprintf(&b, "rp_pppoe_ac %s\n", quotePPP(p.ACName))
	}
	// The provider authenticates us, not the other way round.
	b.WriteString("noauth\n")
	b.WriteString("hide-password\n")
	// Keep dialling: a line that drops at three in the morning should come
	// back without anyone noticing.
	b.WriteString("persist\n")
	b.WriteString("maxfail 0\n")
	b.WriteString("holdoff 5\n")
	// PPPoE takes eight bytes out of the Ethernet frame.
	mtu := in.MTU
	if mtu == 0 {
		mtu = model.PPPoEMTU
	}
	fmt.Fprintf(&b, "mtu %d\nmru %d\n", mtu, mtu)
	interval, failures := p.LCPInterval, p.LCPFailures
	if interval == 0 {
		interval = pppoeDefaultLCPInterval
	}
	if failures == 0 {
		failures = pppoeDefaultLCPFailures
	}
	fmt.Fprintf(&b, "lcp-echo-interval %d\nlcp-echo-failure %d\n", interval, failures)
	if in.IPv4.Mode == model.AddrPPP {
		if metric > 0 {
			fmt.Fprintf(&b, "defaultroute\ndefaultroute-metric %d\n", metric)
		} else {
			b.WriteString("defaultroute\n")
		}
		b.WriteString("replacedefaultroute\n")
	} else {
		b.WriteString("noipdefault\n")
	}
	if p.IPv6 {
		b.WriteString("+ipv6\n")
	} else {
		b.WriteString("noipv6\n")
	}
	// Ostiole decides what this box resolves with, so the provider's
	// servers are not written over /etc/resolv.conf.
	b.WriteString("usepeerdns\n")
	return b.String()
}

// quotePPP wraps a value in double quotes, which is how pppd takes a
// value containing spaces. A quote inside is escaped.
func quotePPP(s string) string {
	s = strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", " ", "\r", " ").Replace(s)
	return `"` + s + `"`
}

// Snapshot implements network.Backend.
func (p *PPPoE) Snapshot() (network.Files, error) {
	files := network.Files{}
	entries, err := os.ReadDir(p.dir())
	if errors.Is(err, os.ErrNotExist) {
		return files, nil
	}
	if err != nil {
		return nil, err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasPrefix(e.Name(), PPPoEPrefix) {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(p.dir(), e.Name()))
		if err != nil {
			return nil, err
		}
		files[e.Name()] = string(raw)
	}
	return files, nil
}

// Apply implements network.Backend: write the peer files, remove the ones
// that are no longer configured, and start or stop a unit for each.
func (p *PPPoE) Apply(ctx context.Context, files network.Files) error {
	current, err := p.Snapshot()
	if err != nil {
		return err
	}
	// A box that dials nothing, and never has, must not so much as create
	// a directory: the daemon runs under ProtectSystem=strict, and an
	// apply that has nothing to do with PPPoE cannot be allowed to fail
	// on it.
	if len(files) == 0 && len(current) == 0 {
		return nil
	}
	if len(files) > 0 && !p.Installed(ctx) {
		return errors.New("PPPoE is not set up on this box: run `ostiole services setup --with-pppoe` once as root")
	}
	if len(files) > 0 {
		if err := os.MkdirAll(p.dir(), 0o700); err != nil {
			return err
		}
	}

	// Stop what has gone away first, so a session cannot be left dialling
	// on a file that no longer exists.
	for name := range current {
		if _, keep := files[name]; keep {
			continue
		}
		iface := strings.TrimPrefix(name, PPPoEPrefix)
		if _, err := p.cmd().Run(ctx, "systemctl", "disable", "--now", unitFor(iface)); err != nil {
			return fmt.Errorf("stop the session on %s: %w", iface, err)
		}
		if err := os.Remove(filepath.Join(p.dir(), name)); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
	}

	for _, name := range sortedNames(files) {
		iface := strings.TrimPrefix(name, PPPoEPrefix)
		unit := unitFor(iface)
		changed := current[name] != files[name]
		if changed {
			// 0600: the provider's password is in here.
			if err := writeSecretFile(filepath.Join(p.dir(), name), files[name]); err != nil {
				return err
			}
		}
		if !changed && p.active(ctx, unit) {
			continue
		}
		if out, err := p.cmd().Run(ctx, "systemctl", "enable", "--now", unit); err != nil {
			return fmt.Errorf("start the session on %s: %w: %s", iface, err, strings.TrimSpace(string(out)))
		}
		if changed {
			if out, err := p.cmd().Run(ctx, "systemctl", "restart", unit); err != nil {
				return fmt.Errorf("restart the session on %s: %w: %s", iface, err, strings.TrimSpace(string(out)))
			}
		}
	}
	return nil
}

func sortedNames(files network.Files) []string {
	out := make([]string, 0, len(files))
	for name := range files {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// Installed reports whether the templated unit exists.
func (p *PPPoE) Installed(ctx context.Context) bool {
	_, err := p.cmd().Run(ctx, "systemctl", "cat", PPPoEUnit)
	return err == nil
}

func (p *PPPoE) active(ctx context.Context, unit string) bool {
	out, err := p.cmd().Run(ctx, "systemctl", "is-active", unit)
	return err == nil && strings.TrimSpace(string(out)) == "active"
}

// PPPoEUnitContent renders the templated unit. The instance name is the
// interface, which is also the peer file's suffix, so one template covers
// however many lines a box has.
func PPPoEUnitContent(pppd string) string {
	return `[Unit]
Description=Ostiole PPPoE session on %i
Documentation=man:pppd(8)
After=network-pre.target
Wants=network-pre.target

[Service]
Type=exec
ExecStart=` + pppd + ` call ` + PPPoEPrefix + `%i nodetach
Restart=always
RestartSec=5
# pppd needs to create an interface, set routes, and open a raw socket on
# the Ethernet link; it needs nothing else.
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW CAP_SYS_ADMIN
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=/etc/ppp /var/run /run
PrivateTmp=yes
ProtectKernelModules=no

[Install]
WantedBy=multi-user.target
`
}
