package dnsblock

import (
	"bufio"
	"fmt"
	"io"
	"sort"
	"strings"
	"time"

	"github.com/rforced/ostiole/internal/model"
)

// Header marks the generated include file. It is checked before the file is
// replaced, so Ostiole never writes over something it did not write.
const Header = "# Generated by ostiole. Do not edit; changes are overwritten on refresh.\n"

// FirefoxCanary is the name Firefox looks up to ask whether the network
// would rather it did not turn on DNS over HTTPS by itself. NXDOMAIN means
// "please do not".
const FirefoxCanary = "use-application-dns.net"

// Options is everything a render needs: what to block, what never to
// block, and how. It is derived from the configuration once and then
// written out beside the generated file, so the same inputs can be
// rendered again later without the configuration being to hand.
type Options struct {
	Enabled bool `json:"enabled"`
	// Mode is what a blocked name is answered with.
	Mode model.BlockMode `json:"mode,omitempty"`
	// Lists names the cached lists to merge, in any order.
	Lists []string `json:"lists,omitempty"`
	Allow []string `json:"allow,omitempty"`
	Deny  []string `json:"deny,omitempty"`
	// Never is what this box answers for itself. It is filtered out of the
	// blocklist but never carved out, because sending the local domain
	// upstream would be worse than blocking it.
	Never []string `json:"never,omitempty"`
	// Delegated are the domains handed to resolvers of their own. They are
	// left alone the same way Never is, and for the same reason a carve-out
	// would be wrong: dnsmasq already has a server line for the domain, and
	// a second entry for it would fight that one.
	Delegated []string `json:"delegated,omitempty"`
	// Canary answers the name Firefox uses to ask whether it should turn
	// on DNS over HTTPS by itself.
	Canary bool `json:"firefoxCanary,omitempty"`
	// Max is the ceiling on merged names; zero means the default.
	Max int `json:"max,omitempty"`
}

// OptionsFor reads the render inputs out of a configuration.
func OptionsFor(cfg *model.Config) Options {
	b := cfg.Blocking
	o := Options{
		Enabled:   cfg.BlockingActive(),
		Mode:      b.BlockMode(),
		Allow:     b.Allow,
		Deny:      b.Deny,
		Never:     cfg.NeverBlocked(),
		Delegated: cfg.DelegatedDomains(),
		Canary:    b.Enforce.FirefoxCanary,
		Max:       b.MaxDomains,
	}
	for _, l := range b.EnabledLists() {
		o.Lists = append(o.Lists, l.Name)
	}
	return o
}

// TooManyError says the merged list is bigger than the ceiling allows, and
// by how much, so the operator can decide what to turn off or how much
// memory to spend.
type TooManyError struct {
	Names   int
	Ceiling int
}

func (e *TooManyError) Error() string {
	return fmt.Sprintf(
		"the lists come to %d names, over the ceiling of %d; raise the ceiling (about %d MB of dnsmasq) or turn a list off",
		e.Names, e.Ceiling, e.Names*BytesPerName/(1<<20))
}

// Result reports what a render came to.
type Result struct {
	// Domains is how many names ended up blocked, after the lists were
	// merged, the redundant subdomains dropped and the allowed ones taken
	// back out. This is the number that costs memory in dnsmasq, and the
	// one the ceiling applies to — not the sum of the lists, which is
	// larger by however much they overlap.
	Domains int `json:"domains"`
	// Allowed is how many carve-outs were written.
	Allowed int `json:"allowed"`
	// At is when the merge happened.
	At time.Time `json:"at,omitempty"`
}

// EstimatedBytes is roughly what this many names cost dnsmasq.
func (r Result) EstimatedBytes() int64 { return int64(r.Domains) * BytesPerName }

// Render writes the dnsmasq include file: every name the enabled lists
// block, plus the operator's own deny list, minus everything allowed.
//
// It streams: the cached lists are read in order and merged, so a render of
// a million names costs one buffer, not a million strings.
func Render(w io.Writer, o Options, c *Cache) (Result, error) {
	var res Result
	ceiling := o.Max
	if ceiling <= 0 {
		ceiling = DefaultMaxDomains
	}

	// Everything allowed, as reversed keys: what the operator allowed, the
	// names this box answers for itself, and the domains it has handed to
	// resolvers of their own.
	untouchable := append(normalizeAll(o.Never), normalizeAll(o.Delegated)...)
	allowed := reducedKeys(append(normalizeAll(o.Allow), untouchable...))

	bw := bufio.NewWriterSize(w, 64<<10)
	if _, err := bw.WriteString(Header); err != nil {
		return res, err
	}
	if !o.Enabled {
		// dnsmasq is told to include this file whenever it answers
		// queries, so with blocking off it gets a file that says nothing
		// rather than no file at all.
		return res, bw.Flush()
	}

	// Carve-outs come first, so they are easy to find when reading the
	// file by hand. dnsmasq takes the most specific match whatever the
	// order, which is what makes them work under a blocked parent.
	//
	// Only what the operator allowed is written out. The names the box
	// answers for, and the domains it has delegated, are filtered from the
	// blocklist instead: a carve-out for the local domain would send its
	// queries upstream, which is the opposite of what it is for, and one
	// for a delegated domain would fight its own server line.
	never := map[string]bool{}
	for _, n := range untouchable {
		never[n] = true
	}
	for _, a := range reducedKeys(normalizeAll(o.Allow)) {
		name := reverseLabels(a)
		if never[name] {
			continue
		}
		if _, err := fmt.Fprintf(bw, "server=/%s/#\n", name); err != nil {
			return res, err
		}
		res.Allowed++
	}

	// The deny list and the canary are sources like any other, so they go
	// through the same merge and get the same redundancy check.
	extra := normalizeAll(o.Deny)
	if o.Canary {
		extra = append(extra, FirefoxCanary)
	}

	srcs := openSources(o, c, extra)
	defer closeSources(srcs)

	mode := o.Mode
	last := ""
	over := false
	for {
		key, ok := nextKey(srcs)
		if !ok {
			break
		}
		if last != "" && covers(last, key) {
			continue // a parent already blocks this
		}
		if coveredBy(allowed, key) {
			continue
		}
		last = key
		res.Domains++
		if res.Domains > ceiling {
			// Keep counting but stop writing: the operator needs the real
			// total to decide what to turn off, and it costs one more pass
			// over data that is already open.
			over = true
			continue
		}
		if err := writeEntry(bw, reverseLabels(key), mode); err != nil {
			return res, err
		}
	}
	if over {
		return res, &TooManyError{Names: res.Domains, Ceiling: ceiling}
	}
	if err := bw.Flush(); err != nil {
		return res, err
	}
	return res, nil
}

func writeEntry(w *bufio.Writer, name string, mode model.BlockMode) error {
	if mode == model.BlockNull {
		if _, err := fmt.Fprintf(w, "address=/%s/0.0.0.0\n", name); err != nil {
			return err
		}
		_, err := fmt.Fprintf(w, "address=/%s/::\n", name)
		return err
	}
	_, err := fmt.Fprintf(w, "local=/%s/\n", name)
	return err
}

// source is one stream of names in reversed-label order.
type source struct {
	rc   io.Closer
	sc   *bufio.Scanner
	mem  []string // for sources held in memory, already sorted
	i    int
	key  string
	live bool
}

func (s *source) advance() {
	if s.mem != nil {
		if s.i >= len(s.mem) {
			s.live = false
			return
		}
		s.key = s.mem[s.i]
		s.i++
		s.live = true
		return
	}
	for s.sc.Scan() {
		line := strings.TrimSpace(s.sc.Text())
		if line == "" {
			continue
		}
		s.key = reverseLabels(line)
		s.live = true
		return
	}
	s.live = false
}

func openSources(o Options, c *Cache, extra []string) []*source {
	var srcs []*source
	if len(extra) > 0 {
		srcs = append(srcs, &source{mem: reducedKeys(extra)})
	}
	for _, name := range o.Lists {
		rc, err := c.Open(name)
		if err != nil {
			continue // never fetched, or fetched and then lost; not fatal
		}
		sc := bufio.NewScanner(rc)
		sc.Buffer(make([]byte, 0, 64<<10), 1<<20)
		srcs = append(srcs, &source{rc: rc, sc: sc})
	}
	for _, s := range srcs {
		s.advance()
	}
	return srcs
}

func closeSources(srcs []*source) {
	for _, s := range srcs {
		if s.rc != nil {
			_ = s.rc.Close()
		}
	}
}

// nextKey returns the smallest key across the sources and advances past it,
// including past any duplicate of it. There are only ever a handful of
// sources, so a scan across them beats a heap.
func nextKey(srcs []*source) (string, bool) {
	best := ""
	for _, s := range srcs {
		if s.live && (best == "" || s.key < best) {
			best = s.key
		}
	}
	if best == "" {
		return "", false
	}
	for _, s := range srcs {
		for s.live && s.key == best {
			s.advance()
		}
	}
	return best, true
}

// normalizeAll keeps the names that are names.
func normalizeAll(in []string) []string {
	out := make([]string, 0, len(in))
	for _, s := range in {
		if d, ok := Normalize(s); ok {
			out = append(out, d)
		}
	}
	return out
}

// reducedKeys returns reversed keys, sorted, with anything a parent already
// covers removed.
func reducedKeys(domains []string) []string {
	keys := make([]string, 0, len(domains))
	for _, d := range domains {
		keys = append(keys, reverseLabels(d))
	}
	sort.Strings(keys)
	out := keys[:0]
	last := ""
	for _, k := range keys {
		if last != "" && covers(last, k) {
			continue
		}
		last = k
		out = append(out, k)
	}
	return out
}

// coveredBy reports whether any of the sorted reversed keys sits at or
// above key.
func coveredBy(sorted []string, key string) bool {
	// The candidate parent is the last entry that is <= key.
	i := sort.SearchStrings(sorted, key)
	if i < len(sorted) && sorted[i] == key {
		return true
	}
	return i > 0 && covers(sorted[i-1], key)
}
