// Package nft renders the Ostiole model to nftables text and drives the
// nft binary to validate, apply, and read back rulesets.
package nft

import (
	"fmt"
	"net/netip"
	"slices"
	"strconv"
	"strings"

	"ostiole/internal/model"
)

// Table is the only nftables table Ostiole manages.
const Table = "inet ostiole"

// Header is the first line of every rendered ruleset.
const Header = "# Generated by ostiole. Do not edit; changes are overwritten on apply."

// LogGroup is the nflog group every log statement targets; the daemon's
// firewall log listener reads it. Nothing goes to the kernel log.
const LogGroup = 1

// QueryLogGroup is the nflog group the resolver's answers are copied to
// while the query log is on; the daemon's query log listener reads it.
const QueryLogGroup = 2

// Render converts a validated configuration into an nftables ruleset that
// atomically replaces the Ostiole table when loaded with `nft -f`.
func Render(cfg *model.Config) (string, error) { return RenderWithFeeds(cfg, nil) }

// RenderWithFeeds is Render with the contents of fetched aliases supplied
// separately: blocklists and country ranges live in a cache, not in the
// configuration, so a revision stays readable and a rollback does not
// carry half a million addresses with it.
func RenderWithFeeds(cfg *model.Config, feeds map[string][]string) (string, error) {
	out, err := Build(cfg, feeds)
	if err != nil {
		return "", err
	}
	return out.Ruleset, nil
}

// render writes the whole table.
func (r *renderer) render() {
	r.line(Header)
	r.line("table " + Table)
	r.line("delete table " + Table)
	r.line("table " + Table + " {")
	r.indent++
	r.sets()
	r.chainInput()
	r.chainForward()
	r.chainOutput()
	r.zoneChains()
	r.floodChains()
	r.chainBlockDNS()
	r.policyChains()
	r.dnsViaChain()
	r.translateChains()
	r.replyChains()
	r.chainPostrouting()
	r.chainNATPrerouting()
	r.chainNATPostrouting()
	r.chainNATOutput()
	r.chainNATInput()
	r.upnpChains()
	r.indent--
	r.line("}")
}

// EmptyRuleset removes the Ostiole table entirely, restoring the kernel to
// the state before Ostiole was installed (other tables are untouched).
func EmptyRuleset() string {
	return Header + "\n" + "table " + Table + "\n" + "delete table " + Table + "\n"
}

type renderer struct {
	cfg *model.Config
	// feeds holds the entries of aliases that are fetched rather than
	// written out.
	feeds map[string][]string
	// resolverUIDs are the accounts the resolvers run as.
	resolverUIDs []uint32
	b            strings.Builder
	indent       int
	// system collects the rules Ostiole adds on its own, recorded as they
	// are written.
	system []SystemRule
	// nat does the same for outbound NAT.
	nat []SystemNAT
}

func (r *renderer) line(s string) {
	if s != "" {
		r.b.WriteString(strings.Repeat("\t", r.indent))
		r.b.WriteString(s)
	}
	r.b.WriteByte('\n')
}

func (r *renderer) block(open string, body func()) {
	r.line(open + " {")
	r.indent++
	body()
	r.indent--
	r.line("}")
}

// ---- sets ------------------------------------------------------------

func aliasSet(name string, family int) string {
	return fmt.Sprintf("alias_%s_v%d", name, family)
}

func aliasPortSet(name string) string {
	return "alias_" + name + "_ports"
}

// Sets Ostiole defines itself rather than from an alias.
const (
	privateSetV4 = "private_v4"
	privateSetV6 = "private_v6"
	bogonSetV4   = "bogons_v4"
	bogonSetV6   = "bogons_v6"
	// BogonFeed is the key the fetched bogon list is cached under. It is
	// not an alias: nobody writes it, and nothing references it by name.
	BogonFeed = "__bogons"
)

// splitFamilies partitions parsed addresses by IP family, preserving order.
func splitFamilies(addrs []string) (v4, v6 []string) {
	for _, a := range addrs {
		p, err := model.ParseAddress(a)
		if err != nil {
			continue // validated upstream
		}
		s := p.String()
		if p.Bits() == p.Addr().BitLen() {
			s = p.Addr().String()
		}
		if p.Addr().Is4() {
			v4 = append(v4, s)
		} else {
			v6 = append(v6, s)
		}
	}
	return v4, v6
}

// entriesOf is what an alias puts in its set: what is written in the
// configuration, less its URL lines, and what was fetched for it. A
// country or AS alias holds keys, never addresses, so only the fetched
// side counts.
func (r *renderer) entriesOf(a model.Alias) []string {
	if !a.Fetched() {
		return a.Entries
	}
	fetched := r.feeds[a.Name]
	if a.Keyed() {
		return fetched
	}
	return append(a.Written(), fetched...)
}

func (r *renderer) sets() {
	for _, a := range r.cfg.Aliases {
		for _, set := range AliasSets(a, r.entriesOf(a)) {
			r.set(set.Name, set.Type, set.Elements, a.Description)
		}
	}
	r.blockSets()
}

// blockSets defines the address sets the per-interface blocks match
// against: a fixed list for private and loopback, and a fetched one for
// the prefixes IANA has not allocated.
func (r *renderer) blockSets() {
	if len(r.interfacesBlocking(func(in model.Interface) bool { return in.BlockPrivate })) > 0 {
		v4, v6 := splitFamilies(model.PrivateSources)
		r.set(privateSetV4, "ipv4_addr", v4, "private and loopback addresses")
		r.set(privateSetV6, "ipv6_addr", v6, "unique local and loopback addresses")
	}
	if len(r.interfacesBlocking(func(in model.Interface) bool { return in.BlockBogons })) > 0 {
		v4, v6 := splitFamilies(r.feeds[BogonFeed])
		// Both sets exist whether or not today's list fills them, so a
		// refresh has somewhere to put tomorrow's.
		r.set(bogonSetV4, "ipv4_addr", v4, "prefixes IANA has not allocated")
		r.set(bogonSetV6, "ipv6_addr", v6, "prefixes IANA has not allocated")
	}
	r.busySets()
	r.protectionSets()
}

// busySet names the per-source connection tally of one zone and family.
func busySet(zone string, family int) string {
	return fmt.Sprintf("busy_%s_v%d", zone, family)
}

// busySetSize bounds the tally. The elements are the hosts on the zone, so
// on any real network this is far more than enough; the kernel collects an
// element as soon as the host it belongs to has no connections left, so
// the set does not grow with churn.
const busySetSize = 65535

// busySets defines the tallies. They are dynamic sets because counting
// connections per source is something only the kernel can do: it adds an
// element for each host it sees and keeps the count there, which is what
// makes `ct count` per host rather than per router.
func (r *renderer) busySets() {
	for _, z := range r.cfg.Zones {
		if z.Busy == nil || len(r.cfg.ZoneInterfaces(z.Name)) == 0 {
			continue
		}
		for _, fam := range []struct{ name, typ string }{
			{busySet(z.Name, 4), "ipv4_addr"},
			{busySet(z.Name, 6), "ipv6_addr"},
		} {
			r.block("set "+fam.name, func() {
				r.line("type " + fam.typ)
				r.line(fmt.Sprintf("size %d", busySetSize))
				r.line("flags dynamic")
				r.line(fmt.Sprintf("comment %q", "connections open per host in "+z.Name))
			})
		}
	}
}

// BlockSets lists the sets the bogon list fills, so a refresh can replace
// their contents without rebuilding the ruleset.
func BlockSets(cfg *model.Config, entries []string) []Set {
	if !cfg.BlocksBogons() {
		return nil
	}
	v4, v6 := splitFamilies(entries)
	return []Set{
		{Name: bogonSetV4, Type: "ipv4_addr", Elements: v4},
		{Name: bogonSetV6, Type: "ipv6_addr", Elements: v6},
	}
}

// Set is one nftables set: its name and the elements it holds. It is
// exported so a refreshed blocklist can replace the elements without
// rebuilding the ruleset.
type Set struct {
	Name     string
	Type     string
	Elements []string
}

// AliasSets returns the sets an alias renders to, given its entries.
//
// An alias written out by hand only gets a set for a family it has
// entries in; one that is fetched always gets both, even when empty,
// because tomorrow's list may have addresses this one does not and the
// rules have to be pointing at somewhere to put them.
func AliasSets(a model.Alias, entries []string) []Set {
	always := a.Fetched()
	switch a.Type {
	case model.AliasPorts:
		if len(entries) == 0 && !always {
			return nil
		}
		ports := make([]string, 0, len(entries))
		for _, e := range entries {
			pr, err := model.ParsePortRange(e)
			if err != nil {
				continue
			}
			ports = append(ports, pr.String())
		}
		return []Set{{Name: aliasPortSet(a.Name), Type: "inet_service", Elements: ports}}
	default:
		v4, v6 := splitFamilies(entries)
		var out []Set
		if len(v4) > 0 || always {
			out = append(out, Set{Name: aliasSet(a.Name, 4), Type: "ipv4_addr", Elements: v4})
		}
		if len(v6) > 0 || always {
			out = append(out, Set{Name: aliasSet(a.Name, 6), Type: "ipv6_addr", Elements: v6})
		}
		return out
	}
}

func (r *renderer) set(name, typ string, elems []string, comment string) {
	r.block("set "+name, func() {
		r.line("type " + typ)
		r.line("flags interval")
		r.line("auto-merge")
		if comment != "" {
			r.line(fmt.Sprintf("comment %q", sanitizeComment(comment)))
		}
		if len(elems) > 0 {
			r.line("elements = { " + strings.Join(elems, ", ") + " }")
		}
	})
}

// ---- base chains -------------------------------------------------------

func (r *renderer) chainInput() {
	r.block("chain input", func() {
		r.line("type filter hook input priority filter; policy drop;")
		r.line(`iifname "lo" accept`)
		r.connectionState("input")
		r.linkLocalBaseline()
		r.blockedSources("input")
		r.antiLockout()
		r.serviceRules()
		r.zoneDispatch()
		r.defaultDrop("input")
	})
}

// linkLocalBaseline accepts what IP cannot work without, and it does so
// ahead of the source-address blocks on purpose. Neighbour discovery,
// router advertisements, and DHCPv6 answers all arrive from fe80::/10,
// and the fetched bogon list contains that prefix, so a WAN that blocks
// bogons would otherwise drop its gateway's neighbour solicitations and
// never get an IPv6 address or a default route.
//
// Each family is accepted only on the interfaces that have it: an
// interface whose IPv6 mode is none carries no IPv6 rule, so turning the
// family off is visible on the rules page and in the kernel alike.
//
// Nothing here lets a spoofed source in. Neighbour discovery is untracked
// by conntrack and the kernel discards it unless the hop limit is 255,
// so it cannot be routed in from off-link. An ICMP error is either
// related to a tracked flow, which the state rule accepted already, or
// invalid, which the state rule dropped already. Echo is deliberately
// absent: whether this firewall answers ping is a zone rule.
// ICMP an interface needs: errors, and IPv6's neighbour discovery and MLD.
const (
	icmpErrors   = "{ destination-unreachable, time-exceeded, parameter-problem }"
	icmpv6Needed = "{ nd-neighbor-solicit, nd-neighbor-advert, nd-router-solicit, nd-router-advert, " +
		"destination-unreachable, packet-too-big, time-exceeded, parameter-problem, " +
		"mld-listener-query, mld-listener-report, mld-listener-done }"
)

func (r *renderer) linkLocalBaseline() {
	if v4 := r.interfacesWith(func(in model.Interface) model.AddrMode { return in.IPv4.Mode }); len(v4) > 0 {
		// Error messages that IPv4 needs to function (no echo: that is a user rule).
		r.line(fmt.Sprintf("iifname %s icmp type %s accept", ifnameSet(v4), icmpErrors))
		r.sysFor(v4, SystemRule{
			Chain: "input", Action: "accept", Protocol: string(model.ProtocolICMP),
			Source: "any", Destination: firewallDest(nil),
			Description: "ICMP errors", Setting: "interface",
		})
	}
	if v6 := r.interfacesWith(func(in model.Interface) model.AddrMode { return in.IPv6.Mode }); len(v6) > 0 {
		// Neighbour discovery, MLD, and error messages that IPv6 cannot work without.
		r.line(fmt.Sprintf("iifname %s icmpv6 type %s accept", ifnameSet(v6), icmpv6Needed))
		r.sysFor(v6, SystemRule{
			Chain: "input", Action: "accept", Protocol: string(model.ProtocolICMP),
			Source: "any", Destination: firewallDest(nil),
			Description: "IPv6 neighbour discovery and errors", Setting: "interface",
		})
	}
	r.dhcpv6ClientRules()
}

// interfacesWith lists the enabled interfaces on which one address family
// is turned on, given how to read that family's mode. A mode of none, or
// none given (a port carries no address of its own), leaves it out.
func (r *renderer) interfacesWith(mode func(model.Interface) model.AddrMode) []string {
	var out []string
	for _, in := range r.cfg.Interfaces {
		if m := mode(in); in.Enabled && m != model.AddrNone && m != "" {
			out = append(out, in.Name)
		}
	}
	return out
}

// dhcpv6ClientRules let the answers to this router's own DHCPv6 requests
// in, on the interfaces that make them. The request goes to a multicast
// group and the answer comes back from the server's link-local address,
// so conntrack never pairs the two and the state rule sees no reply.
// The server is on the link by definition, which is what the link-local
// match on both ends says.
func (r *renderer) dhcpv6ClientRules() {
	var ifs []string
	for _, in := range r.cfg.Interfaces {
		if in.Enabled && in.DHCPv6Client() {
			ifs = append(ifs, in.Name)
		}
	}
	if len(ifs) == 0 {
		return
	}
	r.line(fmt.Sprintf(`iifname %s ip6 saddr fe80::/10 ip6 daddr fe80::/10 udp sport 547 udp dport 546 counter accept comment "client:dhcpv6"`,
		ifnameSet(ifs)))
	r.sysFor(ifs, SystemRule{
		Chain: "input", Action: "accept", Protocol: string(model.ProtocolUDP),
		Source: "link-local : 547", Destination: firewallDest([]string{"546"}),
		Description: "DHCPv6 answers to this router's own requests",
		Keys:        []string{"input/client:dhcpv6"}, Setting: "interface",
	})
}

// connectionState opens a base chain: replies to what was allowed pass,
// packets that belong to no connection do not. Both base chains carry the
// two rules; the rows are recorded once, from input.
func (r *renderer) connectionState(chain string) {
	r.line("ct state established,related accept")
	r.line("ct state invalid drop")
	if chain != "input" {
		return
	}
	r.sys(SystemRule{
		Chain: chain, Action: "accept", Protocol: string(model.ProtocolAny),
		Source: "any", Destination: "any",
		Description: "Replies and related traffic of connections already allowed",
	})
	r.sys(SystemRule{
		Chain: chain, Action: "drop", Protocol: string(model.ProtocolAny),
		Source: "any", Destination: "any",
		Description: "Packets that belong to no connection",
	})
}

// serviceRules lets DHCP, DNS and time clients reach the services this
// router runs, regardless of zone rules, on the interfaces that serve them.
func (r *renderer) serviceRules() {
	svc := r.cfg.Services
	if svc.DHCP.Enabled {
		var ifs []string
		for _, sc := range r.cfg.ActiveDHCP() {
			ifs = append(ifs, sc.Interface)
		}
		if len(ifs) > 0 {
			r.line(fmt.Sprintf(`iifname %s udp dport 67 counter accept comment "service:dhcp"`, ifnameSet(ifs)))
			r.sysFor(ifs, SystemRule{
				Chain: "input", Action: "accept", Protocol: string(model.ProtocolUDP),
				Source: "any", Destination: firewallDest([]string{"67"}),
				Description: "DHCP requests", Keys: []string{"input/service:dhcp"}, Setting: "dhcp",
			})
		}
		// Router advertisements need no rule (ICMPv6 is in the baseline and
		// output is open), but stateful and stateless DHCPv6 do.
		var v6 []string
		for _, sc := range r.cfg.ActiveDHCPv6() {
			if sc.Mode != model.RASLAAC {
				v6 = append(v6, sc.Interface)
			}
		}
		if len(v6) > 0 {
			r.line(fmt.Sprintf(`iifname %s udp dport 547 counter accept comment "service:dhcpv6"`, ifnameSet(v6)))
			r.sysFor(v6, SystemRule{
				Chain: "input", Action: "accept", Protocol: string(model.ProtocolUDP),
				Source: "any", Destination: firewallDest([]string{"547"}),
				Description: "DHCPv6 requests", Keys: []string{"input/service:dhcpv6"}, Setting: "dhcp",
			})
		}
	}
	if svc.DNS.Enabled {
		ifs := DNSInterfaces(r.cfg)
		if len(ifs) > 0 {
			r.line(fmt.Sprintf(`iifname %s meta l4proto { tcp, udp } th dport 53 fib daddr type local counter accept comment "service:dns"`, ifnameSet(ifs)))
			r.sysFor(ifs, SystemRule{
				Chain: "input", Action: "accept", Protocol: string(model.ProtocolTCPUDP),
				Source: "any", Destination: firewallDest([]string{"53"}),
				Description: "DNS queries", Keys: []string{"input/service:dns"}, Setting: "dns",
			})
		}
	}
	if r.cfg.NTPServing() {
		ifs := r.cfg.NTPInterfaces()
		r.line(fmt.Sprintf(`iifname %s udp dport 123 fib daddr type local counter accept comment "service:ntp"`, ifnameSet(ifs)))
		r.sysFor(ifs, SystemRule{
			Chain: "input", Action: "accept", Protocol: string(model.ProtocolUDP),
			Source: "any", Destination: firewallDest([]string{"123"}),
			Description: "NTP requests", Keys: []string{"input/service:ntp"}, Setting: "ntp",
		})
	}
	r.wireguardRules()
	r.tailscaleRules()
	r.upnpRules()
	r.acmeRules()
}

// acmeRules let a CA reach the http-01 solver. The listener is only bound
// while a challenge is pending, but the rule stands for as long as a
// certificate is answering challenges: an apply in the middle of an order
// would otherwise shut the door on it.
func (r *renderer) acmeRules() {
	// A proxy open on an external zone at port 80 answers the challenge
	// itself, and its own rule opens the port.
	if !r.cfg.HTTP01Certificates() || r.cfg.ProxyAnswersChallenges() {
		return
	}
	ifs := r.externalInterfaces()
	if len(ifs) == 0 {
		return
	}
	if !r.cfg.ProxyEnabled() {
		r.line(fmt.Sprintf(`iifname %s tcp dport 80 counter accept comment "service:acme"`, ifnameSet(ifs)))
		r.sysFor(ifs, SystemRule{
			Chain: "input", Action: "accept", Protocol: string(model.ProtocolTCP),
			Source: "any", Destination: firewallDest([]string{"80"}),
			Description: "Certificate challenges", Keys: []string{"input/service:acme"}, Setting: "certificates",
		})
		return
	}
	// With the proxy up, acmeRedirect sends port 80 from outside to the
	// solver. Only what it redirected gets in: the port stays shut to a
	// direct connection.
	r.line(fmt.Sprintf(`iifname %s tcp dport %d ct status dnat counter accept comment "service:acme"`,
		ifnameSet(ifs), model.ChallengePort))
	r.sysFor(ifs, SystemRule{
		Chain: "input", Action: "accept", Protocol: string(model.ProtocolTCP),
		Source: "any", Destination: firewallDest([]string{strconv.Itoa(model.ChallengePort)}),
		Description: "Certificate challenges redirected from port 80",
		Keys:        []string{"input/service:acme"}, Setting: "certificates",
	})
}

// acmeRedirect sends port 80 from outside to the http-01 solver while the
// proxy holds port 80 without answering there from outside, so a
// certificate never needs the proxy's sites open on the WAN.
func (r *renderer) acmeRedirect() {
	if !r.cfg.HTTP01Certificates() || !r.cfg.ProxyEnabled() || r.cfg.ProxyAnswersChallenges() {
		return
	}
	ifs := r.externalInterfaces()
	if len(ifs) == 0 {
		return
	}
	r.line(fmt.Sprintf(`iifname %s tcp dport 80 counter redirect to :%d comment "service:acme"`,
		ifnameSet(ifs), model.ChallengePort))
	r.sysFor(ifs, SystemRule{
		Chain: "nat_prerouting", Action: "redirect", Protocol: string(model.ProtocolTCP),
		Source: "any", Destination: firewallDest([]string{"80"}),
		Description: "Certificate challenges to the solver",
		Keys:        []string{"nat_prerouting/service:acme"}, Setting: "certificates",
	})
}

// externalInterfaces lists the interfaces in external zones.
func (r *renderer) externalInterfaces() []string {
	var out []string
	for _, z := range r.cfg.Zones {
		if z.External {
			out = append(out, r.cfg.ZoneInterfaces(z.Name)...)
		}
	}
	return out
}

// upnpRules let clients reach miniupnpd: SSDP discovery and the device
// description for IGD, and the NAT-PMP and PCP port for the other half.
// Unlike DNS there is no "fib daddr type local" here, because SSDP is
// addressed to a multicast group rather than to this router.
func (r *renderer) upnpRules() {
	if !UPnPEnabled(r.cfg) {
		return
	}
	ifs := UPnPInterfaces(r.cfg)
	if len(ifs) == 0 {
		return
	}
	u := r.cfg.Services.UPnP
	var udp []string
	if u.IGD {
		udp = append(udp, fmt.Sprint(ssdpPort))
	}
	if u.PCP {
		udp = append(udp, fmt.Sprint(pcpPort))
	}
	r.line(fmt.Sprintf(`iifname %s udp dport %s counter accept comment "service:upnp"`,
		ifnameSet(ifs), setOrSingle(udp)))
	ports, proto := udp, model.ProtocolUDP
	if u.IGD {
		r.line(fmt.Sprintf(`iifname %s tcp dport %d counter accept comment "service:upnp"`,
			ifnameSet(ifs), upnpHTTPPort))
		ports, proto = append(ports, fmt.Sprint(upnpHTTPPort)), model.ProtocolTCPUDP
	}
	r.sysFor(ifs, SystemRule{
		Chain: "input", Action: "accept", Protocol: string(proto),
		Source: "any", Destination: firewallDest(ports),
		Description: "UPnP and NAT-PMP requests", Keys: []string{"input/service:upnp"}, Setting: "upnp",
	})
}

// wireguardRules open the listening ports of tunnels on external zones,
// where peers dial in from. A tunnel nobody can reach is not a tunnel.
func (r *renderer) wireguardRules() {
	var ports []string
	seen := map[uint16]bool{}
	for _, in := range r.cfg.Interfaces {
		if in.WireGuard == nil || !in.Enabled || in.WireGuard.ListenPort == 0 || seen[in.WireGuard.ListenPort] {
			continue
		}
		seen[in.WireGuard.ListenPort] = true
		ports = append(ports, fmt.Sprint(in.WireGuard.ListenPort))
	}
	if len(ports) == 0 {
		return
	}
	var ifs []string
	for _, z := range r.cfg.Zones {
		if z.External {
			ifs = append(ifs, r.cfg.ZoneInterfaces(z.Name)...)
		}
	}
	if len(ifs) == 0 {
		return
	}
	r.line(fmt.Sprintf(`iifname %s udp dport %s counter accept comment "service:wireguard"`,
		ifnameSet(ifs), setOrSingle(ports)))
	r.sysFor(ifs, SystemRule{
		Chain: "input", Action: "accept", Protocol: string(model.ProtocolUDP),
		Source: "any", Destination: firewallDest(ports),
		Description: "WireGuard peers dialling in", Keys: []string{"input/service:wireguard"}, Setting: "wireguard",
	})
}

// tailscaleRules open the port peers dial directly on the external zones.
// Without it the node still works through a relay, slowly.
func (r *renderer) tailscaleRules() {
	in, ok := r.cfg.TailscaleInterface()
	if !ok || !in.Enabled || in.Tailscale.Port == 0 {
		return
	}
	var ifs []string
	for _, z := range r.cfg.Zones {
		if z.External {
			ifs = append(ifs, r.cfg.ZoneInterfaces(z.Name)...)
		}
	}
	if len(ifs) == 0 {
		return
	}
	port := fmt.Sprint(in.Tailscale.Port)
	r.line(fmt.Sprintf(`iifname %s udp dport %s counter accept comment "service:tailscale"`,
		ifnameSet(ifs), port))
	r.sysFor(ifs, SystemRule{
		Chain: "input", Action: "accept", Protocol: string(model.ProtocolUDP),
		Source: "any", Destination: firewallDest([]string{port}),
		Description: "Tailscale peers dialling in", Keys: []string{"input/service:tailscale"}, Setting: "tailscale",
	})
}

// TailscaleEnabled reports whether the configuration wants tailscaled.
func TailscaleEnabled(cfg *model.Config) bool {
	in, ok := cfg.TailscaleInterface()
	return ok && in.Enabled
}

// DNSInterfaces lists where the DNS service listens: the configured list,
// or every interface outside external zones. Either way a disabled
// interface is left out; nothing arrives on it to answer.
func DNSInterfaces(cfg *model.Config) []string {
	return cfg.InsideInterfaces(cfg.Services.DNS.Interfaces)
}

// The chains miniupnpd is pointed at. It creates none of its own: its
// nftables backend inserts rules into chains it is given the names of,
// which is how Ostiole keeps every rule inside its own table. They are
// regular chains, so the family and hook come from whoever jumps to them.
const (
	UPnPPreroutingChain  = "upnp_prerouting"
	UPnPForwardChain     = "upnp_forward"
	UPnPPostroutingChain = "upnp_postrouting"
)

const (
	ssdpPort     = 1900
	pcpPort      = 5351
	upnpHTTPPort = 2189
)

// UPnPEnabled reports whether the configuration wants miniupnpd. Enabled
// on its own does nothing: one of the two protocols has to answer.
func UPnPEnabled(cfg *model.Config) bool {
	u := cfg.Services.UPnP
	return u.Enabled && (u.IGD || u.PCP)
}

// UPnPInterfaces lists where clients may ask for a mapping: the configured
// list, or every enabled interface outside external zones, never the
// external interface itself. WireGuard and Tailscale interfaces have to be
// listed by name: otherwise a device that dials in could open a port on the
// WAN to itself.
func UPnPInterfaces(cfg *model.Config) []string {
	u := cfg.Services.UPnP
	if len(u.Interfaces) > 0 {
		return u.Interfaces
	}
	var ifs []string
	for _, in := range cfg.Interfaces {
		if !in.Enabled || in.Zone == "" || in.Name == u.ExternalInterface || in.WireGuard != nil || in.Tailscale != nil {
			continue
		}
		if z, ok := cfg.Zone(in.Zone); ok && !z.External {
			ifs = append(ifs, in.Name)
		}
	}
	return ifs
}

// upnpChains renders the three chains miniupnpd fills in, empty. They are
// rendered whether or not a mapping exists today: the daemon adds to a
// chain, it does not create one, and every apply rebuilds this table.
func (r *renderer) upnpChains() {
	if !UPnPEnabled(r.cfg) {
		return
	}
	for _, name := range []string{UPnPPreroutingChain, UPnPForwardChain, UPnPPostroutingChain} {
		r.block("chain "+name, func() {})
	}
}

func (r *renderer) chainForward() {
	r.block("chain forward", func() {
		r.line("type filter hook forward priority filter; policy drop;")
		r.shapeRestore("forward")
		r.clampPPPoE()
		r.clampTunnels()
		r.killSwitch()
		r.translateHold("forward")
		r.connectionState("forward")
		r.blockedSources("forward")
		r.blockDNSJump()
		// What port forwards, 1:1 mappings and UPnP send inside is
		// accepted at the tail of the zone it arrives from, not here: see
		// forwardAccepts.
		r.zoneDispatch()
		r.defaultDrop("forward")
	})
}

// clampPPPoE lowers the segment size a TCP handshake offers across a PPPoE
// link to what fits in it. A client at 1500 behind a 1492 link otherwise
// stalls on every site whose path MTU discovery is broken. It comes before
// the connection state, since the answer to a forwarded port's SYN is
// already an established packet.
func (r *renderer) clampPPPoE() {
	var ifs []string
	for _, in := range r.cfg.Interfaces {
		if in.Enabled && in.PPPoE != nil {
			ifs = append(ifs, in.Name)
		}
	}
	if len(ifs) == 0 {
		return
	}
	r.line(fmt.Sprintf(`oifname %s tcp flags syn tcp option maxseg size set rt mtu counter comment "pppoe-mss"`, ifnameSet(ifs)))
	r.sys(SystemRule{
		Chain: "forward", Action: "continue", Protocol: string(model.ProtocolTCP),
		Source: "any", Destination: "any",
		Description: "Shrink TCP segments to fit the PPPoE link",
		Keys:        []string{"forward/pppoe-mss"}, Setting: "interface",
	})
}

// killSwitch holds the traffic of a group set to block, and of a tunnel
// gateway, to their own lines. The policy table drops the traffic while
// every member is down,
// but the tables come from the daemon: from the ruleset's load at boot
// until the daemon's first pass, the mark routes nowhere and the traffic
// would take the main table out whichever WAN holds the default route. It
// comes before the connection state, so a flow already going cannot move
// to another WAN either.
func (r *renderer) killSwitch() {
	for _, t := range r.cfg.BlockingTargets() {
		// A rule puts the mark on forwarded traffic, so a target no rule
		// routes through has nothing here to hold.
		zones := r.gatewayZones(t.Name)
		others := r.otherExternals(t)
		if len(zones) == 0 || len(others) == 0 {
			continue
		}
		key := "kill-switch:" + t.Name
		r.line(fmt.Sprintf(`ct mark & 0x%08x == 0x%x oifname %s counter drop comment %q`,
			model.PolicyMarkMask, t.Mark, ifnameSet(others), key))
		what := "Keep a blocking group's traffic off every other WAN"
		if !t.Group {
			what = "Keep a tunnel gateway's traffic off every other WAN"
		}
		r.sys(SystemRule{
			Chain: "forward", Zones: zones, Action: "drop", Protocol: string(model.ProtocolAny),
			Source: "routed through " + t.Name, Destination: "out " + strings.Join(others, ", "),
			Description: what,
			Keys:        []string{"forward/" + key}, Setting: "routing",
		})
	}
}

// otherExternals lists the interfaces of external zones that are none of
// a blocking target's lines.
func (r *renderer) otherExternals(t model.BlockingTarget) []string {
	var out []string
	for _, z := range r.cfg.Zones {
		if !z.External {
			continue
		}
		for _, name := range r.cfg.ZoneInterfaces(z.Name) {
			if !slices.Contains(t.Interfaces, name) {
				out = append(out, name)
			}
		}
	}
	return out
}

// gatewayZones lists the zones whose enabled rules route through a gateway
// or group, in zone order.
func (r *renderer) gatewayZones(name string) []string {
	var out []string
	for _, z := range r.cfg.Zones {
		for i := range r.cfg.Rules {
			if rule := &r.cfg.Rules[i]; rule.Enabled && rule.Zone == z.Name && rule.Gateway == name {
				out = append(out, z.Name)
				break
			}
		}
	}
	return out
}

func (r *renderer) chainOutput() {
	r.block("chain output", func() {
		r.line("type filter hook output priority filter; policy accept;")
		r.shapeRestore("output")
		r.queryLogRule()
	})
}

// queryLogRule copies the resolver's answers to the daemon, for the query
// log and for naming Traffic's destinations. Only what this router answers
// itself: a reply forwarded for a client that asked somebody else goes
// through forward and is not its answer. Answers over TCP come too, every
// segment of them; the daemon reads the one that starts an answer.
func (r *renderer) queryLogRule() {
	dns := r.cfg.Services.DNS
	if !dns.Enabled || (!dns.QueryLog.Enabled && !r.cfg.Traffic.DestinationsOn()) {
		return
	}
	ifs := DNSInterfaces(r.cfg)
	if len(ifs) == 0 {
		return
	}
	r.line(fmt.Sprintf(`oifname %s meta l4proto { tcp, udp } th sport 53 counter log group %d comment "dns-log"`,
		ifnameSet(ifs), QueryLogGroup))
	r.sysFor(ifs, SystemRule{
		Chain: "output", Action: "continue", Protocol: string(model.ProtocolTCPUDP),
		Source: firewallDest([]string{"53"}), Destination: "any",
		Description: "DNS query logger",
		Keys:        []string{"output/dns-log"}, Setting: "queryLog",
	})
}

// ---- traffic shaping --------------------------------------------------

// Mark arithmetic for the tier a flow is in. The tier is set inside the
// rule that admits the flow rather than in a chain of its own: unlike
// policy routing it does not have to beat the routing decision, so there
// is nothing to mirror ahead of it.
const (
	shapeSet        = "meta mark set meta mark & 0x%08x | 0x%08x"
	shapeTest       = "ct mark & 0x%08x != 0x0"
	shapeCopy       = "ct mark set ct mark & 0x%08x | 0x%08x"
	shapeRestoreTag = "shaping:restore"
)

// shapeMark is what a rule does to put its traffic in a tier: the tier
// goes into the packet mark and into the connection's, leaving the rest of
// both alone. Later packets and the replies coming back are tiered from
// the connection's without being matched again. Copying the whole packet
// mark instead would also store what other features put on this packet
// alone, such as a translation's mark, and put it back on the replies.
func shapeMark(t model.Tier) []string {
	mark, ok := t.Mark()
	if !ok {
		return nil
	}
	return []string{
		fmt.Sprintf(shapeSet, ^uint32(model.ShapeMarkMask), mark),
		fmt.Sprintf(shapeCopy, ^uint32(model.ShapeMarkMask), mark),
	}
}

// shapePrefix is shapeMark for a rule assembled by formatting rather than
// by joining parts, and empty when the rule sets no tier.
func shapePrefix(t model.Tier) string {
	parts := shapeMark(t)
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, " ") + " "
}

// busyHosts holds back a host that already has a lot of connections open,
// which is what file sharing looks like from outside whatever port it is
// on and however well encrypted it is.
//
// It comes before the zone's own rules so that a rule which names a
// priority still wins: a call from a busy host is still a call. The tier
// is copied onto the connection here rather than left to the rule's
// verdict, because the rule that accepts the flow may set no tier of its
// own and the copy is what makes one stick.
//
// Only the connections over the limit are marked. The kernel keeps the
// tally and drops it as the host's connections close, so a host that
// settles down stops being held back without anything being reset.
func (r *renderer) busyHosts(z model.Zone) {
	b := z.Busy
	if b == nil || len(r.cfg.ZoneInterfaces(z.Name)) == 0 {
		return
	}
	if _, ok := b.Priority.Mark(); !ok {
		return
	}
	set := strings.Join(shapeMark(b.Priority), " ")
	for _, fam := range []struct{ set, prefix string }{
		{busySet(z.Name, 4), "ip"},
		{busySet(z.Name, 6), "ip6"},
	} {
		r.line(fmt.Sprintf(`ct state new add @%s { %s saddr ct count over %d } counter %s comment "busy:%s"`,
			fam.set, fam.prefix, b.Connections, set, z.Name))
	}
	r.sys(SystemRule{
		Chain: "zone_" + z.Name, Zones: []string{z.Name}, Action: "continue",
		Protocol:    string(model.ProtocolAny),
		Source:      fmt.Sprintf("a host past %d connections", b.Connections),
		Destination: "any",
		Description: "Hold back a host that is opening a lot of connections at once",
		Keys:        []string{"zone_" + z.Name + "/busy:" + z.Name}, Setting: "shaping",
	})
}

// shapeRestore puts a connection's tier back on the packet before the
// state rule accepts it, which is what makes one classification cover a
// whole flow. It sits in forward for traffic passing through and in
// output for the router's own replies, which are on a shaped interface
// like anything else.
func (r *renderer) shapeRestore(chain string) {
	if !r.cfg.ShapesTraffic() {
		return
	}
	r.line(fmt.Sprintf(shapeTest+" meta mark set ct mark counter comment %q", model.ShapeMarkMask, shapeRestoreTag))
	if chain != "forward" {
		return
	}
	// Both chains carry the same rule; the row is recorded once, with the
	// counter keys of both.
	r.sys(SystemRule{
		Chain: chain, Action: "continue", Protocol: string(model.ProtocolAny),
		Source: "any", Destination: "any",
		Description: "Put a connection's priority back on its later packets",
		Keys:        []string{"forward/" + shapeRestoreTag, "output/" + shapeRestoreTag}, Setting: "shaping",
	})
}

func (r *renderer) antiLockout() {
	m := r.cfg.System.Management
	var ports []string
	if m.WebPort != 0 {
		ports = append(ports, fmt.Sprint(m.WebPort))
	}
	if m.SSHPort != 0 && m.SSHPort != m.WebPort {
		ports = append(ports, fmt.Sprint(m.SSHPort))
	}
	if len(ports) == 0 {
		return
	}
	for _, z := range r.cfg.Zones {
		if !z.AntiLockout {
			continue
		}
		ifs := r.cfg.ZoneInterfaces(z.Name)
		if len(ifs) == 0 {
			continue
		}
		r.line(fmt.Sprintf("iifname %s tcp dport %s counter accept comment \"anti-lockout:%s\"",
			ifnameSet(ifs), setOrSingle(ports), z.Name))
		r.sys(SystemRule{
			Chain: "input", Zones: []string{z.Name}, Action: "accept", Protocol: string(model.ProtocolTCP),
			Source: "any", Destination: firewallDest(ports),
			Description: "Anti-lockout, keeps the web UI and SSH reachable",
			Keys:        []string{"input/anti-lockout:" + z.Name}, Setting: "zone",
		})
	}
}

func (r *renderer) zoneDispatch() {
	for _, z := range r.cfg.Zones {
		ifs := r.cfg.ZoneInterfaces(z.Name)
		if len(ifs) == 0 {
			continue
		}
		r.line(fmt.Sprintf("iifname %s jump zone_%s", ifnameSet(ifs), z.Name))
	}
}

// defaultDrop ends a base chain. Every interface can decide for itself
// whether a packet dropped here is logged, so the common case stays one
// counter and a sampled log, and only a router with an exception pays for
// more.
//
// The log line carries no interface name because it does not need one:
// the kernel tells the log listener which interface a packet arrived on.
func (r *renderer) defaultDrop(chain string) {
	prefix := fmt.Sprintf("ostiole:c:%s:drop: ", chain)
	quiet := `counter comment "default-drop"`

	def := r.cfg.System.Management.LogDefaultDrops
	var exceptions []string
	for _, in := range r.cfg.Interfaces {
		if in.Enabled && in.LogDrops != nil && *in.LogDrops != def {
			exceptions = append(exceptions, in.Name)
		}
	}
	if len(exceptions) == 0 {
		if def {
			r.line(sampledLog("", "", prefix, "log:default-drop"))
		}
		r.line(quiet)
		return
	}

	// The exceptions get an explicit verdict so they stop here; everything
	// else, including traffic on an interface Ostiole knows nothing about,
	// falls through to the chain's own behaviour.
	if def {
		r.line(fmt.Sprintf(`iifname %s counter drop comment "default-drop:quiet"`, ifnameSet(exceptions)))
		r.line(sampledLog("", "", prefix, "log:default-drop"))
		r.line(quiet)
		return
	}
	r.line(sampledLog("", ifnameSet(exceptions), prefix, "log:default-drop"))
	r.line(fmt.Sprintf(`iifname %s counter drop comment "default-drop:logged"`, ifnameSet(exceptions)))
	r.line(quiet)
}

// blockedSources drops traffic whose source address has no business
// arriving on this interface. It sits after the state check, so a flow
// that is already up is not cut, and before everything that accepts, so
// no later rule can let a spoofed source in.
func (r *renderer) blockedSources(chain string) {
	private := r.interfacesBlocking(func(in model.Interface) bool { return in.BlockPrivate })
	bogons := r.interfacesBlocking(func(in model.Interface) bool { return in.BlockBogons })
	if len(private) == 0 && len(bogons) == 0 {
		return
	}
	def := r.cfg.System.Management.LogDefaultDrops

	emit := func(ifs []string, kind, what, set4, set6 string) {
		if len(ifs) == 0 {
			return
		}
		// Interfaces that log their drops log these too. The sampled log
		// takes only those and one drop takes them all, so one noisy WAN
		// does not make every other interface chatty.
		var loud, quiet []string
		for _, name := range ifs {
			in, _ := r.cfg.Interface(name)
			if in.LogsDrops(def) {
				loud = append(loud, name)
			} else {
				quiet = append(quiet, name)
			}
		}
		// Both base chains carry the same rules; the row is recorded once.
		if chain == "input" {
			row := SystemRule{
				Chain: chain, Action: "drop", Protocol: string(model.ProtocolAny),
				Source: what + " networks", Destination: "any",
				Description: "Block " + what + " sources, set on " + strings.Join(ifs, ", "), Log: len(quiet) == 0,
				Keys: []string{"input/" + kind, "forward/" + kind}, Setting: "interface",
			}
			if len(loud) > 0 {
				row.LogKeys = []string{"input/log:" + kind, "forward/log:" + kind}
			}
			r.sysFor(ifs, row)
		}
		for _, fam := range []struct {
			prefix string
			set    string
		}{{"ip", set4}, {"ip6", set6}} {
			if fam.set == "" {
				continue
			}
			match := fmt.Sprintf("%s saddr @%s", fam.prefix, fam.set)
			if len(loud) > 0 {
				r.line(sampledLog(match, ifnameSet(loud), fmt.Sprintf("ostiole:c:%s:%s: ", chain, kind), "log:"+kind))
			}
			r.line(fmt.Sprintf(`iifname %s %s counter drop comment "%s"`, ifnameSet(ifs), match, kind))
		}
	}
	emit(private, "block-private", "private and loopback", privateSetV4, privateSetV6)
	// Both families are always matched: the sets exist whether or not
	// today's list filled them, so a refresh needs no new rules.
	emit(bogons, "block-bogons", "bogon", bogonSetV4, bogonSetV6)
}

// interfacesBlocking lists the enabled interfaces that want a block.
func (r *renderer) interfacesBlocking(want func(model.Interface) bool) []string {
	var out []string
	for _, in := range r.cfg.Interfaces {
		if in.Enabled && want(in) {
			out = append(out, in.Name)
		}
	}
	return out
}

// ---- zone chains ---------------------------------------------------------

func (r *renderer) zoneChains() {
	for _, z := range r.cfg.Zones {
		r.block("chain zone_"+z.Name, func() {
			// The defence comes first: a flood should not be matched
			// against every rule in the zone before it is dropped.
			r.protectZone(z.Name)
			r.busyHosts(z)
			for i := range r.cfg.Rules {
				rule := &r.cfg.Rules[i]
				if rule.Zone != z.Name || !rule.Enabled {
					continue
				}
				r.rule(rule)
			}
			r.proxyAccess(z)
			r.forwardAccepts(z)
			// Everything nothing allowed arrives here, which is what a port
			// scan looks like from the router's side.
			r.scanTally(z.Name)
			// The tail counts what no rule matched. A zone that logs drops it
			// here; the rest hand it back to the base chain, which decides
			// per interface whether the drop is logged, so they only count.
			key := "zone-unmatched"
			var logKeys []string
			if z.LogDrops {
				key = "zone-default"
				logKeys = []string{"zone_" + z.Name + "/log:zone-default"}
				r.line(sampledLog("", "", fmt.Sprintf("ostiole:z:%s:drop: ", z.Name), "log:zone-default"))
				r.line(`counter drop comment "zone-default"`)
			} else {
				r.line(`counter comment "zone-unmatched"`)
			}
			r.sys(SystemRule{
				Chain: "zone_" + z.Name, After: true, Zones: []string{z.Name}, Action: "drop", Protocol: string(model.ProtocolAny),
				Source: "any", Destination: "any", Description: "Everything else", Log: r.zoneLogsDrops(z),
				Keys: []string{"zone_" + z.Name + "/" + key}, LogKeys: logKeys, Setting: "zone",
			})
		})
	}
}

// proxyAccess writes the zone's lines of the proxy's access list, in order,
// at the tail of the zone's chain: behind the zone's flood and scan defence,
// and behind the operator's rules, so a drop written above narrows them.
// Each goes through the rule renderer with this firewall and the ports it
// names as its destination, so a source alias, an inversion and logging
// work as they do on the Rules page.
func (r *renderer) proxyAccess(z model.Zone) {
	if !r.cfg.ProxyEnabled() || len(r.cfg.ZoneInterfaces(z.Name)) == 0 {
		return
	}
	for _, a := range r.cfg.Services.Proxy.Access {
		if !a.Enabled || a.Zone != z.Name {
			continue
		}
		tcp, udp := r.cfg.AccessPorts(a)
		if len(tcp) == 0 && len(udp) == 0 {
			r.line(fmt.Sprintf("# proxy access %s opens nothing: the routes it names are off", a.ID))
			continue
		}
		comment := "proxy:" + a.ID
		for _, l := range []struct {
			proto model.Protocol
			ports []uint16
		}{{model.ProtocolTCP, tcp}, {model.ProtocolUDP, udp}} {
			if len(l.ports) == 0 {
				continue
			}
			rule := model.Rule{
				ID: a.ID, Enabled: true, Zone: z.Name, Action: a.Action, Protocol: l.proto,
				Source:      model.Endpoint{Addresses: a.Source.Addresses, Alias: a.Source.Alias, Peer: a.Source.Peer, NotAddresses: a.Source.NotAddresses},
				Destination: model.Endpoint{Self: true, Ports: portList(l.ports)},
				Log:         a.Log,
			}
			r.ruleAs(&rule, comment, fmt.Sprintf("ostiole:p:%s:%s: ", a.ID, a.Action))
		}
		protocol := model.ProtocolTCP
		switch {
		case len(tcp) == 0:
			protocol = model.ProtocolUDP
		case len(udp) > 0:
			protocol = model.ProtocolTCPUDP
		}
		description := "Reverse proxy access"
		if a.Description != "" {
			description += ": " + a.Description
		}
		row := SystemRule{
			Chain: "zone_" + z.Name, After: true, Zones: []string{z.Name}, Action: string(a.Action),
			Protocol: string(protocol), Source: endpointText(a.Source), Destination: accessDest(tcp, udp),
			Description: description, Log: a.Log, Keys: []string{"zone_" + z.Name + "/" + comment},
			Setting: "proxy",
		}
		if a.Log && a.Action != model.ActionAccept {
			row.LogKeys = []string{"zone_" + z.Name + "/" + logComment(comment)}
		}
		r.sys(row)
	}
}

// portList writes ports as a rule names them.
func portList(ports []uint16) []string {
	out := make([]string, len(ports))
	for i, p := range ports {
		out[i] = strconv.Itoa(int(p))
	}
	return out
}

// accessDest is the destination text of an access line's row: the ports,
// and the UDP ones apart when they are not the same.
func accessDest(tcp, udp []uint16) string {
	switch {
	case len(tcp) == 0:
		return firewallDest(portList(udp))
	case len(udp) == 0 || slices.Equal(tcp, udp):
		return firewallDest(portList(tcp))
	}
	return firewallDest(portList(tcp)) + ", udp " + strings.Join(portList(udp), ", ")
}

// endpointText is how the Rules page writes an address match.
func endpointText(e model.Endpoint) string {
	who := "any"
	switch {
	case e.Alias != "":
		who = "@" + e.Alias
	case e.Peer != "":
		tunnel, peer, _ := strings.Cut(e.Peer, "/")
		who = peer + " on " + tunnel
	case len(e.Addresses) > 0:
		who = strings.Join(e.Addresses, ", ")
	}
	if e.NotAddresses {
		who = "not " + who
	}
	return who
}

// forwardAccepts pass what a port forward, a 1:1 mapping or a client's own
// UPnP mapping sent inside. They sit at the tail of the zone the traffic
// arrives from, behind the zone's flood and scan defence and the
// operator's rules, so a drop written there narrows a forward the way it
// narrows everything else. The zone chains serve input too; fib keeps the
// accept to forwarded traffic, so a forward to the router itself is still
// the zone's rules to allow.
func (r *renderer) forwardAccepts(z model.Zone) {
	if r.hasPortForwards() && slices.Contains(r.forwardedZones(), z.Name) {
		r.line(`ct status dnat fib daddr type != local counter accept comment "port-forwards"`)
		r.sys(SystemRule{
			Chain: "zone_" + z.Name, After: true, Zones: []string{z.Name}, Action: "accept",
			Protocol: string(model.ProtocolAny), Source: "any", Destination: "forwarded hosts",
			Description: "Traffic a port forward or 1:1 mapping sent inside",
			Keys:        []string{"zone_" + z.Name + "/port-forwards"}, Setting: "nat",
		})
	}
	if UPnPEnabled(r.cfg) && slices.Contains(r.zonesOf([]string{r.cfg.Services.UPnP.ExternalInterface}), z.Name) {
		r.line("jump " + UPnPForwardChain)
		r.sys(SystemRule{
			Chain: "zone_" + z.Name, After: true, Zones: []string{z.Name}, Action: "accept",
			Protocol: string(model.ProtocolAny), Source: "any", Destination: "mapped hosts",
			Description: "Ports opened by UPnP or NAT-PMP", Setting: "upnp",
		})
	}
}

// scheduleMatch turns a schedule into nftables meta matches. A window that
// ends before it starts runs over midnight, which nft cannot express as a
// range, so it is matched as "outside the daytime window" instead.
// Times are the firewall's local time: nft converts them to UTC when the
// ruleset is loaded, so a change of offset needs a reload. Days are not
// converted: the kernel matches them in an offset it keeps, which the
// engine sets to the clock's.
func scheduleMatch(sc model.Schedule) []string {
	var out []string
	if len(sc.Days) > 0 {
		days := make([]string, 0, len(sc.Days))
		for _, d := range sc.Days {
			if day, ok := model.Weekday(d); ok {
				days = append(days, fmt.Sprintf("%q", day))
			}
		}
		if len(days) > 0 {
			out = append(out, "meta day "+setOrSingle(days))
		}
	}
	start, serr := model.ParseClock(sc.Start)
	end, eerr := model.ParseClock(sc.End)
	switch {
	case serr != nil || eerr != nil || start == end:
	case start < end:
		out = append(out, fmt.Sprintf("meta hour %q-%q", model.Clock(start), model.Clock(end)))
	default:
		out = append(out, fmt.Sprintf("meta hour != %q-%q", model.Clock(end), model.Clock(start)))
	}
	return out
}

// famExpr is the address match for one endpoint. any means unconstrained;
// both is a family-agnostic expression (e.g. "fib daddr type local");
// otherwise v4/v6 hold per-family expressions and nil means the endpoint
// cannot match that family at all.
type famExpr struct {
	any    bool
	both   *string
	v4, v6 *string
}

// split reports whether the endpoint needs per-family rules.
func (f famExpr) split() bool { return !f.any && f.both == nil }

// expr returns the expression for family fam (4 or 6) and whether the
// endpoint can match that family.
func (f famExpr) expr(fam int) (string, bool) {
	switch {
	case f.any:
		return "", true
	case f.both != nil:
		return *f.both, true
	case fam == 4 && f.v4 != nil:
		return *f.v4, true
	case fam == 6 && f.v6 != nil:
		return *f.v6, true
	}
	return "", false
}

func (r *renderer) endpointAddr(dir string, e model.Endpoint) famExpr {
	op := " "
	if e.NotAddresses {
		op = " != "
	}
	if e.Self {
		s := "fib daddr type local"
		if e.NotAddresses {
			s = "fib daddr type != local"
		}
		return famExpr{both: &s}
	}
	if e.Alias != "" {
		a, _ := r.cfg.Alias(e.Alias)
		v4, v6 := splitFamilies(r.entriesOf(*a))
		var f famExpr
		if len(v4) > 0 || a.Fetched() {
			s := fmt.Sprintf("ip %s%s@%s", dir, op, aliasSet(a.Name, 4))
			f.v4 = &s
		}
		if len(v6) > 0 || a.Fetched() {
			s := fmt.Sprintf("ip6 %s%s@%s", dir, op, aliasSet(a.Name, 6))
			f.v6 = &s
		}
		return coverBothFamilies(f, e.NotAddresses)
	}
	addrs := e.Addresses
	pin := ""
	if e.Peer != "" {
		// A peer is the addresses it may use in its tunnel. One that is
		// gone, or has none, matches nothing rather than everything.
		in, p, ok := r.cfg.Peer(e.Peer)
		if !ok || len(p.AllowedIPs) == 0 {
			return famExpr{}
		}
		addrs = p.AllowedIPs
		// A peer that shows its network under another prefix has this
		// side's numbers, so it is told apart by its tunnel. Validation
		// keeps it from being inverted.
		if len(p.Theirs) > 0 {
			pin = fmt.Sprintf("oifname %q ", in.Name)
			if dir == "saddr" {
				pin = fmt.Sprintf("iifname %q ", in.Name)
			}
		}
	}
	if len(addrs) == 0 {
		return famExpr{any: true}
	}
	v4, v6 := splitFamilies(addrs)
	var f famExpr
	if len(v4) > 0 {
		s := fmt.Sprintf("%sip %s%s%s", pin, dir, op, setOrSingle(v4))
		f.v4 = &s
	}
	if len(v6) > 0 {
		s := fmt.Sprintf("%sip6 %s%s%s", pin, dir, op, setOrSingle(v6))
		f.v6 = &s
	}
	return coverBothFamilies(f, e.NotAddresses)
}

// coverBothFamilies fills in the family an inverted endpoint says nothing
// about. "Not in this IPv4 set" is true of every IPv6 packet, so the family
// the addresses do not name has to match in full rather than be left out:
// a v4-only "block everything except my country" rule that emitted no IPv6
// rule would let every IPv6 packet through, and say nothing about it.
//
// The filled-in side still names its family, because a rule with no address
// expression at all would match the other one too.
func coverBothFamilies(f famExpr, inverted bool) famExpr {
	if !inverted {
		return f
	}
	if f.v4 == nil && f.v6 != nil {
		s := "meta nfproto ipv4"
		f.v4 = &s
	}
	if f.v6 == nil && f.v4 != nil {
		s := "meta nfproto ipv6"
		f.v6 = &s
	}
	return f
}

// match is the part of a rule that selects packets, kept apart from the
// verdict so the filter chains and the policy routing chains can act on
// the same conditions.
type match struct {
	prefix   []string
	src, dst famExpr
	l4       string
}

// buildMatch renders a rule's conditions. It reports false when the rule
// cannot be expressed, having written a comment saying why. withDestZone
// is false in prerouting, where the outgoing interface is not known yet.
func (r *renderer) buildMatch(rule *model.Rule, withDestZone bool) (match, bool) {
	var m match
	if rule.Schedule != "" {
		sc, ok := r.cfg.Schedule(rule.Schedule)
		if !ok {
			r.line(fmt.Sprintf("# rule %s skipped: unknown schedule %q", rule.ID, rule.Schedule))
			return m, false
		}
		m.prefix = append(m.prefix, scheduleMatch(*sc)...)
	}
	if withDestZone && rule.DestZone != "" {
		ifs := r.cfg.ZoneInterfaces(rule.DestZone)
		if len(ifs) == 0 {
			r.line(fmt.Sprintf("# rule %s skipped: destination zone %q has no enabled interfaces", rule.ID, rule.DestZone))
			return m, false
		}
		m.prefix = append(m.prefix, "oifname "+ifnameSet(ifs))
	}
	m.src = r.endpointAddr("saddr", rule.Source)
	m.dst = r.endpointAddr("daddr", rule.Destination)
	m.l4 = r.l4(rule)
	return m, true
}

// emit writes the rule once, or once per address family when the two ends
// need different expressions.
func (r *renderer) emit(id string, m match, verdict []string) {
	one := func(addr ...string) {
		parts := append([]string{}, m.prefix...)
		for _, a := range addr {
			if a != "" {
				parts = append(parts, a)
			}
		}
		if m.l4 != "" {
			parts = append(parts, m.l4)
		}
		parts = append(parts, verdict...)
		r.line(strings.Join(parts, " "))
	}
	if !m.src.split() && !m.dst.split() {
		s, _ := m.src.expr(4)
		d, _ := m.dst.expr(4)
		one(s, d)
		return
	}
	emitted := false
	for _, fam := range []int{4, 6} {
		s, sok := m.src.expr(fam)
		d, dok := m.dst.expr(fam)
		if !sok || !dok {
			continue
		}
		one(s, d)
		emitted = true
	}
	if !emitted {
		r.line(fmt.Sprintf("# rule %s skipped: source and destination cannot match the same address family (empty alias, or IPv4 on one side and IPv6 on the other)", id))
	}
}

func (r *renderer) rule(rule *model.Rule) {
	r.ruleAs(rule, "id:"+rule.ID, fmt.Sprintf("ostiole:r:%s:%s: ", rule.ID, rule.Action))
}

// ruleAs writes a rule under the comment its counter is keyed by and the
// prefix it logs with, so a rule Ostiole writes from other settings, a line
// of the proxy's access list, matches the way one on the Rules page does.
func (r *renderer) ruleAs(rule *model.Rule, comment, prefix string) {
	m, ok := r.buildMatch(rule, true)
	if !ok {
		return
	}

	// A per-source limit is a rule of its own, and it has to come first:
	// it is what drops the excess before this rule accepts anything.
	r.ruleLimit(rule, m)

	// The action goes in the prefix because this is the only place it is
	// known for certain: the log rule and the verdict are rendered from the
	// same configuration. Reading it back out of the config when the entry
	// is served would answer for the rule as it stands now, not as it stood
	// when the packet arrived.
	//
	// A drop or reject sees every packet of a scan, so it logs through a
	// sampled rule of its own in front of it, as this firewall's own drops
	// do. One with a rate limit of its own keeps the log in the verdict:
	// the limit already bounds it, and a second bucket would not agree with
	// the first packet for packet. An accept sees only a connection's first
	// packet, the state rule taking the rest, so it logs every one.
	sampled := rule.Log && rule.Action != model.ActionAccept && len(limitExpr(rule.Limit)) == 0
	if sampled {
		r.emit(rule.ID, m, []string{sampledLog("", "", prefix, logComment(comment))})
	}
	verdict := append(limitExpr(rule.Limit), "counter")
	if rule.Log && !sampled {
		verdict = append(verdict, fmt.Sprintf("log prefix %q group %d", prefix, LogGroup))
	}
	// The tier goes in beside the verdict, which is the only place that
	// knows this rule is the one admitting the flow.
	verdict = append(verdict, shapeMark(rule.Priority)...)
	switch rule.Action {
	case model.ActionAccept:
		verdict = append(verdict, "accept")
	case model.ActionDrop:
		verdict = append(verdict, "drop")
	case model.ActionReject:
		r.reject(rule, m, verdict, comment)
		return
	}
	verdict = append(verdict, fmt.Sprintf("comment %q", comment))
	r.emit(rule.ID, m, verdict)
}

// A reject answers TCP with a reset, since some clients ignore ICMP while
// they connect, and anything else with administratively prohibited: icmpx,
// because the table is inet and a packet may be of either family.
const (
	rejectTCP   = "reject with tcp reset"
	rejectOther = "reject with icmpx type admin-prohibited"
)

// reject writes a reject rule's verdict. A rule that can match TCP and
// other protocols too is written twice under the one comment, the TCP half
// first, so its counter sums both.
func (r *renderer) reject(rule *model.Rule, m match, verdict []string, comment string) {
	tail := fmt.Sprintf("comment %q", comment)
	rest := m
	switch rule.Protocol {
	case model.ProtocolTCP:
		r.emit(rule.ID, m, slices.Concat(verdict, []string{rejectTCP, tail}))
		return
	case model.ProtocolTCPUDP:
		tcp, udp := *rule, *rule
		tcp.Protocol, udp.Protocol = model.ProtocolTCP, model.ProtocolUDP
		half := m
		half.l4 = r.l4(&tcp)
		r.emit(rule.ID, half, slices.Concat(verdict, []string{rejectTCP, tail}))
		rest.l4 = r.l4(&udp)
	case model.ProtocolAny:
		half := m
		half.l4 = "meta l4proto tcp"
		r.emit(rule.ID, half, slices.Concat(verdict, []string{rejectTCP, tail}))
	}
	r.emit(rule.ID, rest, slices.Concat(verdict, []string{rejectOther, tail}))
}

// logComment is the comment on a rule's sampled log, so its counter is
// keyed beside the rule's: "id:web-in" logs under "id:log:web-in", which
// the counters read as "log:web-in".
func logComment(comment string) string {
	if id, ok := strings.CutPrefix(comment, "id:"); ok {
		return "id:log:" + id
	}
	return "log:" + comment
}

// ---- policy routing --------------------------------------------------------

// policyChains mark traffic before the kernel decides where to send it, so
// rules that pick a gateway are routed through it. Nothing is rendered
// unless a rule asks for one.
func (r *renderer) policyChains() {
	zones := r.policyZones()
	if len(zones) == 0 {
		return
	}
	r.block("chain policy_prerouting", func() {
		r.line("type filter hook prerouting priority mangle; policy accept;")
		// An established flow keeps the gateway it started on: changing
		// lines halfway through would break the connection. Only this
		// feature's own byte counts: a flow that carries nothing but a
		// shaping tier was never policy routed and has to go on to the
		// zone chains like any other. The line a connection came in on
		// stays off: reply_prerouting puts it back on the answers alone.
		restore := "meta mark set ct mark"
		if len(r.cfg.ReplyLines()) > 0 {
			restore = fmt.Sprintf("meta mark set ct mark & 0x%08x", ^uint32(model.ReplyMarkMask))
		}
		r.line(fmt.Sprintf(`ct mark & 0x%08x != 0x0 %s counter accept comment "policy:established"`,
			model.PolicyMarkMask, restore))
		// Traffic addressed to the firewall itself is never policy routed.
		r.line(`fib daddr type local counter accept comment "policy:local"`)
		// Nor is traffic to a network a tunnel's peer shows under another
		// prefix: the tunnel's own mark takes it there.
		if shown := r.allTheirs(); len(shown) > 0 {
			r.line(fmt.Sprintf(`ip daddr %s counter accept comment "policy:translated"`, setOrSingle(shown)))
		}
		// Only a connection's first packet picks a gateway. A reply has
		// no mark of its own when its connection came in from outside, a
		// port forward's say, and marking it would send it out the rule's
		// gateway instead of back the way the connection came.
		for _, z := range zones {
			r.line(fmt.Sprintf("iifname %s ct state new jump policy_%s", ifnameSet(r.cfg.ZoneInterfaces(z)), z))
		}
	})
	for _, z := range zones {
		r.block("chain policy_"+z, func() { r.policyZoneRules(z) })
	}
}

// policyZones lists the zones that need a marking chain: those with an
// enabled rule that picks a gateway, and with somewhere for it to arrive.
func (r *renderer) policyZones() []string {
	var out []string
	for _, z := range r.cfg.Zones {
		if len(r.cfg.ZoneInterfaces(z.Name)) == 0 {
			continue
		}
		for i := range r.cfg.Rules {
			if rule := &r.cfg.Rules[i]; rule.Enabled && rule.Zone == z.Name && rule.Gateway != "" {
				out = append(out, z.Name)
				break
			}
		}
	}
	return out
}

// policyZoneRules mirrors the zone's filter rules up to the last one that
// picks a gateway. Rules without one are emitted as bare accepts: they end
// the chain in the filter path, so they have to end it here too, or a
// later rule would mark traffic the earlier one already decided.
func (r *renderer) policyZoneRules(zone string) {
	last := -1
	for i := range r.cfg.Rules {
		if rule := &r.cfg.Rules[i]; rule.Enabled && rule.Zone == zone && rule.Gateway != "" {
			last = i
		}
	}
	for i := 0; i <= last; i++ {
		rule := &r.cfg.Rules[i]
		if !rule.Enabled || rule.Zone != zone {
			continue
		}
		if rule.Gateway == "" && rule.DestZone != "" {
			// The exit interface is not known before the routing decision,
			// so this rule cannot stand in the way here.
			r.line(fmt.Sprintf("# rule %s not mirrored: it matches on the destination zone, which prerouting cannot see", rule.ID))
			continue
		}
		m, ok := r.buildMatch(rule, false)
		if !ok {
			continue
		}
		target, marked := r.cfg.PolicyTarget(rule.Gateway)
		switch {
		case rule.Gateway == "":
			r.emit(rule.ID, m, []string{"counter", "accept", fmt.Sprintf("comment %q", "no-policy:"+rule.ID)})
		case !marked:
			r.line(fmt.Sprintf("# rule %s: gateway %q is disabled, so its traffic follows the default route", rule.ID, rule.Gateway))
			r.emit(rule.ID, m, []string{"counter", "accept", fmt.Sprintf("comment %q", "no-policy:"+rule.ID)})
		default:
			// Only this feature's byte is written, on the packet and on the
			// connection: the rest of both belongs to whoever else marks.
			r.emit(rule.ID, m, []string{
				fmt.Sprintf("meta mark set meta mark & 0x%08x | 0x%x", ^uint32(model.PolicyMarkMask), target.Mark),
				fmt.Sprintf("ct mark set ct mark & 0x%08x | 0x%x", ^uint32(model.PolicyMarkMask), target.Mark),
				"counter", "accept",
				fmt.Sprintf("comment %q", "policy:"+rule.ID),
			})
		}
	}
}

// l4 renders the protocol and port match for a rule.
func (r *renderer) l4(rule *model.Rule) string {
	sport := r.ports("sport", rule.Source)
	dport := r.ports("dport", rule.Destination)
	switch rule.Protocol {
	case model.ProtocolTCP, model.ProtocolUDP:
		p := string(rule.Protocol)
		if sport == "" && dport == "" {
			return "meta l4proto " + p
		}
		return strings.TrimSpace(strings.Join([]string{portExpr(p, sport), portExpr(p, dport)}, " "))
	case model.ProtocolTCPUDP:
		if sport == "" && dport == "" {
			return "meta l4proto { tcp, udp }"
		}
		return strings.TrimSpace("meta l4proto { tcp, udp } " + strings.TrimSpace(portExpr("th", sport)+" "+portExpr("th", dport)))
	case model.ProtocolICMP:
		return "meta l4proto { icmp, ipv6-icmp }"
	}
	return ""
}

func portExpr(proto, expr string) string {
	if expr == "" {
		return ""
	}
	return proto + " " + expr
}

// ports renders "dport { … }" style operand for an endpoint, or "". An
// inverted endpoint matches every port but the ones named.
func (r *renderer) ports(kind string, e model.Endpoint) string {
	op := " "
	if e.NotPorts {
		op = " != "
	}
	if e.PortAlias != "" {
		a, _ := r.cfg.Alias(e.PortAlias)
		if len(r.entriesOf(*a)) == 0 && !a.Fetched() {
			return ""
		}
		return kind + op + "@" + aliasPortSet(a.Name)
	}
	if len(e.Ports) == 0 {
		return ""
	}
	ps := make([]string, 0, len(e.Ports))
	for _, p := range e.Ports {
		pr, _ := model.ParsePortRange(p)
		ps = append(ps, pr.String())
	}
	return kind + op + setOrSingle(ps)
}

// ---- NAT ------------------------------------------------------------------

// hasPortForwards reports whether anything gets DNATed, which is what the
// forward chain's "accept what NAT redirected" rule keys on.
func (r *renderer) hasPortForwards() bool {
	for _, pf := range r.cfg.NAT.PortForwards {
		if pf.Enabled && len(r.cfg.ZoneInterfaces(pf.Zone)) > 0 {
			return true
		}
	}
	for _, o := range r.cfg.NAT.OneToOne {
		if o.Enabled && len(r.cfg.ZoneInterfaces(o.Zone)) > 0 {
			return true
		}
	}
	return false
}

func (r *renderer) chainNATPrerouting() {
	r.block("chain nat_prerouting", func() {
		r.line("type nat hook prerouting priority dstnat; policy accept;")
		// First, so a UPnP mapping of port 80 cannot take a challenge.
		// Validation keeps port forwards off it.
		r.acmeRedirect()
		r.translateDNAT()
		for _, pf := range r.cfg.NAT.PortForwards {
			if !pf.Enabled {
				continue
			}
			ifs := r.cfg.ZoneInterfaces(pf.Zone)
			if len(ifs) == 0 {
				r.line(fmt.Sprintf("# port forward %s skipped: zone %q has no enabled interfaces", pf.ID, pf.Zone))
				continue
			}
			match := portMatch(pf.Protocol, pf.Ports)
			target, _ := model.ParseIP(pf.Target)
			// Only a connection's first packet is translated, which is
			// exactly the packet worth classifying.
			r.line(fmt.Sprintf("iifname %s %s counter %sdnat %s comment \"id:%s\"",
				ifnameSet(ifs), match, shapePrefix(pf.Priority), dnatTarget(target, pf.TargetPort), pf.ID))
			if pf.Reflection {
				r.reflectDNAT(pf, match, target)
			}
		}
		r.oneToOneDNAT()
		r.dnsRedirect()
		// Last, so a forward an admin wrote beats a mapping a client asked
		// for on the same port.
		if UPnPEnabled(r.cfg) {
			r.line("jump " + UPnPPreroutingChain)
		}
	})
}

// reflectDNAT forwards connections internal hosts make to the firewall's
// own outside address. The destination is any local address except the
// firewall's own internal ones, so reaching the web UI from the LAN keeps
// working even when a forward uses the same port.
func (r *renderer) reflectDNAT(pf model.PortForward, match string, target netip.Addr) {
	fam := 4
	if !target.Is4() {
		fam = 6
	}
	ifs := r.internalInterfaces()
	if len(ifs) == 0 {
		r.line(fmt.Sprintf("# reflection for %s skipped: no internal interfaces", pf.ID))
		return
	}
	var except string
	if own := r.internalAddresses(fam); len(own) > 0 {
		except = fmt.Sprintf("%s daddr != %s ", famPrefix(fam), setOrSingle(own))
	}
	r.line(fmt.Sprintf("iifname %s %sfib daddr type local %s counter %sdnat %s comment \"reflect:%s\"",
		ifnameSet(ifs), except, match, shapePrefix(pf.Priority), dnatTarget(target, pf.TargetPort), pf.ID))
}

// oneToOneDNAT maps each external address onto its internal host.
func (r *renderer) oneToOneDNAT() {
	for _, o := range r.cfg.NAT.OneToOne {
		if !o.Enabled {
			continue
		}
		ifs := r.cfg.ZoneInterfaces(o.Zone)
		if len(ifs) == 0 {
			r.line(fmt.Sprintf("# 1:1 nat %s skipped: zone %q has no enabled interfaces", o.ID, o.Zone))
			continue
		}
		ext, _ := model.ParseIP(o.External)
		in, _ := model.ParseIP(o.Internal)
		fam := 4
		if !ext.Is4() {
			fam = 6
		}
		r.line(fmt.Sprintf("iifname %s %s daddr %s counter dnat %s comment \"id:%s\"",
			ifnameSet(ifs), famPrefix(fam), ext, dnatTarget(in, ""), o.ID))
	}
}

// internalInterfaces lists enabled interfaces in zones that are not
// external, where reflected traffic comes from.
func (r *renderer) internalInterfaces() []string {
	var out []string
	for _, z := range r.cfg.Zones {
		if z.External {
			continue
		}
		out = append(out, r.cfg.ZoneInterfaces(z.Name)...)
	}
	return out
}

// internalPrefixes lists the firewall's own static addresses on internal
// interfaces, in the given family, each with its network's length.
func (r *renderer) internalPrefixes(fam int) []netip.Prefix {
	var out []netip.Prefix
	for _, in := range r.cfg.Interfaces {
		if !in.Enabled || in.Zone == "" {
			continue
		}
		if z, ok := r.cfg.Zone(in.Zone); !ok || z.External {
			continue
		}
		addr := in.IPv4.Address
		if fam == 6 {
			addr = in.IPv6.Address
		}
		if p, err := netip.ParsePrefix(addr); err == nil && (p.Addr().Is4() == (fam == 4)) {
			out = append(out, p)
		}
	}
	return out
}

// internalAddresses lists the firewall's own static addresses on internal
// interfaces, in the given family.
func (r *renderer) internalAddresses(fam int) []string {
	var out []string
	for _, p := range r.internalPrefixes(fam) {
		out = append(out, p.Addr().String())
	}
	return out
}

// internalNetworks lists the networks behind internal interfaces, which is
// who may be sent through the hairpin.
func (r *renderer) internalNetworks(fam int) []string {
	var out []string
	for _, p := range r.internalPrefixes(fam) {
		out = append(out, p.Masked().String())
	}
	return out
}

func famPrefix(fam int) string {
	if fam == 6 {
		return "ip6"
	}
	return "ip"
}

func dnatTarget(ip netip.Addr, port string) string {
	if ip.Is4() {
		if port == "" {
			return "ip to " + ip.String()
		}
		return fmt.Sprintf("ip to %s:%s", ip, port)
	}
	if port == "" {
		return "ip6 to " + ip.String()
	}
	return fmt.Sprintf("ip6 to [%s]:%s", ip, port)
}

func (r *renderer) chainNATPostrouting() {
	r.block("chain nat_postrouting", func() {
		r.line("type nat hook postrouting priority srcnat; policy accept;")
		// A NAT statement ends the chain, so the first rule to match
		// decides how a connection leaves. UPnP goes first, so the source
		// translation a mapping asks for is applied instead of the
		// masquerade everything else gets.
		if UPnPEnabled(r.cfg) {
			r.line("jump " + UPnPPostroutingChain)
		}
		r.oneToOneSNAT()
		r.translateSNAT()
		r.peerNAT()
		r.tunnelNAT()
		// The listed rules come first in hybrid mode, so a host can be
		// given its own address, or kept out of NAT, without anyone
		// writing out the rules for everything else.
		switch r.cfg.NAT.Outbound.Mode {
		case model.OutboundAutomatic:
			r.outboundAutomatic()
		case model.OutboundHybrid:
			r.outboundManual()
			r.outboundAutomatic()
		case model.OutboundManual:
			r.outboundManual()
		}
		r.reflectSNAT()
	})
}

// outboundAutomatic masquerades everything leaving an external zone.
// peerNAT puts this side behind a tunnel's own address for a peer set to
// Translate, so a far end that does not route this side's networks
// answers an address it knows. It is the peer's own setting, so it holds
// in every outbound mode, and it comes before the outbound rules, which
// would otherwise decide first.
func (r *renderer) peerNAT() {
	for _, in := range r.cfg.Interfaces {
		if !in.Enabled || in.WireGuard == nil {
			continue
		}
		for _, p := range in.WireGuard.Peers {
			if !p.Enabled || !p.Masquerade {
				continue
			}
			var nets []string
			for _, a := range p.AllowedIPs {
				if pre, err := model.ParseAddress(a); err == nil && pre.Bits() > 0 {
					nets = append(nets, pre.String())
				}
			}
			v4, v6 := splitFamilies(nets)
			key := "peer-nat:" + model.PeerRef(in.Name, p.Name)
			var dests []string
			for _, fam := range []struct {
				prefix, own string
				addrs       []string
			}{{"ip", in.IPv4.Address, v4}, {"ip6", in.IPv6.Address, v6}} {
				// With no address of its own in the family, the masquerade
				// would take another interface's; validation refuses that.
				if len(fam.addrs) == 0 || fam.own == "" {
					continue
				}
				r.line(fmt.Sprintf("oifname %s %s daddr %s counter masquerade comment %q",
					ifnameSet([]string{in.Name}), fam.prefix, setOrSingle(fam.addrs), key))
				dests = append(dests, fam.addrs...)
			}
			if len(dests) > 0 {
				r.nat = append(r.nat, SystemNAT{
					Zone: in.Zone, Interfaces: []string{in.Name}, Source: "any", Destination: strings.Join(dests, ", "),
					Keys: []string{"nat_postrouting/" + key},
				})
			}
		}
	}
}

func (r *renderer) outboundAutomatic() {
	ulas := r.tunnelULAs()
	for _, z := range r.cfg.Zones {
		if !z.External {
			continue
		}
		ifs := r.cfg.ZoneInterfaces(z.Name)
		if len(ifs) == 0 {
			continue
		}
		// IPv4 only: masquerading IPv6 would break end-to-end addressing.
		r.line(fmt.Sprintf("oifname %s meta nfproto ipv4 counter masquerade comment %q",
			ifnameSet(ifs), "auto-nat:"+z.Name))
		r.nat = append(r.nat, SystemNAT{
			Zone: z.Name, Interfaces: ifs, Source: "any IPv4", Destination: "anywhere",
			Keys: []string{"nat_postrouting/auto-nat:" + z.Name},
		})
		// Except a tunnel's unique local addresses, which cannot leave
		// untranslated: a device sent everything gets IPv6 through the
		// router as well.
		if len(ulas) > 0 {
			r.line(fmt.Sprintf("oifname %s ip6 saddr %s counter masquerade comment %q",
				ifnameSet(ifs), setOrSingle(ulas), "tunnel-v6:"+z.Name))
			r.nat = append(r.nat, SystemNAT{
				Zone: z.Name, Interfaces: ifs, Source: strings.Join(ulas, ", "), Destination: "anywhere",
				Keys: []string{"nat_postrouting/tunnel-v6:" + z.Name},
			})
		}
	}
}

// uniqueLocal is fc00::/7, the IPv6 addresses no router forwards on the
// internet.
var uniqueLocal = netip.MustParsePrefix("fc00::/7")

// tunnelULAs are the networks of the WireGuard tunnels' unique local IPv6
// addresses, of the tunnels devices dial into. One in an external zone is
// a way out, holding the one address its far end gave it.
func (r *renderer) tunnelULAs() []string {
	var out []string
	for _, in := range r.cfg.Interfaces {
		if !in.Enabled || in.WireGuard == nil || in.IPv6.Mode != model.AddrStatic {
			continue
		}
		if z, ok := r.cfg.Zone(in.Zone); ok && z.External {
			continue
		}
		if p, err := netip.ParsePrefix(in.IPv6.Address); err == nil && uniqueLocal.Contains(p.Addr()) {
			out = append(out, p.Masked().String())
		}
	}
	return out
}

// outboundManual writes the rules as configured, one line per address
// family the rule can match.
func (r *renderer) outboundManual() {
	for _, o := range r.cfg.NAT.Outbound.Rules {
		if !o.Enabled {
			continue
		}
		ifs := r.cfg.ZoneInterfaces(o.Zone)
		if len(ifs) == 0 {
			r.line(fmt.Sprintf("# outbound nat %s skipped: zone %q has no enabled interfaces", o.ID, o.Zone))
			continue
		}
		r.outboundRule(o, ifnameSet(ifs))
	}
}

func (r *renderer) outboundRule(o model.OutboundRule, ifs string) {
	comment := fmt.Sprintf("comment %q", "id:"+o.ID)
	// A rule that names an address translates to it; one that names none
	// masquerades, which follows whatever the interface has today. NoNAT
	// returns from the chain, leaving the traffic untranslated.
	verdict := "counter masquerade"
	family := 0
	switch {
	case o.NoNAT:
		verdict = "counter return"
	case o.Address != "":
		addr, err := model.ParseIP(o.Address)
		if err != nil {
			r.line(fmt.Sprintf("# outbound nat %s skipped: %v", o.ID, err))
			return
		}
		verdict = "counter snat " + snatTarget(addr)
		family = 4
		if !addr.Is4() {
			family = 6
		}
	}

	emit := func(fam int, match string) {
		parts := []string{"oifname " + ifs}
		if match != "" {
			parts = append(parts, match)
		} else if fam == 4 && !o.NoNAT && o.Address == "" {
			// Masquerading with no address match still has to say which
			// family it means, or it would catch IPv6 too.
			parts = append(parts, "meta nfproto ipv4")
		}
		parts = append(parts, verdict, comment)
		r.line(strings.Join(parts, " "))
	}

	src4, src6 := splitFamilies(o.Source)
	dst4, dst6 := splitFamilies(o.Destination)
	for _, fam := range []int{4, 6} {
		if family != 0 && fam != family {
			// Translating to an IPv4 address can only apply to IPv4.
			continue
		}
		src, dst := src4, dst4
		prefix := "ip"
		if fam == 6 {
			src, dst, prefix = src6, dst6, "ip6"
		}
		// A rule that names addresses in one family only does not apply to
		// the other.
		if len(o.Source) > 0 && len(src) == 0 {
			continue
		}
		if len(o.Destination) > 0 && len(dst) == 0 {
			continue
		}
		var match []string
		if len(src) > 0 {
			match = append(match, fmt.Sprintf("%s saddr %s", prefix, setOrSingle(src)))
		}
		if len(dst) > 0 {
			match = append(match, fmt.Sprintf("%s daddr %s", prefix, setOrSingle(dst)))
		}
		if len(match) == 0 {
			// Nothing to match on: one rule covers it, and for masquerade
			// that rule is IPv4 only.
			if fam == 6 && family == 0 && !o.NoNAT {
				continue
			}
			emit(fam, "")
			continue
		}
		emit(fam, strings.Join(match, " "))
	}
}

// oneToOneSNAT sends the mapped host out as its external address. It comes
// before outbound NAT, as binat does in pf, so the mapping beats the
// masquerade and the operator's rules alike.
func (r *renderer) oneToOneSNAT() {
	for _, o := range r.cfg.NAT.OneToOne {
		if !o.Enabled {
			continue
		}
		ifs := r.cfg.ZoneInterfaces(o.Zone)
		if len(ifs) == 0 {
			continue
		}
		ext, _ := model.ParseIP(o.External)
		in, _ := model.ParseIP(o.Internal)
		fam := 4
		if !ext.Is4() {
			fam = 6
		}
		r.line(fmt.Sprintf("oifname %s %s saddr %s counter snat %s comment \"id:%s\"",
			ifnameSet(ifs), famPrefix(fam), in, snatTarget(ext), o.ID))
	}
}

// reflectSNAT makes the reflected connection come back through the
// firewall: without it the server would answer the client directly and the
// client would drop the reply as unrelated.
func (r *renderer) reflectSNAT() {
	for _, pf := range r.cfg.NAT.PortForwards {
		if !pf.Enabled || !pf.Reflection {
			continue
		}
		target, err := model.ParseIP(pf.Target)
		if err != nil {
			continue
		}
		fam := 4
		if !target.Is4() {
			fam = 6
		}
		nets := r.internalNetworks(fam)
		if len(nets) == 0 {
			continue
		}
		ports := pf.Ports
		if pf.TargetPort != "" {
			ports = []string{pf.TargetPort}
		}
		r.line(fmt.Sprintf("%s saddr %s %s daddr %s %s counter masquerade comment \"reflect:%s\"",
			famPrefix(fam), setOrSingle(nets), famPrefix(fam), target, portMatch(pf.Protocol, ports), pf.ID))
	}
}

// portMatch renders the protocol and port part shared by NAT rules.
func portMatch(proto model.Protocol, ports []string) string {
	list := make([]string, 0, len(ports))
	for _, p := range ports {
		pr, _ := model.ParsePortRange(p)
		list = append(list, pr.String())
	}
	if proto == model.ProtocolTCPUDP {
		return "meta l4proto { tcp, udp } th dport " + setOrSingle(list)
	}
	return string(proto) + " dport " + setOrSingle(list)
}

func snatTarget(ip netip.Addr) string {
	if ip.Is4() {
		return "ip to " + ip.String()
	}
	return "ip6 to " + ip.String()
}

// ---- helpers ---------------------------------------------------------------

func ifnameSet(names []string) string {
	quoted := make([]string, 0, len(names))
	for _, n := range names {
		quoted = append(quoted, fmt.Sprintf("%q", n))
	}
	return setOrSingle(quoted)
}

func setOrSingle(items []string) string {
	if len(items) == 1 {
		return items[0]
	}
	return "{ " + strings.Join(items, ", ") + " }"
}

func sanitizeComment(s string) string {
	s = strings.NewReplacer(`"`, "'", "\n", " ", "\\", "/").Replace(s)
	if len(s) > 120 {
		s = s[:120]
	}
	return s
}
