// Package nft renders the Ostiole model to nftables text and drives the
// nft binary to validate, apply, and read back rulesets.
package nft

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"github.com/rforced/ostiole/internal/model"
)

// Table is the only nftables table Ostiole manages.
const Table = "inet ostiole"

// Header is the first line of every rendered ruleset.
const Header = "# Generated by ostiole. Do not edit; changes are overwritten on apply."

// LogGroup is the nflog group every log statement targets; the daemon's
// firewall log listener reads it. Nothing goes to the kernel log.
const LogGroup = 1

// Render converts a validated configuration into an nftables ruleset that
// atomically replaces the Ostiole table when loaded with `nft -f`.
func Render(cfg *model.Config) (string, error) { return RenderWithFeeds(cfg, nil) }

// RenderWithFeeds is Render with the contents of fetched aliases supplied
// separately: blocklists and country ranges live in a cache, not in the
// configuration, so a revision stays readable and a rollback does not
// carry half a million addresses with it.
func RenderWithFeeds(cfg *model.Config, feeds map[string][]string) (string, error) {
	out, err := Build(cfg, feeds)
	if err != nil {
		return "", err
	}
	return out.Ruleset, nil
}

// render writes the whole table.
func (r *renderer) render() {
	r.line(Header)
	r.line("table " + Table)
	r.line("delete table " + Table)
	r.line("table " + Table + " {")
	r.indent++
	r.sets()
	r.chainInput()
	r.chainForward()
	r.chainOutput()
	r.zoneChains()
	r.chainBlockDNS()
	r.policyChains()
	r.chainNATPrerouting()
	r.chainNATPostrouting()
	r.upnpChains()
	r.indent--
	r.line("}")
}

// EmptyRuleset removes the Ostiole table entirely, restoring the kernel to
// the state before Ostiole was installed (other tables are untouched).
func EmptyRuleset() string {
	return Header + "\n" + "table " + Table + "\n" + "delete table " + Table + "\n"
}

type renderer struct {
	cfg *model.Config
	// feeds holds the entries of aliases that are fetched rather than
	// written out.
	feeds  map[string][]string
	b      strings.Builder
	indent int
	// system collects the rules Ostiole adds on its own, recorded as they
	// are written.
	system []SystemRule
}

func (r *renderer) line(s string) {
	if s != "" {
		r.b.WriteString(strings.Repeat("\t", r.indent))
		r.b.WriteString(s)
	}
	r.b.WriteByte('\n')
}

func (r *renderer) block(open string, body func()) {
	r.line(open + " {")
	r.indent++
	body()
	r.indent--
	r.line("}")
}

// ---- sets ------------------------------------------------------------

func aliasSet(name string, family int) string {
	return fmt.Sprintf("alias_%s_v%d", name, family)
}

func aliasPortSet(name string) string {
	return "alias_" + name + "_ports"
}

// Sets Ostiole defines itself rather than from an alias.
const (
	privateSetV4 = "private_v4"
	privateSetV6 = "private_v6"
	bogonSetV4   = "bogons_v4"
	bogonSetV6   = "bogons_v6"
	// BogonFeed is the key the fetched bogon list is cached under. It is
	// not an alias: nobody writes it, and nothing references it by name.
	BogonFeed = "__bogons"
)

// splitFamilies partitions parsed addresses by IP family, preserving order.
func splitFamilies(addrs []string) (v4, v6 []string) {
	for _, a := range addrs {
		p, err := model.ParseAddress(a)
		if err != nil {
			continue // validated upstream
		}
		s := p.String()
		if p.Bits() == p.Addr().BitLen() {
			s = p.Addr().String()
		}
		if p.Addr().Is4() {
			v4 = append(v4, s)
		} else {
			v6 = append(v6, s)
		}
	}
	return v4, v6
}

// entriesOf is what an alias puts in its set: what is written in the
// configuration, or what was fetched for it. A country alias holds codes,
// never addresses, so only the fetched side counts.
func (r *renderer) entriesOf(a model.Alias) []string {
	if !a.Fetched() {
		return a.Entries
	}
	fetched := r.feeds[a.Name]
	if a.Type == model.AliasGeoIP {
		return fetched
	}
	return append(append([]string{}, a.Entries...), fetched...)
}

func (r *renderer) sets() {
	for _, a := range r.cfg.Aliases {
		for _, set := range AliasSets(a, r.entriesOf(a)) {
			r.set(set.Name, set.Type, set.Elements, a.Description)
		}
	}
	r.blockSets()
}

// blockSets defines the address sets the per-interface blocks match
// against: a fixed list for private and loopback, and a fetched one for
// the prefixes IANA has not allocated.
func (r *renderer) blockSets() {
	if len(r.interfacesBlocking(func(in model.Interface) bool { return in.BlockPrivate })) > 0 {
		v4, v6 := splitFamilies(model.PrivateSources)
		r.set(privateSetV4, "ipv4_addr", v4, "private and loopback addresses")
		r.set(privateSetV6, "ipv6_addr", v6, "unique local and loopback addresses")
	}
	if len(r.interfacesBlocking(func(in model.Interface) bool { return in.BlockBogons })) > 0 {
		v4, v6 := splitFamilies(r.feeds[BogonFeed])
		// Both sets exist whether or not today's list fills them, so a
		// refresh has somewhere to put tomorrow's.
		r.set(bogonSetV4, "ipv4_addr", v4, "prefixes IANA has not allocated")
		r.set(bogonSetV6, "ipv6_addr", v6, "prefixes IANA has not allocated")
	}
}

// BlockSets lists the sets the bogon list fills, so a refresh can replace
// their contents without rebuilding the ruleset.
func BlockSets(cfg *model.Config, entries []string) []Set {
	if !cfg.BlocksBogons() {
		return nil
	}
	v4, v6 := splitFamilies(entries)
	return []Set{
		{Name: bogonSetV4, Type: "ipv4_addr", Elements: v4},
		{Name: bogonSetV6, Type: "ipv6_addr", Elements: v6},
	}
}

// Set is one nftables set: its name and the elements it holds. It is
// exported so a refreshed blocklist can replace the elements without
// rebuilding the ruleset.
type Set struct {
	Name     string
	Type     string
	Elements []string
}

// AliasSets returns the sets an alias renders to, given its entries.
//
// An alias written out by hand only gets a set for a family it has
// entries in; one that is fetched always gets both, even when empty,
// because tomorrow's list may have addresses this one does not and the
// rules have to be pointing at somewhere to put them.
func AliasSets(a model.Alias, entries []string) []Set {
	always := a.Fetched()
	switch a.Type {
	case model.AliasPorts:
		if len(entries) == 0 && !always {
			return nil
		}
		ports := make([]string, 0, len(entries))
		for _, e := range entries {
			pr, err := model.ParsePortRange(e)
			if err != nil {
				continue
			}
			ports = append(ports, pr.String())
		}
		return []Set{{Name: aliasPortSet(a.Name), Type: "inet_service", Elements: ports}}
	default:
		v4, v6 := splitFamilies(entries)
		var out []Set
		if len(v4) > 0 || always {
			out = append(out, Set{Name: aliasSet(a.Name, 4), Type: "ipv4_addr", Elements: v4})
		}
		if len(v6) > 0 || always {
			out = append(out, Set{Name: aliasSet(a.Name, 6), Type: "ipv6_addr", Elements: v6})
		}
		return out
	}
}

func (r *renderer) set(name, typ string, elems []string, comment string) {
	r.block("set "+name, func() {
		r.line("type " + typ)
		r.line("flags interval")
		r.line("auto-merge")
		if comment != "" {
			r.line(fmt.Sprintf("comment %q", sanitizeComment(comment)))
		}
		if len(elems) > 0 {
			r.line("elements = { " + strings.Join(elems, ", ") + " }")
		}
	})
}

// ---- base chains -------------------------------------------------------

func (r *renderer) chainInput() {
	r.block("chain input", func() {
		r.line("type filter hook input priority filter; policy drop;")
		r.line(`iifname "lo" accept`)
		r.connectionState("input")
		r.linkLocalBaseline()
		r.blockedSources("input")
		r.antiLockout()
		r.serviceRules()
		r.zoneDispatch()
		r.defaultDrop("input")
	})
}

// linkLocalBaseline accepts what IP cannot work without, and it does so
// ahead of the source-address blocks on purpose. Neighbour discovery,
// router advertisements, and DHCPv6 answers all arrive from fe80::/10,
// and the fetched bogon list contains that prefix, so a WAN that blocks
// bogons would otherwise drop its gateway's neighbour solicitations and
// never get an IPv6 address or a default route.
//
// Nothing here lets a spoofed source in. Neighbour discovery is untracked
// by conntrack and the kernel discards it unless the hop limit is 255,
// so it cannot be routed in from off-link. An ICMP error is either
// related to a tracked flow, which the state rule accepted already, or
// invalid, which the state rule dropped already. Echo is deliberately
// absent: whether this firewall answers ping is a zone rule.
func (r *renderer) linkLocalBaseline() {
	// Error messages that IPv4 needs to function (no echo: that is a user rule).
	r.line("icmp type { destination-unreachable, time-exceeded, parameter-problem } accept")
	// Neighbour discovery, MLD, and error messages that IPv6 cannot work without.
	r.line("icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert, nd-router-solicit, nd-router-advert, " +
		"destination-unreachable, packet-too-big, time-exceeded, parameter-problem, " +
		"mld-listener-query, mld-listener-report, mld-listener-done } accept")
	r.sys(SystemRule{
		Chain: "input", Action: "accept", Protocol: string(model.ProtocolICMP),
		Source: "any", Destination: firewallDest(nil),
		Description: "ICMP errors and IPv6 neighbour discovery",
	})
	r.dhcpv6ClientRules()
}

// dhcpv6ClientRules let the answers to this router's own DHCPv6 requests
// in, on the interfaces that make them. The request goes to a multicast
// group and the answer comes back from the server's link-local address,
// so conntrack never pairs the two and the state rule sees no reply.
// The server is on the link by definition, which is what the link-local
// match on both ends says.
func (r *renderer) dhcpv6ClientRules() {
	var ifs []string
	for _, in := range r.cfg.Interfaces {
		if in.Enabled && in.DHCPv6Client() {
			ifs = append(ifs, in.Name)
		}
	}
	if len(ifs) == 0 {
		return
	}
	r.line(fmt.Sprintf(`iifname %s ip6 saddr fe80::/10 ip6 daddr fe80::/10 udp sport 547 udp dport 546 counter accept comment "client:dhcpv6"`,
		ifnameSet(ifs)))
	r.sysFor(ifs, SystemRule{
		Chain: "input", Action: "accept", Protocol: string(model.ProtocolUDP),
		Source: "link-local : 547", Destination: firewallDest([]string{"546"}),
		Description: "DHCPv6 answers to this firewall's own requests",
		Keys:        []string{"input/client:dhcpv6"}, Setting: "interface",
	})
}

// connectionState opens a base chain: replies to what was allowed pass,
// packets that belong to no connection do not. Both base chains carry the
// two rules; the rows are recorded once, from input.
func (r *renderer) connectionState(chain string) {
	r.line("ct state established,related accept")
	r.line("ct state invalid drop")
	if chain != "input" {
		return
	}
	r.sys(SystemRule{
		Chain: chain, Action: "accept", Protocol: string(model.ProtocolAny),
		Source: "any", Destination: "any",
		Description: "Replies and related traffic of connections already allowed",
	})
	r.sys(SystemRule{
		Chain: chain, Action: "drop", Protocol: string(model.ProtocolAny),
		Source: "any", Destination: "any",
		Description: "Packets that belong to no connection",
	})
}

// serviceRules lets DHCP and DNS clients reach the services this router runs,
// regardless of zone rules, on the interfaces that serve them.
func (r *renderer) serviceRules() {
	svc := r.cfg.Services
	if svc.DHCP.Enabled {
		var ifs []string
		for _, sc := range svc.DHCP.Servers {
			if in, ok := r.cfg.Interface(sc.Interface); ok && sc.Enabled && in.Enabled {
				ifs = append(ifs, sc.Interface)
			}
		}
		if len(ifs) > 0 {
			r.line(fmt.Sprintf(`iifname %s udp dport 67 counter accept comment "service:dhcp"`, ifnameSet(ifs)))
			r.sysFor(ifs, SystemRule{
				Chain: "input", Action: "accept", Protocol: string(model.ProtocolUDP),
				Source: "any", Destination: firewallDest([]string{"67"}),
				Description: "DHCP requests", Keys: []string{"input/service:dhcp"}, Setting: "dhcp",
			})
		}
		// Router advertisements need no rule (ICMPv6 is in the baseline and
		// output is open), but stateful and stateless DHCPv6 do.
		var v6 []string
		for _, sc := range svc.DHCP.V6 {
			if in, ok := r.cfg.Interface(sc.Interface); ok && sc.Enabled && in.Enabled && sc.Mode != model.RASLAAC {
				v6 = append(v6, sc.Interface)
			}
		}
		if len(v6) > 0 {
			r.line(fmt.Sprintf(`iifname %s udp dport 547 counter accept comment "service:dhcpv6"`, ifnameSet(v6)))
			r.sysFor(v6, SystemRule{
				Chain: "input", Action: "accept", Protocol: string(model.ProtocolUDP),
				Source: "any", Destination: firewallDest([]string{"547"}),
				Description: "DHCPv6 requests", Keys: []string{"input/service:dhcpv6"}, Setting: "dhcp",
			})
		}
	}
	if svc.DNS.Enabled {
		ifs := DNSInterfaces(r.cfg)
		if len(ifs) > 0 {
			r.line(fmt.Sprintf(`iifname %s meta l4proto { tcp, udp } th dport 53 fib daddr type local counter accept comment "service:dns"`, ifnameSet(ifs)))
			r.sysFor(ifs, SystemRule{
				Chain: "input", Action: "accept", Protocol: string(model.ProtocolTCPUDP),
				Source: "any", Destination: firewallDest([]string{"53"}),
				Description: "DNS queries to this firewall", Keys: []string{"input/service:dns"}, Setting: "dns",
			})
		}
	}
	r.wireguardRules()
	r.upnpRules()
}

// upnpRules let clients reach miniupnpd: SSDP discovery and the device
// description for IGD, and the NAT-PMP and PCP port for the other half.
// Unlike DNS there is no "fib daddr type local" here, because SSDP is
// addressed to a multicast group rather than to this router.
func (r *renderer) upnpRules() {
	if !UPnPEnabled(r.cfg) {
		return
	}
	ifs := UPnPInterfaces(r.cfg)
	if len(ifs) == 0 {
		return
	}
	u := r.cfg.Services.UPnP
	var udp []string
	if u.IGD {
		udp = append(udp, fmt.Sprint(ssdpPort))
	}
	if u.PCP {
		udp = append(udp, fmt.Sprint(pcpPort))
	}
	r.line(fmt.Sprintf(`iifname %s udp dport %s counter accept comment "service:upnp"`,
		ifnameSet(ifs), setOrSingle(udp)))
	ports, proto := udp, model.ProtocolUDP
	if u.IGD {
		r.line(fmt.Sprintf(`iifname %s tcp dport %d counter accept comment "service:upnp"`,
			ifnameSet(ifs), upnpHTTPPort))
		ports, proto = append(ports, fmt.Sprint(upnpHTTPPort)), model.ProtocolTCPUDP
	}
	r.sysFor(ifs, SystemRule{
		Chain: "input", Action: "accept", Protocol: string(proto),
		Source: "any", Destination: firewallDest(ports),
		Description: "UPnP and NAT-PMP requests", Keys: []string{"input/service:upnp"}, Setting: "upnp",
	})
}

// wireguardRules open the listening ports of tunnels on external zones,
// where peers dial in from. A tunnel nobody can reach is not a tunnel.
func (r *renderer) wireguardRules() {
	var ports []string
	seen := map[uint16]bool{}
	for _, in := range r.cfg.Interfaces {
		if in.WireGuard == nil || !in.Enabled || in.WireGuard.ListenPort == 0 || seen[in.WireGuard.ListenPort] {
			continue
		}
		seen[in.WireGuard.ListenPort] = true
		ports = append(ports, fmt.Sprint(in.WireGuard.ListenPort))
	}
	if len(ports) == 0 {
		return
	}
	var ifs []string
	for _, z := range r.cfg.Zones {
		if z.External {
			ifs = append(ifs, r.cfg.ZoneInterfaces(z.Name)...)
		}
	}
	if len(ifs) == 0 {
		return
	}
	r.line(fmt.Sprintf(`iifname %s udp dport %s counter accept comment "service:wireguard"`,
		ifnameSet(ifs), setOrSingle(ports)))
	r.sysFor(ifs, SystemRule{
		Chain: "input", Action: "accept", Protocol: string(model.ProtocolUDP),
		Source: "any", Destination: firewallDest(ports),
		Description: "WireGuard peers dialling in", Keys: []string{"input/service:wireguard"}, Setting: "wireguard",
	})
}

// DNSInterfaces lists where the DNS service listens: the configured list,
// or every enabled interface outside external zones.
func DNSInterfaces(cfg *model.Config) []string {
	if len(cfg.Services.DNS.Interfaces) > 0 {
		return cfg.Services.DNS.Interfaces
	}
	var ifs []string
	for _, in := range cfg.Interfaces {
		if !in.Enabled || in.Zone == "" {
			continue
		}
		if z, ok := cfg.Zone(in.Zone); ok && !z.External {
			ifs = append(ifs, in.Name)
		}
	}
	return ifs
}

// The chains miniupnpd is pointed at. It creates none of its own: its
// nftables backend inserts rules into chains it is given the names of,
// which is how Ostiole keeps every rule inside its own table. They are
// regular chains, so the family and hook come from whoever jumps to them.
const (
	UPnPPreroutingChain  = "upnp_prerouting"
	UPnPForwardChain     = "upnp_forward"
	UPnPPostroutingChain = "upnp_postrouting"
)

// Ports the mapping service answers on. upnpHTTPPort is where miniupnpd
// serves its device description; it is pfSense's choice, and it matches
// the http_port the services package configures.
const (
	ssdpPort     = 1900
	pcpPort      = 5351
	upnpHTTPPort = 2189
)

// UPnPEnabled reports whether the configuration wants miniupnpd. Enabled
// on its own does nothing: one of the two protocols has to answer.
func UPnPEnabled(cfg *model.Config) bool {
	u := cfg.Services.UPnP
	return u.Enabled && (u.IGD || u.PCP)
}

// UPnPInterfaces lists where clients may ask for a mapping: the configured
// list, or every enabled interface outside external zones, never the
// external interface itself.
func UPnPInterfaces(cfg *model.Config) []string {
	u := cfg.Services.UPnP
	if len(u.Interfaces) > 0 {
		return u.Interfaces
	}
	var ifs []string
	for _, in := range cfg.Interfaces {
		if !in.Enabled || in.Zone == "" || in.Name == u.ExternalInterface {
			continue
		}
		if z, ok := cfg.Zone(in.Zone); ok && !z.External {
			ifs = append(ifs, in.Name)
		}
	}
	return ifs
}

// upnpChains renders the three chains miniupnpd fills in, empty. They are
// rendered whether or not a mapping exists today: the daemon adds to a
// chain, it does not create one, and every apply rebuilds this table.
func (r *renderer) upnpChains() {
	if !UPnPEnabled(r.cfg) {
		return
	}
	for _, name := range []string{UPnPPreroutingChain, UPnPForwardChain, UPnPPostroutingChain} {
		r.block("chain "+name, func() {})
	}
}

func (r *renderer) chainForward() {
	r.block("chain forward", func() {
		r.line("type filter hook forward priority filter; policy drop;")
		r.connectionState("forward")
		r.blockedSources("forward")
		r.blockDNSJump()
		if r.hasPortForwards() {
			r.line(`ct status dnat counter accept comment "port-forwards"`)
			r.sys(SystemRule{
				Chain: "forward", Zones: r.forwardedZones(), Action: "accept", Protocol: string(model.ProtocolAny),
				Source: "any", Destination: "forwarded hosts",
				Description: "Traffic a port forward or 1:1 mapping sent inside",
				Keys:        []string{"forward/port-forwards"}, Setting: "nat",
			})
		}
		if UPnPEnabled(r.cfg) {
			r.line("jump " + UPnPForwardChain)
			r.sysFor([]string{r.cfg.Services.UPnP.ExternalInterface}, SystemRule{
				Chain: "forward", Action: "accept", Protocol: string(model.ProtocolAny),
				Source: "any", Destination: "mapped hosts",
				Description: "Ports opened by UPnP or NAT-PMP", Setting: "upnp",
			})
		}
		r.zoneDispatch()
		r.defaultDrop("forward")
	})
}

func (r *renderer) chainOutput() {
	r.block("chain output", func() {
		r.line("type filter hook output priority filter; policy accept;")
	})
}

func (r *renderer) antiLockout() {
	m := r.cfg.System.Management
	var ports []string
	if m.WebPort != 0 {
		ports = append(ports, fmt.Sprint(m.WebPort))
	}
	if m.SSHPort != 0 && m.SSHPort != m.WebPort {
		ports = append(ports, fmt.Sprint(m.SSHPort))
	}
	if len(ports) == 0 {
		return
	}
	for _, z := range r.cfg.Zones {
		if !z.AntiLockout {
			continue
		}
		ifs := r.cfg.ZoneInterfaces(z.Name)
		if len(ifs) == 0 {
			continue
		}
		r.line(fmt.Sprintf("iifname %s tcp dport %s counter accept comment \"anti-lockout:%s\"",
			ifnameSet(ifs), setOrSingle(ports), z.Name))
		r.sys(SystemRule{
			Chain: "input", Zones: []string{z.Name}, Action: "accept", Protocol: string(model.ProtocolTCP),
			Source: "any", Destination: firewallDest(ports),
			Description: "Anti-lockout, keeps the web UI and SSH reachable",
			Keys:        []string{"input/anti-lockout:" + z.Name}, Setting: "zone",
		})
	}
}

func (r *renderer) zoneDispatch() {
	for _, z := range r.cfg.Zones {
		ifs := r.cfg.ZoneInterfaces(z.Name)
		if len(ifs) == 0 {
			continue
		}
		r.line(fmt.Sprintf("iifname %s jump zone_%s", ifnameSet(ifs), z.Name))
	}
}

// defaultDrop ends a base chain. Every interface can decide for itself
// whether a packet dropped here is logged, so the common case stays one
// rule and only a router with an exception pays for two.
//
// The log line carries no interface name because it does not need one:
// the kernel tells the log listener which interface a packet arrived on.
func (r *renderer) defaultDrop(chain string) {
	logging := fmt.Sprintf(`counter log prefix "ostiole:%s:drop: " group %d comment "default-drop"`, chain, LogGroup)
	quiet := `counter comment "default-drop"`

	def := r.cfg.System.Management.LogDefaultDrops
	var exceptions []string
	for _, in := range r.cfg.Interfaces {
		if in.Enabled && in.LogDrops != nil && *in.LogDrops != def {
			exceptions = append(exceptions, in.Name)
		}
	}
	if len(exceptions) == 0 {
		if def {
			r.line(logging)
			return
		}
		r.line(quiet)
		return
	}

	// The exceptions get an explicit verdict so they stop here; everything
	// else, including traffic on an interface Ostiole knows nothing about,
	// falls through to the chain's own behaviour.
	if def {
		r.line(fmt.Sprintf(`iifname %s counter drop comment "default-drop:quiet"`, ifnameSet(exceptions)))
		r.line(logging)
		return
	}
	r.line(fmt.Sprintf(`iifname %s counter log prefix "ostiole:%s:drop: " group %d drop comment "default-drop:logged"`,
		ifnameSet(exceptions), chain, LogGroup))
	r.line(quiet)
}

// blockedSources drops traffic whose source address has no business
// arriving on this interface. It sits after the state check, so a flow
// that is already up is not cut, and before everything that accepts, so
// no later rule can let a spoofed source in.
func (r *renderer) blockedSources(chain string) {
	private := r.interfacesBlocking(func(in model.Interface) bool { return in.BlockPrivate })
	bogons := r.interfacesBlocking(func(in model.Interface) bool { return in.BlockBogons })
	if len(private) == 0 && len(bogons) == 0 {
		return
	}
	def := r.cfg.System.Management.LogDefaultDrops

	emit := func(ifs []string, kind, what, set4, set6 string) {
		if len(ifs) == 0 {
			return
		}
		// Interfaces that log their drops log these too; the rest are split
		// out so one noisy WAN does not make every other interface chatty.
		var loud, quiet []string
		for _, name := range ifs {
			in, _ := r.cfg.Interface(name)
			if in.LogsDrops(def) {
				loud = append(loud, name)
			} else {
				quiet = append(quiet, name)
			}
		}
		// Both base chains carry the same rules; the row is recorded once.
		if chain == "input" {
			r.sysFor(ifs, SystemRule{
				Chain: chain, Action: "drop", Protocol: string(model.ProtocolAny),
				Source: what + " networks", Destination: "any",
				Description: "Block " + what + " sources, set on " + strings.Join(ifs, ", "), Log: len(quiet) == 0,
				Keys: []string{"input/" + kind, "forward/" + kind}, Setting: "interface",
			})
		}
		for _, fam := range []struct {
			prefix string
			set    string
		}{{"ip", set4}, {"ip6", set6}} {
			if fam.set == "" {
				continue
			}
			if len(loud) > 0 {
				r.line(fmt.Sprintf(`iifname %s %s saddr @%s counter log prefix "ostiole:%s:%s: " group %d drop comment "%s"`,
					ifnameSet(loud), fam.prefix, fam.set, chain, kind, LogGroup, kind))
			}
			if len(quiet) > 0 {
				r.line(fmt.Sprintf(`iifname %s %s saddr @%s counter drop comment "%s"`,
					ifnameSet(quiet), fam.prefix, fam.set, kind))
			}
		}
	}
	emit(private, "block-private", "private and loopback", privateSetV4, privateSetV6)
	// Both families are always matched: the sets exist whether or not
	// today's list filled them, so a refresh needs no new rules.
	emit(bogons, "block-bogons", "bogon", bogonSetV4, bogonSetV6)
}

// interfacesBlocking lists the enabled interfaces that want a block.
func (r *renderer) interfacesBlocking(want func(model.Interface) bool) []string {
	var out []string
	for _, in := range r.cfg.Interfaces {
		if in.Enabled && want(in) {
			out = append(out, in.Name)
		}
	}
	return out
}

// ---- zone chains ---------------------------------------------------------

func (r *renderer) zoneChains() {
	for _, z := range r.cfg.Zones {
		r.block("chain zone_"+z.Name, func() {
			for i := range r.cfg.Rules {
				rule := &r.cfg.Rules[i]
				if rule.Zone != z.Name || !rule.Enabled {
					continue
				}
				r.rule(rule)
			}
			// The tail counts what no rule matched. A zone that logs drops it
			// here; the rest hand it back to the base chain, which decides
			// per interface whether the drop is logged, so they only count.
			key := "zone-unmatched"
			if z.LogDrops {
				key = "zone-default"
				r.line(fmt.Sprintf(`counter log prefix "ostiole:%s:drop: " group %d drop comment "zone-default"`, z.Name, LogGroup))
			} else {
				r.line(`counter comment "zone-unmatched"`)
			}
			r.sys(SystemRule{
				Chain: "zone_" + z.Name, After: true, Zones: []string{z.Name}, Action: "drop", Protocol: string(model.ProtocolAny),
				Source: "any", Destination: "any", Description: "Everything else", Log: r.zoneLogsDrops(z),
				Keys: []string{"zone_" + z.Name + "/" + key}, Setting: "zone",
			})
		})
	}
}

// scheduleMatch turns a schedule into nftables meta matches. A window that
// ends before it starts runs over midnight, which nft cannot express as a
// range, so it is matched as "outside the daytime window" instead.
// Times are the firewall's local time: nft converts them to UTC when the
// ruleset is loaded, so a change of offset needs a reload.
func scheduleMatch(sc model.Schedule) []string {
	var out []string
	if len(sc.Days) > 0 {
		days := make([]string, 0, len(sc.Days))
		for _, d := range sc.Days {
			if day, ok := model.Weekday(d); ok {
				days = append(days, fmt.Sprintf("%q", day))
			}
		}
		if len(days) > 0 {
			out = append(out, "meta day "+setOrSingle(days))
		}
	}
	start, serr := model.ParseClock(sc.Start)
	end, eerr := model.ParseClock(sc.End)
	switch {
	case serr != nil || eerr != nil || start == end:
	case start < end:
		out = append(out, fmt.Sprintf("meta hour %q-%q", model.Clock(start), model.Clock(end)))
	default:
		out = append(out, fmt.Sprintf("meta hour != %q-%q", model.Clock(end), model.Clock(start)))
	}
	return out
}

// famExpr is the address match for one endpoint. any means unconstrained;
// both is a family-agnostic expression (e.g. "fib daddr type local");
// otherwise v4/v6 hold per-family expressions and nil means the endpoint
// cannot match that family at all.
type famExpr struct {
	any    bool
	both   *string
	v4, v6 *string
}

// split reports whether the endpoint needs per-family rules.
func (f famExpr) split() bool { return !f.any && f.both == nil }

// expr returns the expression for family fam (4 or 6) and whether the
// endpoint can match that family.
func (f famExpr) expr(fam int) (string, bool) {
	switch {
	case f.any:
		return "", true
	case f.both != nil:
		return *f.both, true
	case fam == 4 && f.v4 != nil:
		return *f.v4, true
	case fam == 6 && f.v6 != nil:
		return *f.v6, true
	}
	return "", false
}

func (r *renderer) endpointAddr(dir string, e model.Endpoint) famExpr {
	op := " "
	if e.NotAddresses {
		op = " != "
	}
	if e.Self {
		s := "fib daddr type local"
		if e.NotAddresses {
			s = "fib daddr type != local"
		}
		return famExpr{both: &s}
	}
	if e.Alias != "" {
		a, _ := r.cfg.Alias(e.Alias)
		v4, v6 := splitFamilies(r.entriesOf(*a))
		var f famExpr
		if len(v4) > 0 || a.Fetched() {
			s := fmt.Sprintf("ip %s%s@%s", dir, op, aliasSet(a.Name, 4))
			f.v4 = &s
		}
		if len(v6) > 0 || a.Fetched() {
			s := fmt.Sprintf("ip6 %s%s@%s", dir, op, aliasSet(a.Name, 6))
			f.v6 = &s
		}
		return coverBothFamilies(f, e.NotAddresses)
	}
	if len(e.Addresses) == 0 {
		return famExpr{any: true}
	}
	v4, v6 := splitFamilies(e.Addresses)
	var f famExpr
	if len(v4) > 0 {
		s := fmt.Sprintf("ip %s%s%s", dir, op, setOrSingle(v4))
		f.v4 = &s
	}
	if len(v6) > 0 {
		s := fmt.Sprintf("ip6 %s%s%s", dir, op, setOrSingle(v6))
		f.v6 = &s
	}
	return coverBothFamilies(f, e.NotAddresses)
}

// coverBothFamilies fills in the family an inverted endpoint says nothing
// about. "Not in this IPv4 set" is true of every IPv6 packet, so the family
// the addresses do not name has to match in full rather than be left out:
// a v4-only "block everything except my country" rule that emitted no IPv6
// rule would let every IPv6 packet through, and say nothing about it.
//
// The filled-in side still names its family, because a rule with no address
// expression at all would match the other one too.
func coverBothFamilies(f famExpr, inverted bool) famExpr {
	if !inverted {
		return f
	}
	if f.v4 == nil && f.v6 != nil {
		s := "meta nfproto ipv4"
		f.v4 = &s
	}
	if f.v6 == nil && f.v4 != nil {
		s := "meta nfproto ipv6"
		f.v6 = &s
	}
	return f
}

// match is the part of a rule that selects packets, kept apart from the
// verdict so the filter chains and the policy routing chains can act on
// the same conditions.
type match struct {
	prefix   []string
	src, dst famExpr
	l4       string
}

// buildMatch renders a rule's conditions. It reports false when the rule
// cannot be expressed, having written a comment saying why. withDestZone
// is false in prerouting, where the outgoing interface is not known yet.
func (r *renderer) buildMatch(rule *model.Rule, withDestZone bool) (match, bool) {
	var m match
	if rule.Schedule != "" {
		sc, ok := r.cfg.Schedule(rule.Schedule)
		if !ok {
			r.line(fmt.Sprintf("# rule %s skipped: unknown schedule %q", rule.ID, rule.Schedule))
			return m, false
		}
		m.prefix = append(m.prefix, scheduleMatch(*sc)...)
	}
	if withDestZone && rule.DestZone != "" {
		ifs := r.cfg.ZoneInterfaces(rule.DestZone)
		if len(ifs) == 0 {
			r.line(fmt.Sprintf("# rule %s skipped: destination zone %q has no enabled interfaces", rule.ID, rule.DestZone))
			return m, false
		}
		m.prefix = append(m.prefix, "oifname "+ifnameSet(ifs))
	}
	m.src = r.endpointAddr("saddr", rule.Source)
	m.dst = r.endpointAddr("daddr", rule.Destination)
	m.l4 = r.l4(rule)
	return m, true
}

// emit writes the rule once, or once per address family when the two ends
// need different expressions.
func (r *renderer) emit(id string, m match, verdict []string) {
	one := func(addr ...string) {
		parts := append([]string{}, m.prefix...)
		for _, a := range addr {
			if a != "" {
				parts = append(parts, a)
			}
		}
		if m.l4 != "" {
			parts = append(parts, m.l4)
		}
		parts = append(parts, verdict...)
		r.line(strings.Join(parts, " "))
	}
	if !m.src.split() && !m.dst.split() {
		s, _ := m.src.expr(4)
		d, _ := m.dst.expr(4)
		one(s, d)
		return
	}
	emitted := false
	for _, fam := range []int{4, 6} {
		s, sok := m.src.expr(fam)
		d, dok := m.dst.expr(fam)
		if !sok || !dok {
			continue
		}
		one(s, d)
		emitted = true
	}
	if !emitted {
		r.line(fmt.Sprintf("# rule %s skipped: source and destination cannot match the same address family (empty alias, or IPv4 on one side and IPv6 on the other)", id))
	}
}

func (r *renderer) rule(rule *model.Rule) {
	m, ok := r.buildMatch(rule, true)
	if !ok {
		return
	}

	verdict := []string{"counter"}
	if rule.Log {
		verdict = append(verdict, fmt.Sprintf("log prefix \"ostiole:%s: \" group %d", rule.ID, LogGroup))
	}
	switch rule.Action {
	case model.ActionAccept:
		verdict = append(verdict, "accept")
	case model.ActionDrop:
		verdict = append(verdict, "drop")
	case model.ActionReject:
		if rule.Protocol == model.ProtocolTCP {
			verdict = append(verdict, "reject with tcp reset")
		} else {
			verdict = append(verdict, "reject")
		}
	}
	verdict = append(verdict, fmt.Sprintf("comment \"id:%s\"", rule.ID))
	r.emit(rule.ID, m, verdict)
}

// ---- policy routing --------------------------------------------------------

// policyChains mark traffic before the kernel decides where to send it, so
// rules that pick a gateway are routed through it. Nothing is rendered
// unless a rule asks for one.
func (r *renderer) policyChains() {
	zones := r.policyZones()
	if len(zones) == 0 {
		return
	}
	r.block("chain policy_prerouting", func() {
		r.line("type filter hook prerouting priority mangle; policy accept;")
		// An established flow keeps the gateway it started on: changing
		// lines halfway through would break the connection.
		r.line(`ct mark != 0x0 meta mark set ct mark counter accept comment "policy:established"`)
		// Traffic addressed to the firewall itself is never policy routed.
		r.line(`fib daddr type local counter accept comment "policy:local"`)
		for _, z := range zones {
			r.line(fmt.Sprintf("iifname %s jump policy_%s", ifnameSet(r.cfg.ZoneInterfaces(z)), z))
		}
	})
	for _, z := range zones {
		r.block("chain policy_"+z, func() { r.policyZoneRules(z) })
	}
}

// policyZones lists the zones that need a marking chain: those with an
// enabled rule that picks a gateway, and with somewhere for it to arrive.
func (r *renderer) policyZones() []string {
	var out []string
	for _, z := range r.cfg.Zones {
		if len(r.cfg.ZoneInterfaces(z.Name)) == 0 {
			continue
		}
		for i := range r.cfg.Rules {
			if rule := &r.cfg.Rules[i]; rule.Enabled && rule.Zone == z.Name && rule.Gateway != "" {
				out = append(out, z.Name)
				break
			}
		}
	}
	return out
}

// policyZoneRules mirrors the zone's filter rules up to the last one that
// picks a gateway. Rules without one are emitted as bare accepts: they end
// the chain in the filter path, so they have to end it here too, or a
// later rule would mark traffic the earlier one already decided.
func (r *renderer) policyZoneRules(zone string) {
	last := -1
	for i := range r.cfg.Rules {
		if rule := &r.cfg.Rules[i]; rule.Enabled && rule.Zone == zone && rule.Gateway != "" {
			last = i
		}
	}
	for i := 0; i <= last; i++ {
		rule := &r.cfg.Rules[i]
		if !rule.Enabled || rule.Zone != zone {
			continue
		}
		if rule.Gateway == "" && rule.DestZone != "" {
			// The exit interface is not known before the routing decision,
			// so this rule cannot stand in the way here.
			r.line(fmt.Sprintf("# rule %s not mirrored: it matches on the destination zone, which prerouting cannot see", rule.ID))
			continue
		}
		m, ok := r.buildMatch(rule, false)
		if !ok {
			continue
		}
		target, marked := r.cfg.PolicyTarget(rule.Gateway)
		switch {
		case rule.Gateway == "":
			r.emit(rule.ID, m, []string{"counter", "accept", fmt.Sprintf("comment %q", "no-policy:"+rule.ID)})
		case !marked:
			r.line(fmt.Sprintf("# rule %s: gateway %q is disabled, so its traffic follows the default route", rule.ID, rule.Gateway))
			r.emit(rule.ID, m, []string{"counter", "accept", fmt.Sprintf("comment %q", "no-policy:"+rule.ID)})
		default:
			r.emit(rule.ID, m, []string{
				fmt.Sprintf("meta mark set 0x%x", target.Mark),
				"ct mark set meta mark",
				"counter", "accept",
				fmt.Sprintf("comment %q", "policy:"+rule.ID),
			})
		}
	}
}

// l4 renders the protocol and port match for a rule.
func (r *renderer) l4(rule *model.Rule) string {
	sport := r.ports("sport", rule.Source)
	dport := r.ports("dport", rule.Destination)
	switch rule.Protocol {
	case model.ProtocolTCP, model.ProtocolUDP:
		p := string(rule.Protocol)
		if sport == "" && dport == "" {
			return "meta l4proto " + p
		}
		return strings.TrimSpace(strings.Join([]string{portExpr(p, sport), portExpr(p, dport)}, " "))
	case model.ProtocolTCPUDP:
		if sport == "" && dport == "" {
			return "meta l4proto { tcp, udp }"
		}
		return strings.TrimSpace("meta l4proto { tcp, udp } " + strings.TrimSpace(portExpr("th", sport)+" "+portExpr("th", dport)))
	case model.ProtocolICMP:
		return "meta l4proto { icmp, ipv6-icmp }"
	}
	return ""
}

func portExpr(proto, expr string) string {
	if expr == "" {
		return ""
	}
	return proto + " " + expr
}

// ports renders "dport { … }" style operand for an endpoint, or "". An
// inverted endpoint matches every port but the ones named.
func (r *renderer) ports(kind string, e model.Endpoint) string {
	op := " "
	if e.NotPorts {
		op = " != "
	}
	if e.PortAlias != "" {
		a, _ := r.cfg.Alias(e.PortAlias)
		if len(r.entriesOf(*a)) == 0 && !a.Fetched() {
			return ""
		}
		return kind + op + "@" + aliasPortSet(a.Name)
	}
	if len(e.Ports) == 0 {
		return ""
	}
	ps := make([]string, 0, len(e.Ports))
	for _, p := range e.Ports {
		pr, _ := model.ParsePortRange(p)
		ps = append(ps, pr.String())
	}
	return kind + op + setOrSingle(ps)
}

// ---- NAT ------------------------------------------------------------------

// hasPortForwards reports whether anything gets DNATed, which is what the
// forward chain's "accept what NAT redirected" rule keys on.
func (r *renderer) hasPortForwards() bool {
	for _, pf := range r.cfg.NAT.PortForwards {
		if pf.Enabled && len(r.cfg.ZoneInterfaces(pf.Zone)) > 0 {
			return true
		}
	}
	for _, o := range r.cfg.NAT.OneToOne {
		if o.Enabled && len(r.cfg.ZoneInterfaces(o.Zone)) > 0 {
			return true
		}
	}
	return false
}

func (r *renderer) chainNATPrerouting() {
	r.block("chain nat_prerouting", func() {
		r.line("type nat hook prerouting priority dstnat; policy accept;")
		for _, pf := range r.cfg.NAT.PortForwards {
			if !pf.Enabled {
				continue
			}
			ifs := r.cfg.ZoneInterfaces(pf.Zone)
			if len(ifs) == 0 {
				r.line(fmt.Sprintf("# port forward %s skipped: zone %q has no enabled interfaces", pf.ID, pf.Zone))
				continue
			}
			match := portMatch(pf.Protocol, pf.Ports)
			target, _ := model.ParseIP(pf.Target)
			r.line(fmt.Sprintf("iifname %s %s counter dnat %s comment \"id:%s\"",
				ifnameSet(ifs), match, dnatTarget(target, pf.TargetPort), pf.ID))
			if pf.Reflection {
				r.reflectDNAT(pf, match, target)
			}
		}
		r.oneToOneDNAT()
		r.dnsRedirect()
		// Last, so a forward an admin wrote beats a mapping a client asked
		// for on the same port.
		if UPnPEnabled(r.cfg) {
			r.line("jump " + UPnPPreroutingChain)
		}
	})
}

// reflectDNAT forwards connections internal hosts make to the firewall's
// own outside address. The destination is any local address except the
// firewall's own internal ones, so reaching the web UI from the LAN keeps
// working even when a forward uses the same port.
func (r *renderer) reflectDNAT(pf model.PortForward, match string, target netip.Addr) {
	fam := 4
	if !target.Is4() {
		fam = 6
	}
	ifs := r.internalInterfaces()
	if len(ifs) == 0 {
		r.line(fmt.Sprintf("# reflection for %s skipped: no internal interfaces", pf.ID))
		return
	}
	var except string
	if own := r.internalAddresses(fam); len(own) > 0 {
		except = fmt.Sprintf("%s daddr != %s ", famPrefix(fam), setOrSingle(own))
	}
	r.line(fmt.Sprintf("iifname %s %sfib daddr type local %s counter dnat %s comment \"reflect:%s\"",
		ifnameSet(ifs), except, match, dnatTarget(target, pf.TargetPort), pf.ID))
}

// oneToOneDNAT maps each external address onto its internal host.
func (r *renderer) oneToOneDNAT() {
	for _, o := range r.cfg.NAT.OneToOne {
		if !o.Enabled {
			continue
		}
		ifs := r.cfg.ZoneInterfaces(o.Zone)
		if len(ifs) == 0 {
			r.line(fmt.Sprintf("# 1:1 nat %s skipped: zone %q has no enabled interfaces", o.ID, o.Zone))
			continue
		}
		ext, _ := model.ParseIP(o.External)
		in, _ := model.ParseIP(o.Internal)
		fam := 4
		if !ext.Is4() {
			fam = 6
		}
		r.line(fmt.Sprintf("iifname %s %s daddr %s counter dnat %s comment \"id:%s\"",
			ifnameSet(ifs), famPrefix(fam), ext, dnatTarget(in, ""), o.ID))
	}
}

// internalInterfaces lists enabled interfaces in zones that are not
// external, where reflected traffic comes from.
func (r *renderer) internalInterfaces() []string {
	var out []string
	for _, z := range r.cfg.Zones {
		if z.External {
			continue
		}
		out = append(out, r.cfg.ZoneInterfaces(z.Name)...)
	}
	return out
}

// internalAddresses lists the firewall's own static addresses on internal
// interfaces, in the given family.
func (r *renderer) internalAddresses(fam int) []string {
	var out []string
	for _, in := range r.cfg.Interfaces {
		if !in.Enabled || in.Zone == "" {
			continue
		}
		if z, ok := r.cfg.Zone(in.Zone); !ok || z.External {
			continue
		}
		addr := in.IPv4.Address
		if fam == 6 {
			addr = in.IPv6.Address
		}
		if p, err := netip.ParsePrefix(addr); err == nil && (p.Addr().Is4() == (fam == 4)) {
			out = append(out, p.Addr().String())
		}
	}
	return out
}

// internalNetworks lists the networks behind internal interfaces, which is
// who may be sent through the hairpin.
func (r *renderer) internalNetworks(fam int) []string {
	var out []string
	for _, in := range r.cfg.Interfaces {
		if !in.Enabled || in.Zone == "" {
			continue
		}
		if z, ok := r.cfg.Zone(in.Zone); !ok || z.External {
			continue
		}
		addr := in.IPv4.Address
		if fam == 6 {
			addr = in.IPv6.Address
		}
		if p, err := netip.ParsePrefix(addr); err == nil && (p.Addr().Is4() == (fam == 4)) {
			out = append(out, p.Masked().String())
		}
	}
	return out
}

func famPrefix(fam int) string {
	if fam == 6 {
		return "ip6"
	}
	return "ip"
}

func dnatTarget(ip netip.Addr, port string) string {
	if ip.Is4() {
		if port == "" {
			return "ip to " + ip.String()
		}
		return fmt.Sprintf("ip to %s:%s", ip, port)
	}
	if port == "" {
		return "ip6 to " + ip.String()
	}
	return fmt.Sprintf("ip6 to [%s]:%s", ip, port)
}

func (r *renderer) chainNATPostrouting() {
	r.block("chain nat_postrouting", func() {
		r.line("type nat hook postrouting priority srcnat; policy accept;")
		// First, so the source translation a mapping asks for is applied
		// instead of the masquerade everything else gets.
		if UPnPEnabled(r.cfg) {
			r.line("jump " + UPnPPostroutingChain)
		}
		// The listed rules come first in hybrid mode, so a host can be
		// given its own address, or kept out of NAT, without anyone
		// writing out the rules for everything else.
		switch r.cfg.NAT.Outbound.Mode {
		case model.OutboundAutomatic:
			r.outboundAutomatic()
		case model.OutboundHybrid:
			r.outboundManual()
			r.outboundAutomatic()
		case model.OutboundManual:
			r.outboundManual()
		}
		r.oneToOneSNAT()
		r.reflectSNAT()
	})
}

// outboundAutomatic masquerades everything leaving an external zone.
func (r *renderer) outboundAutomatic() {
	for _, z := range r.cfg.Zones {
		if !z.External {
			continue
		}
		ifs := r.cfg.ZoneInterfaces(z.Name)
		if len(ifs) == 0 {
			continue
		}
		// IPv4 only: masquerading IPv6 would break end-to-end addressing.
		r.line(fmt.Sprintf("oifname %s meta nfproto ipv4 counter masquerade comment %q",
			ifnameSet(ifs), "auto-nat:"+z.Name))
	}
}

// outboundManual writes the rules as configured, one line per address
// family the rule can match.
func (r *renderer) outboundManual() {
	for _, o := range r.cfg.NAT.Outbound.Rules {
		if !o.Enabled {
			continue
		}
		ifs := r.cfg.ZoneInterfaces(o.Zone)
		if len(ifs) == 0 {
			r.line(fmt.Sprintf("# outbound nat %s skipped: zone %q has no enabled interfaces", o.ID, o.Zone))
			continue
		}
		r.outboundRule(o, ifnameSet(ifs))
	}
}

func (r *renderer) outboundRule(o model.OutboundRule, ifs string) {
	comment := fmt.Sprintf("comment %q", "id:"+o.ID)
	// A rule that names an address translates to it; one that names none
	// masquerades, which follows whatever the interface has today. NoNAT
	// returns from the chain, leaving the traffic untranslated.
	verdict := "counter masquerade"
	family := 0
	switch {
	case o.NoNAT:
		verdict = "counter return"
	case o.Address != "":
		addr, err := model.ParseIP(o.Address)
		if err != nil {
			r.line(fmt.Sprintf("# outbound nat %s skipped: %v", o.ID, err))
			return
		}
		verdict = "counter snat " + snatTarget(addr)
		family = 4
		if !addr.Is4() {
			family = 6
		}
	}

	emit := func(fam int, match string) {
		parts := []string{"oifname " + ifs}
		if match != "" {
			parts = append(parts, match)
		} else if fam == 4 && !o.NoNAT && o.Address == "" {
			// Masquerading with no address match still has to say which
			// family it means, or it would catch IPv6 too.
			parts = append(parts, "meta nfproto ipv4")
		}
		parts = append(parts, verdict, comment)
		r.line(strings.Join(parts, " "))
	}

	src4, src6 := splitFamilies(o.Source)
	dst4, dst6 := splitFamilies(o.Destination)
	for _, fam := range []int{4, 6} {
		if family != 0 && fam != family {
			// Translating to an IPv4 address can only apply to IPv4.
			continue
		}
		src, dst := src4, dst4
		prefix := "ip"
		if fam == 6 {
			src, dst, prefix = src6, dst6, "ip6"
		}
		// A rule that names addresses in one family only does not apply to
		// the other.
		if len(o.Source) > 0 && len(src) == 0 {
			continue
		}
		if len(o.Destination) > 0 && len(dst) == 0 {
			continue
		}
		var match []string
		if len(src) > 0 {
			match = append(match, fmt.Sprintf("%s saddr %s", prefix, setOrSingle(src)))
		}
		if len(dst) > 0 {
			match = append(match, fmt.Sprintf("%s daddr %s", prefix, setOrSingle(dst)))
		}
		if len(match) == 0 {
			// Nothing to match on: one rule covers it, and for masquerade
			// that rule is IPv4 only.
			if fam == 6 && family == 0 && !o.NoNAT {
				continue
			}
			emit(fam, "")
			continue
		}
		emit(fam, strings.Join(match, " "))
	}
}

// oneToOneSNAT sends the mapped host out as its external address. It comes
// after outbound NAT so the explicit mapping wins over a masquerade.
func (r *renderer) oneToOneSNAT() {
	for _, o := range r.cfg.NAT.OneToOne {
		if !o.Enabled {
			continue
		}
		ifs := r.cfg.ZoneInterfaces(o.Zone)
		if len(ifs) == 0 {
			continue
		}
		ext, _ := model.ParseIP(o.External)
		in, _ := model.ParseIP(o.Internal)
		fam := 4
		if !ext.Is4() {
			fam = 6
		}
		r.line(fmt.Sprintf("oifname %s %s saddr %s counter snat %s comment \"id:%s\"",
			ifnameSet(ifs), famPrefix(fam), in, snatTarget(ext), o.ID))
	}
}

// reflectSNAT makes the reflected connection come back through the
// firewall: without it the server would answer the client directly and the
// client would drop the reply as unrelated.
func (r *renderer) reflectSNAT() {
	for _, pf := range r.cfg.NAT.PortForwards {
		if !pf.Enabled || !pf.Reflection {
			continue
		}
		target, err := model.ParseIP(pf.Target)
		if err != nil {
			continue
		}
		fam := 4
		if !target.Is4() {
			fam = 6
		}
		nets := r.internalNetworks(fam)
		if len(nets) == 0 {
			continue
		}
		ports := pf.Ports
		if pf.TargetPort != "" {
			ports = []string{pf.TargetPort}
		}
		r.line(fmt.Sprintf("%s saddr %s %s daddr %s %s counter masquerade comment \"reflect:%s\"",
			famPrefix(fam), setOrSingle(nets), famPrefix(fam), target, portMatch(pf.Protocol, ports), pf.ID))
	}
}

// portMatch renders the protocol and port part shared by NAT rules.
func portMatch(proto model.Protocol, ports []string) string {
	list := make([]string, 0, len(ports))
	for _, p := range ports {
		pr, _ := model.ParsePortRange(p)
		list = append(list, pr.String())
	}
	if proto == model.ProtocolTCPUDP {
		return "meta l4proto { tcp, udp } th dport " + setOrSingle(list)
	}
	return string(proto) + " dport " + setOrSingle(list)
}

func snatTarget(ip netip.Addr) string {
	if ip.Is4() {
		return "ip to " + ip.String()
	}
	return "ip6 to " + ip.String()
}

// ---- helpers ---------------------------------------------------------------

func ifnameSet(names []string) string {
	quoted := make([]string, 0, len(names))
	for _, n := range names {
		quoted = append(quoted, fmt.Sprintf("%q", n))
	}
	return setOrSingle(quoted)
}

func setOrSingle(items []string) string {
	if len(items) == 1 {
		return items[0]
	}
	return "{ " + strings.Join(items, ", ") + " }"
}

func sanitizeComment(s string) string {
	s = strings.NewReplacer(`"`, "'", "\n", " ", "\\", "/").Replace(s)
	if len(s) > 120 {
		s = s[:120]
	}
	return s
}

// SortedZoneNames is a helper for callers that want deterministic zone order
// independent of configuration order.
func SortedZoneNames(cfg *model.Config) []string {
	names := make([]string, 0, len(cfg.Zones))
	for _, z := range cfg.Zones {
		names = append(names, z.Name)
	}
	sort.Strings(names)
	return names
}
