// Package nft renders the Ostiole model to nftables text and drives the
// nft binary to validate, apply, and read back rulesets.
package nft

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"github.com/rforced/ostiole/internal/model"
)

// Table is the only nftables table Ostiole manages.
const Table = "inet ostiole"

// Header is the first line of every rendered ruleset.
const Header = "# Generated by ostiole. Do not edit; changes are overwritten on apply."

// LogGroup is the nflog group every log statement targets; the daemon's
// firewall log listener reads it. Nothing goes to the kernel log.
const LogGroup = 1

// Render converts a validated configuration into an nftables ruleset that
// atomically replaces the Ostiole table when loaded with `nft -f`.
func Render(cfg *model.Config) (string, error) {
	if err := cfg.Validate(); err != nil {
		return "", err
	}
	r := &renderer{cfg: cfg}
	r.line(Header)
	r.line("table " + Table)
	r.line("delete table " + Table)
	r.line("table " + Table + " {")
	r.indent++
	r.sets()
	r.chainInput()
	r.chainForward()
	r.chainOutput()
	r.zoneChains()
	r.chainNATPrerouting()
	r.chainNATPostrouting()
	r.indent--
	r.line("}")
	return r.b.String(), nil
}

// EmptyRuleset removes the Ostiole table entirely, restoring the kernel to
// the state before Ostiole was installed (other tables are untouched).
func EmptyRuleset() string {
	return Header + "\n" + "table " + Table + "\n" + "delete table " + Table + "\n"
}

type renderer struct {
	cfg    *model.Config
	b      strings.Builder
	indent int
}

func (r *renderer) line(s string) {
	if s != "" {
		r.b.WriteString(strings.Repeat("\t", r.indent))
		r.b.WriteString(s)
	}
	r.b.WriteByte('\n')
}

func (r *renderer) block(open string, body func()) {
	r.line(open + " {")
	r.indent++
	body()
	r.indent--
	r.line("}")
}

// ---- sets ------------------------------------------------------------

func aliasSet(name string, family int) string {
	return fmt.Sprintf("alias_%s_v%d", name, family)
}

func aliasPortSet(name string) string {
	return "alias_" + name + "_ports"
}

// splitFamilies partitions parsed addresses by IP family, preserving order.
func splitFamilies(addrs []string) (v4, v6 []string) {
	for _, a := range addrs {
		p, err := model.ParseAddress(a)
		if err != nil {
			continue // validated upstream
		}
		s := p.String()
		if p.Bits() == p.Addr().BitLen() {
			s = p.Addr().String()
		}
		if p.Addr().Is4() {
			v4 = append(v4, s)
		} else {
			v6 = append(v6, s)
		}
	}
	return v4, v6
}

func (r *renderer) sets() {
	for _, a := range r.cfg.Aliases {
		switch a.Type {
		case model.AliasHosts:
			v4, v6 := splitFamilies(a.Entries)
			if len(v4) > 0 {
				r.set(aliasSet(a.Name, 4), "ipv4_addr", v4, a.Description)
			}
			if len(v6) > 0 {
				r.set(aliasSet(a.Name, 6), "ipv6_addr", v6, a.Description)
			}
		case model.AliasPorts:
			if len(a.Entries) > 0 {
				ports := make([]string, 0, len(a.Entries))
				for _, e := range a.Entries {
					pr, _ := model.ParsePortRange(e)
					ports = append(ports, pr.String())
				}
				r.set(aliasPortSet(a.Name), "inet_service", ports, a.Description)
			}
		}
	}
}

func (r *renderer) set(name, typ string, elems []string, comment string) {
	r.block("set "+name, func() {
		r.line("type " + typ)
		r.line("flags interval")
		r.line("auto-merge")
		if comment != "" {
			r.line(fmt.Sprintf("comment %q", sanitizeComment(comment)))
		}
		r.line("elements = { " + strings.Join(elems, ", ") + " }")
	})
}

// ---- base chains -------------------------------------------------------

func (r *renderer) chainInput() {
	r.block("chain input", func() {
		r.line("type filter hook input priority filter; policy drop;")
		r.line(`iifname "lo" accept`)
		r.line("ct state established,related accept")
		r.line("ct state invalid drop")
		// Error messages that IPv4 needs to function (no echo: that is a user rule).
		r.line("icmp type { destination-unreachable, time-exceeded, parameter-problem } accept")
		// Neighbour discovery, MLD, and error messages that IPv6 cannot work without.
		r.line("icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert, nd-router-solicit, nd-router-advert, " +
			"destination-unreachable, packet-too-big, time-exceeded, parameter-problem, " +
			"mld-listener-query, mld-listener-report, mld-listener-done } accept")
		r.antiLockout()
		r.serviceRules()
		r.zoneDispatch()
		r.defaultDrop("input")
	})
}

// serviceRules lets DHCP and DNS clients reach the services this box runs,
// regardless of zone rules, on the interfaces that serve them.
func (r *renderer) serviceRules() {
	svc := r.cfg.Services
	if svc.DHCP.Enabled {
		var ifs []string
		for _, sc := range svc.DHCP.Scopes {
			if in, ok := r.cfg.Interface(sc.Interface); ok && sc.Enabled && in.Enabled {
				ifs = append(ifs, sc.Interface)
			}
		}
		if len(ifs) > 0 {
			r.line(fmt.Sprintf(`iifname %s udp dport 67 counter accept comment "service:dhcp"`, ifnameSet(ifs)))
		}
	}
	if svc.DNS.Enabled {
		ifs := DNSInterfaces(r.cfg)
		if len(ifs) > 0 {
			r.line(fmt.Sprintf(`iifname %s meta l4proto { tcp, udp } th dport 53 fib daddr type local counter accept comment "service:dns"`, ifnameSet(ifs)))
		}
	}
}

// DNSInterfaces lists where the DNS service listens: the configured list,
// or every enabled interface outside external zones.
func DNSInterfaces(cfg *model.Config) []string {
	if len(cfg.Services.DNS.Interfaces) > 0 {
		return cfg.Services.DNS.Interfaces
	}
	var ifs []string
	for _, in := range cfg.Interfaces {
		if !in.Enabled || in.Zone == "" {
			continue
		}
		if z, ok := cfg.Zone(in.Zone); ok && !z.External {
			ifs = append(ifs, in.Name)
		}
	}
	return ifs
}

func (r *renderer) chainForward() {
	r.block("chain forward", func() {
		r.line("type filter hook forward priority filter; policy drop;")
		r.line("ct state established,related accept")
		r.line("ct state invalid drop")
		if r.hasPortForwards() {
			r.line(`ct status dnat counter accept comment "port-forwards"`)
		}
		r.zoneDispatch()
		r.defaultDrop("forward")
	})
}

func (r *renderer) chainOutput() {
	r.block("chain output", func() {
		r.line("type filter hook output priority filter; policy accept;")
	})
}

func (r *renderer) antiLockout() {
	m := r.cfg.System.Management
	var ports []string
	if m.WebPort != 0 {
		ports = append(ports, fmt.Sprint(m.WebPort))
	}
	if m.SSHPort != 0 && m.SSHPort != m.WebPort {
		ports = append(ports, fmt.Sprint(m.SSHPort))
	}
	if len(ports) == 0 {
		return
	}
	for _, z := range r.cfg.Zones {
		if !z.AntiLockout {
			continue
		}
		ifs := r.cfg.ZoneInterfaces(z.Name)
		if len(ifs) == 0 {
			continue
		}
		r.line(fmt.Sprintf("iifname %s tcp dport %s counter accept comment \"anti-lockout:%s\"",
			ifnameSet(ifs), setOrSingle(ports), z.Name))
	}
}

func (r *renderer) zoneDispatch() {
	for _, z := range r.cfg.Zones {
		ifs := r.cfg.ZoneInterfaces(z.Name)
		if len(ifs) == 0 {
			continue
		}
		r.line(fmt.Sprintf("iifname %s jump zone_%s", ifnameSet(ifs), z.Name))
	}
}

func (r *renderer) defaultDrop(chain string) {
	if r.cfg.System.Management.LogDefaultDrops {
		r.line(fmt.Sprintf(`counter log prefix "ostiole:%s:drop: " group %d comment "default-drop"`, chain, LogGroup))
		return
	}
	r.line(`counter comment "default-drop"`)
}

// ---- zone chains ---------------------------------------------------------

func (r *renderer) zoneChains() {
	for _, z := range r.cfg.Zones {
		r.block("chain zone_"+z.Name, func() {
			for i := range r.cfg.Rules {
				rule := &r.cfg.Rules[i]
				if rule.Zone != z.Name || !rule.Enabled {
					continue
				}
				r.rule(rule)
			}
			if z.LogDrops {
				r.line(fmt.Sprintf(`counter log prefix "ostiole:%s:drop: " group %d drop comment "zone-default"`, z.Name, LogGroup))
			}
		})
	}
}

// famExpr is the address match for one endpoint. any means unconstrained;
// both is a family-agnostic expression (e.g. "fib daddr type local");
// otherwise v4/v6 hold per-family expressions and nil means the endpoint
// cannot match that family at all.
type famExpr struct {
	any    bool
	both   *string
	v4, v6 *string
}

// split reports whether the endpoint needs per-family rules.
func (f famExpr) split() bool { return !f.any && f.both == nil }

// expr returns the expression for family fam (4 or 6) and whether the
// endpoint can match that family.
func (f famExpr) expr(fam int) (string, bool) {
	switch {
	case f.any:
		return "", true
	case f.both != nil:
		return *f.both, true
	case fam == 4 && f.v4 != nil:
		return *f.v4, true
	case fam == 6 && f.v6 != nil:
		return *f.v6, true
	}
	return "", false
}

func (r *renderer) endpointAddr(dir string, e model.Endpoint) famExpr {
	if e.Self {
		s := "fib daddr type local"
		return famExpr{both: &s}
	}
	if e.Alias != "" {
		a, _ := r.cfg.Alias(e.Alias)
		v4, v6 := splitFamilies(a.Entries)
		var f famExpr
		if len(v4) > 0 {
			s := fmt.Sprintf("ip %s @%s", dir, aliasSet(a.Name, 4))
			f.v4 = &s
		}
		if len(v6) > 0 {
			s := fmt.Sprintf("ip6 %s @%s", dir, aliasSet(a.Name, 6))
			f.v6 = &s
		}
		return f
	}
	if len(e.Addresses) == 0 {
		return famExpr{any: true}
	}
	v4, v6 := splitFamilies(e.Addresses)
	var f famExpr
	if len(v4) > 0 {
		s := fmt.Sprintf("ip %s %s", dir, setOrSingle(v4))
		f.v4 = &s
	}
	if len(v6) > 0 {
		s := fmt.Sprintf("ip6 %s %s", dir, setOrSingle(v6))
		f.v6 = &s
	}
	return f
}

func (r *renderer) rule(rule *model.Rule) {
	var prefix []string
	if rule.DestZone != "" {
		ifs := r.cfg.ZoneInterfaces(rule.DestZone)
		if len(ifs) == 0 {
			r.line(fmt.Sprintf("# rule %s skipped: destination zone %q has no enabled interfaces", rule.ID, rule.DestZone))
			return
		}
		prefix = append(prefix, "oifname "+ifnameSet(ifs))
	}

	src := r.endpointAddr("saddr", rule.Source)
	dst := r.endpointAddr("daddr", rule.Destination)
	l4 := r.l4(rule)

	verdict := []string{"counter"}
	if rule.Log {
		verdict = append(verdict, fmt.Sprintf("log prefix \"ostiole:%s: \" group %d", rule.ID, LogGroup))
	}
	switch rule.Action {
	case model.ActionAccept:
		verdict = append(verdict, "accept")
	case model.ActionDrop:
		verdict = append(verdict, "drop")
	case model.ActionReject:
		if rule.Protocol == model.ProtocolTCP {
			verdict = append(verdict, "reject with tcp reset")
		} else {
			verdict = append(verdict, "reject")
		}
	}
	comment := fmt.Sprintf("comment \"id:%s\"", rule.ID)

	emit := func(addr ...string) {
		parts := append([]string{}, prefix...)
		for _, a := range addr {
			if a != "" {
				parts = append(parts, a)
			}
		}
		if l4 != "" {
			parts = append(parts, l4)
		}
		parts = append(parts, verdict...)
		parts = append(parts, comment)
		r.line(strings.Join(parts, " "))
	}

	if !src.split() && !dst.split() {
		s, _ := src.expr(4)
		d, _ := dst.expr(4)
		emit(s, d)
		return
	}
	emitted := false
	for _, fam := range []int{4, 6} {
		s, sok := src.expr(fam)
		d, dok := dst.expr(fam)
		if !sok || !dok {
			continue
		}
		emit(s, d)
		emitted = true
	}
	if !emitted {
		r.line(fmt.Sprintf("# rule %s skipped: source and destination cannot match the same address family (empty alias, or IPv4 on one side and IPv6 on the other)", rule.ID))
	}
}

// l4 renders the protocol and port match for a rule.
func (r *renderer) l4(rule *model.Rule) string {
	sport := r.ports("sport", rule.Source)
	dport := r.ports("dport", rule.Destination)
	switch rule.Protocol {
	case model.ProtocolTCP, model.ProtocolUDP:
		p := string(rule.Protocol)
		if sport == "" && dport == "" {
			return "meta l4proto " + p
		}
		return strings.TrimSpace(strings.Join([]string{portExpr(p, sport), portExpr(p, dport)}, " "))
	case model.ProtocolTCPUDP:
		if sport == "" && dport == "" {
			return "meta l4proto { tcp, udp }"
		}
		return strings.TrimSpace("meta l4proto { tcp, udp } " + strings.TrimSpace(portExpr("th", sport)+" "+portExpr("th", dport)))
	case model.ProtocolICMP:
		return "meta l4proto { icmp, ipv6-icmp }"
	}
	return ""
}

func portExpr(proto, expr string) string {
	if expr == "" {
		return ""
	}
	return proto + " " + expr
}

// ports renders "dport { … }" style operand for an endpoint, or "".
func (r *renderer) ports(kind string, e model.Endpoint) string {
	if e.PortAlias != "" {
		a, _ := r.cfg.Alias(e.PortAlias)
		if len(a.Entries) == 0 {
			return ""
		}
		return kind + " @" + aliasPortSet(a.Name)
	}
	if len(e.Ports) == 0 {
		return ""
	}
	ps := make([]string, 0, len(e.Ports))
	for _, p := range e.Ports {
		pr, _ := model.ParsePortRange(p)
		ps = append(ps, pr.String())
	}
	return kind + " " + setOrSingle(ps)
}

// ---- NAT ------------------------------------------------------------------

func (r *renderer) hasPortForwards() bool {
	for _, pf := range r.cfg.NAT.PortForwards {
		if pf.Enabled && len(r.cfg.ZoneInterfaces(pf.Zone)) > 0 {
			return true
		}
	}
	return false
}

func (r *renderer) chainNATPrerouting() {
	r.block("chain nat_prerouting", func() {
		r.line("type nat hook prerouting priority dstnat; policy accept;")
		for _, pf := range r.cfg.NAT.PortForwards {
			if !pf.Enabled {
				continue
			}
			ifs := r.cfg.ZoneInterfaces(pf.Zone)
			if len(ifs) == 0 {
				r.line(fmt.Sprintf("# port forward %s skipped: zone %q has no enabled interfaces", pf.ID, pf.Zone))
				continue
			}
			ports := make([]string, 0, len(pf.Ports))
			for _, p := range pf.Ports {
				pr, _ := model.ParsePortRange(p)
				ports = append(ports, pr.String())
			}
			var match string
			switch pf.Protocol {
			case model.ProtocolTCPUDP:
				match = "meta l4proto { tcp, udp } th dport " + setOrSingle(ports)
			default:
				match = string(pf.Protocol) + " dport " + setOrSingle(ports)
			}
			target, _ := model.ParseIP(pf.Target)
			r.line(fmt.Sprintf("iifname %s %s counter dnat %s comment \"id:%s\"",
				ifnameSet(ifs), match, dnatTarget(target, pf.TargetPort), pf.ID))
		}
	})
}

func dnatTarget(ip netip.Addr, port string) string {
	if ip.Is4() {
		if port == "" {
			return "ip to " + ip.String()
		}
		return fmt.Sprintf("ip to %s:%s", ip, port)
	}
	if port == "" {
		return "ip6 to " + ip.String()
	}
	return fmt.Sprintf("ip6 to [%s]:%s", ip, port)
}

func (r *renderer) chainNATPostrouting() {
	r.block("chain nat_postrouting", func() {
		r.line("type nat hook postrouting priority srcnat; policy accept;")
		switch r.cfg.NAT.Outbound.Mode {
		case model.OutboundAutomatic:
			for _, z := range r.cfg.Zones {
				if !z.External {
					continue
				}
				ifs := r.cfg.ZoneInterfaces(z.Name)
				if len(ifs) == 0 {
					continue
				}
				// IPv4 only: masquerading IPv6 would break end-to-end addressing.
				r.line(fmt.Sprintf("oifname %s meta nfproto ipv4 counter masquerade comment \"auto-nat:%s\"",
					ifnameSet(ifs), z.Name))
			}
		case model.OutboundManual:
			for _, o := range r.cfg.NAT.Outbound.Rules {
				if !o.Enabled {
					continue
				}
				ifs := r.cfg.ZoneInterfaces(o.Zone)
				if len(ifs) == 0 {
					r.line(fmt.Sprintf("# outbound nat %s skipped: zone %q has no enabled interfaces", o.ID, o.Zone))
					continue
				}
				if len(o.Source) == 0 {
					r.line(fmt.Sprintf("oifname %s meta nfproto ipv4 counter masquerade comment \"id:%s\"", ifnameSet(ifs), o.ID))
					continue
				}
				v4, v6 := splitFamilies(o.Source)
				if len(v4) > 0 {
					r.line(fmt.Sprintf("oifname %s ip saddr %s counter masquerade comment \"id:%s\"", ifnameSet(ifs), setOrSingle(v4), o.ID))
				}
				if len(v6) > 0 {
					r.line(fmt.Sprintf("oifname %s ip6 saddr %s counter masquerade comment \"id:%s\"", ifnameSet(ifs), setOrSingle(v6), o.ID))
				}
			}
		}
	})
}

// ---- helpers ---------------------------------------------------------------

func ifnameSet(names []string) string {
	quoted := make([]string, 0, len(names))
	for _, n := range names {
		quoted = append(quoted, fmt.Sprintf("%q", n))
	}
	return setOrSingle(quoted)
}

func setOrSingle(items []string) string {
	if len(items) == 1 {
		return items[0]
	}
	return "{ " + strings.Join(items, ", ") + " }"
}

func sanitizeComment(s string) string {
	s = strings.NewReplacer(`"`, "'", "\n", " ", "\\", "/").Replace(s)
	if len(s) > 120 {
		s = s[:120]
	}
	return s
}

// SortedZoneNames is a helper for callers that want deterministic zone order
// independent of configuration order.
func SortedZoneNames(cfg *model.Config) []string {
	names := make([]string, 0, len(cfg.Zones))
	for _, z := range cfg.Zones {
		names = append(names, z.Name)
	}
	sort.Strings(names)
	return names
}
